(function () {
  "use strict";
  // Starter prompts, not a site-specific safe-work procedure. See JSA-WORKFLOW.md.
  const presets = [
    ["Ladders", "Falls; unstable footing; dropped tools", "Consider a work platform first. Inspect and secure the correct ladder on firm footing; maintain three points of contact; keep the landing clear. Keep people out below. Select footwear and head protection for the work."],
    ["Working at heights", "Falls from edges/openings; falling objects; suspension after a fall", "Eliminate work at height where possible. Use suitable guarded platforms and protect openings. Follow the site fall-protection and rescue plan; use trained workers and inspected equipment. Secure tools and establish an exclusion zone."],
    ["Power tools", "Contact with moving parts; electric shock; noise; flying debris", "Inspect tools, guards, leads and accessories. Secure the work; isolate power before adjustment. Use required electrical protection and keep leads clear. Select eye, hearing and other protection for the tool and material."],
    ["Cutting and sawing", "Blade contact; kickback; dust; flying fragments; noise", "Confirm the material and hidden services before cutting. Use the correct guarded tool and blade; support and clamp the work. Control dust at source and separate nearby workers. Select eye/face, hearing and respiratory protection from the assessment."],
    ["Grinding", "Wheel failure; sparks; dust; noise; entanglement", "Use an inspected compatible wheel within the tool rating and keep guards fitted. Secure the work and direct sparks away from people and combustibles. Assess hot-work requirements and dust controls. Use suitable eye/face and hearing protection; assess respiratory protection."],
    ["Silica-producing work", "Respirable silica from concrete/masonry; exposure of nearby workers", "Use a lower-dust method where possible. Apply suitable water suppression or on-tool extraction and isolate the work area. Avoid dry sweeping and compressed-air cleaning. Follow the exposure-control plan and select respiratory protection, fit testing and training as required."],
    ["Demolition", "Unstable structure; hidden services; hazardous materials; falling debris", "Confirm the demolition sequence and structural support with the responsible competent person. Survey hazardous materials and isolate services before disturbance. Establish exclusion zones and control debris/dust. Select task-specific PPE; stop if unexpected materials or instability appear."],
    ["Manual lifting and handling", "Strains; crush/pinch points; sharp edges; obstructed routes", "Reduce load size or use a mechanical aid. Assess weight, grip, route and landing area before lifting. Arrange a coordinated team lift where appropriate; keep hands clear of pinch points. Use suitable gloves and protective footwear."],
    ["Scaffolding", "Falls; collapse; falling objects; unsafe access", "Have competent personnel erect, inspect and alter the scaffold. Confirm foundations, loading, bracing, guarded platforms and safe access. Respect inspection status and load limits; keep people clear below. Follow the site fall-protection plan for erection and alteration."],
    ["Electrical work / isolation", "Shock; arc flash; unexpected energization; overhead/underground services", "Use qualified authorized personnel. Identify every energy source, isolate and lock out under the approved procedure, and verify a safe state before work. Maintain assessed approach limits and protect others. Select electrical PPE and tools through the task-specific assessment."],
    ["Hot work", "Fire; explosion; burns; fumes; sparks reaching adjacent spaces", "Use a cold-work method where practical. Obtain required authorization/permit; remove or protect combustibles and check adjoining spaces. Provide ventilation, fire watch and extinguishing equipment under the site plan. Select welding/face, hand and body protection for the process."],
    ["Excavation", "Cave-in; buried services; falls; water; nearby equipment", "Locate and verify utilities before digging. Have a competent person assess soil, support/sloping, water and adjacent structures. Provide safe access and edge protection; control spoil and equipment near edges. No entry until protective measures and required inspections are in place."],
    ["Mobile equipment", "Struck-by; blind spots; overturning; reversing; overhead hazards", "Use authorized operators and complete pre-use checks. Separate pedestrians and equipment; plan travel routes, ground conditions and overhead clearances. Use agreed signals/spotters where required. Wear seat belts and site visibility PPE; stay outside operating zones."],
    ["Concrete placement and finishing", "Cement burns; pump/line movement; rebar; slips; manual handling", "Plan delivery and hose handling; inspect equipment and control access. Protect exposed reinforcing hazards. Prevent wet-cement skin/eye contact and provide washing facilities. Use suitable waterproof gloves/boots, eye protection and handling aids; assess dust when cutting or cleaning."],
    ["Chemicals / coatings", "Skin/eye contact; inhalation; fire; incompatible products; spills", "Review current SDS and substitute a less hazardous product where practical. Provide suitable ventilation, segregated storage and spill response. Keep containers labelled and control ignition sources. Select chemical-resistant gloves, eye protection and respiratory protection from the assessment."],
    ["Confined spaces", "Oxygen deficiency; toxic/flammable atmosphere; engulfment; restricted rescue", "Do not enter until the space has been assessed and an authorized entry plan/permit is in place. Confirm isolation, atmospheric testing/monitoring, ventilation, attendant, communications and a workable rescue plan. Only trained authorized entrants may proceed with the specified equipment."],
    ["Rigging and hoisting", "Dropped load; rigging failure; pinch points; load swing; overhead services", "Use a planned lift with competent riggers/operators. Verify load weight, lifting points and rated inspected equipment. Establish an exclusion zone and agreed signals; keep everyone clear of suspended loads. Assess ground, wind and service clearances before lifting."],
    ["Occupied areas / public protection", "Public entry; dust/noise; blocked exits; interference with building services", "Coordinate with the client and occupants. Isolate the work, maintain accessible exits and protect essential services. Schedule disruptive work and contain dust at source. Provide clear signs/barriers and inspect the separation throughout the work."],
    ["Housekeeping and access", "Slips/trips; sharp waste; blocked exits; poor lighting", "Keep access routes and emergency exits clear. Remove waste regularly, cover or route leads safely, and maintain lighting. Control spills promptly and segregate sharp waste. Use task-appropriate footwear and hand protection."],
    ["Weather and outdoor work", "Heat/cold stress; lightning; wind; ice; reduced visibility", "Check conditions and adjust or stop exposed work when unsafe. Plan shelter, drinking water, rest breaks and communication. Treat slippery access and secure materials. Select clothing/PPE for the conditions without compromising task protection."]
  ].map(([task, hazards, controls], index) => ({ id: "construction-" + index, task, hazards: hazards.split("; "), controls: controls.split(/\. (?=[A-Z])/).map(s => s.replace(/\.$/, "")) }));
  window.JgcJsaPresets = presets;
}());
