(function () {
  "use strict";
  // Starter prompts, not a site-specific safe-work procedure. See JSA-WORKFLOW.md.
  // Format per task: [task, hazards separated by "; ", controls/PPE as sentences].
  // Controls are split on ". " before a capital letter, so avoid abbreviations such as "e.g." or "O. Reg.".
  const library = [
    ["Access & working at heights", [
      ["Ladders", "Falls; unstable footing; dropped tools", "Consider a work platform first. Inspect and secure the correct ladder on firm footing; maintain three points of contact; keep the landing clear. Keep people out below. Select footwear and head protection for the work."],
      ["Working at heights", "Falls from edges/openings; falling objects; suspension after a fall", "Eliminate work at height where possible. Use suitable guarded platforms and protect openings. Follow the site fall-protection and rescue plan; use trained workers and inspected equipment. Secure tools and establish an exclusion zone."],
      ["Scaffolding", "Falls; collapse; falling objects; unsafe access", "Have competent personnel erect, inspect and alter the scaffold. Confirm foundations, loading, bracing, guarded platforms and safe access. Respect inspection status and load limits; keep people clear below. Follow the site fall-protection plan for erection and alteration."],
      ["Rolling scaffold (baker scaffold)", "Tip-over when moved or overloaded; falls from the platform; casters rolling; overhead contact", "Assemble to the manufacturer's instructions with all braces, deck boards and guardrails in place. Lock every caster before climbing and keep the load within the rating. Move it only on firm, level floors with nobody on the platform. Check overhead clearance and nearby floor openings before moving. Climb the built-in ladder, never the cross-braces."],
      ["Scissor lift / boom lift (elevating work platform)", "Tip-over; falls from the platform; crushing against overhead structure; power-line contact; ground or floor failure", "Only trained, authorized operators; complete the pre-use inspection and function test. Check ground, slopes, floor loading and overhead clearance before driving or raising. Keep gates closed; on boom lifts wear a harness with the lanyard on the designated anchor. Stay within the rated load and wind limit. Use a spotter near people, edges or obstructions and know the emergency lowering procedure."],
      ["Roof work and leading edges", "Falls from roof edges, skylights and openings; fragile surfaces; wind and ice; falling materials", "Plan roof access and edge protection before work starts: guardrails, warning lines or travel restraint under the fall-protection plan. Cover or guard skylights and openings and mark the covers. Do not walk on fragile surfaces without support. Stop work in high wind, ice or lightning. Secure materials and control the area below."],
      ["Floor, wall and shaft openings", "Falls through openings; tripping on covers; objects falling to levels below", "Guard openings with guardrails or secured, load-rated covers marked OPENING - DO NOT REMOVE. Replace protection immediately after each use. Add toe boards or netting where objects could fall. Tell other trades about openings and check covers every shift."],
      ["Temporary stairs, ramps and access routes", "Slips and trips; missing handrails; carrying loads on stairs; poor lighting", "Install handrails and keep treads, landings and ramps clear and lit. Carry loads that leave one hand free for the rail. Use a hoist, material lift or pass-up for bulky items. Treat ice, mud and water on access routes."]
    ]],
    ["Hand & power tools", [
      ["Power tools", "Contact with moving parts; electric shock; noise; flying debris", "Inspect tools, guards, leads and accessories. Secure the work; isolate power before adjustment. Use required electrical protection and keep leads clear. Select eye, hearing and other protection for the tool and material."],
      ["Hand tools", "Cuts; struck by tools; strains; flying fragments from struck tools", "Use the right tool for the job and inspect handles, heads and edges before use. Replace mushroomed chisels, cracked handles and worn wrenches. Cut and strike away from the body and keep others clear. Carry tools in a belt or bag, not in pockets. Wear safety glasses and gloves suited to the task."],
      ["Powder-actuated tools", "Fastener pass-through or ricochet; accidental discharge; noise; flying fragments", "Only trained, authorized operators; check the tool daily and use the correct load and fastener. Confirm the base material and never fire into brittle, hard or thin material or close to edges. Keep the area behind the work clear and hands away from the muzzle. Store charges locked and unload the tool when not in use. Wear eye/face and hearing protection."],
      ["Pneumatic nailers and staplers", "Nail penetration injuries; double firing; ricochet; hose whip", "Use a sequential (single-shot) trigger where available and keep fingers off the trigger when not fastening. Disconnect air before clearing jams, adjusting or servicing. Never point the tool at anyone and keep the free hand out of the nail line. Secure hose fittings and check hoses for damage. Wear safety glasses and hearing protection."],
      ["Drilling and anchoring into concrete or masonry", "Embedded services, rebar or post-tension cables; silica dust; binding and wrist injury; noise", "Scan or check drawings for embedded services before drilling, and never drill post-tensioned slabs without approval. Use a drill with a clutch and side handle and brace against binding. Use on-tool dust extraction with a HEPA vacuum. Wear eye and hearing protection and respiratory protection under the silica plan."],
      ["Core drilling", "Water and electricity; bit binding and rig rotation; cutting services; falling core below", "Scan the slab or wall and confirm the location with the responsible person. Anchor or vacuum-mount the rig and follow the manufacturer's set-up. Use GFCI protection and control slurry for wet drilling. Barricade the area below floor penetrations and plan to catch the core. Wear eye, hearing and foot protection."],
      ["Compressed air and hoses", "Hose whip; air injection through skin; flying particles; noise", "Use whip checks and safety clips on couplings and inspect hoses before use. Depressurize before connecting or disconnecting. Never blow dust off skin or clothing. Use a reduced-pressure nozzle for cleaning and direct it away from people. Wear eye and hearing protection."],
      ["Vibrating tools (hammer drills, breakers, compactors)", "Hand-arm vibration; loss of grip; noise; fatigue", "Choose low-vibration tools and keep them maintained and sharp. Limit trigger time with task rotation and regular breaks. Let the tool do the work and avoid a tight grip. Keep hands warm and dry. Wear anti-vibration gloves where suitable and hearing protection."]
    ]],
    ["Knives, saws, grinding & cutting", [
      ["Cutting and sawing", "Blade contact; kickback; dust; flying fragments; noise", "Confirm the material and hidden services before cutting. Use the correct guarded tool and blade; support and clamp the work. Control dust at source and separate nearby workers. Select eye/face, hearing and respiratory protection from the assessment."],
      ["Grinding", "Wheel failure; sparks; dust; noise; entanglement", "Use an inspected compatible wheel within the tool rating and keep guards fitted. Secure the work and direct sparks away from people and combustibles. Assess hot-work requirements and dust controls. Use suitable eye/face and hearing protection; assess respiratory protection."],
      ["Utility knives and box cutters", "Lacerations to hands, arms and legs; blade snapping", "Use a self-retracting or auto-closing knife and a sharp blade. Cut away from the body on a stable surface, never toward the free hand or legs. Wear cut-resistant gloves on the free hand. Put used blades in a sharps or blade container. Retract the blade before setting the knife down."],
      ["Circular, mitre and table saws", "Kickback; blade contact; flying debris; wood dust; noise", "Keep guards and the riving knife in place and working. Support long stock and use push sticks near the blade. Unplug the saw before blade changes or adjustments. Keep loose gloves, sleeves and cords away from the blade. Use dust extraction and wear eye and hearing protection."],
      ["Reciprocating saw and demolition cutting", "Hidden wires or pipes; blade binding and kickback; vibration; flying debris", "Check behind walls and ceilings for services and isolate them if needed. Use the correct demolition blade and keep the shoe against the work. Hold with two hands and keep the cord clear of the cut. Wear eye protection, gloves and hearing protection."],
      ["Gas cut-off saw (concrete, masonry or metal)", "Kickback/climbing; silica dust; sparks and fire; exhaust fumes (carbon monoxide); noise", "Use water suppression or extraction and a blade rated for the material and saw speed. Do not run the saw indoors or in enclosed areas without ventilation and CO monitoring. Stand out of the line of the blade and secure the work. Apply hot-work controls where sparks can reach combustibles. Wear face shield, hearing protection and respiratory protection."],
      ["Metal cutting and deburring (chop saw, band saw, snips)", "Sharp edges and burrs; hot chips; noise; pinch points", "Clamp stock and keep saw guards in place. Let parts cool before handling and deburr cut edges. Keep hands clear of the blade path. Wear cut-resistant gloves, eye protection and hearing protection."]
    ]],
    ["Dust, silica & hazardous materials", [
      ["Silica-producing work", "Respirable silica from concrete/masonry; exposure of nearby workers", "Use a lower-dust method where possible. Apply suitable water suppression or on-tool extraction and isolate the work area. Avoid dry sweeping and compressed-air cleaning. Follow the exposure-control plan and select respiratory protection, fit testing and training as required."],
      ["Drywall sanding and joint compound", "Fine dust inhalation; eye irritation; falls from stilts or ladders", "Use low-dust compound and vacuum sanders where possible, or wet-sponge finishing. Ventilate the area and keep others away during sanding. Clean with a HEPA vacuum, not dry sweeping. Wear eye protection and at least an N95 respirator."],
      ["Suspected asbestos-containing materials", "Asbestos fibres released by disturbing insulation, tiles, plaster, drywall compound or mastics", "Check the designated-substance / asbestos survey before disturbing any building material. If a suspect material is not covered by the survey, stop work and report it. Only trained workers may disturb asbestos, following the required work classification and procedures. Keep others out of the area until cleared."],
      ["Lead paint disturbance", "Lead dust or fumes from sanding, scraping, cutting or heating painted surfaces", "Confirm paint test results before disturbing old coatings. Avoid dry sanding, power grinding and torching; use wet methods and HEPA extraction. Contain the work area and clean with a HEPA vacuum. Wash hands and face before eating, drinking or smoking. Select respiratory protection from the assessment."],
      ["Mould removal (small areas)", "Spore inhalation; skin and eye irritation; hidden water damage", "Assess the extent; call a specialist for large areas or HVAC contamination. Fix or isolate the moisture source. Mist, remove and bag material without dry brushing, then HEPA vacuum. Keep occupants away. Wear an N95 or better respirator, gloves and goggles."],
      ["Insulation and wood dust", "Respiratory and skin irritation from fibres and fine dust; eye irritation", "Use extraction when cutting and avoid blowing dust with compressed air. Wear long sleeves, gloves and eye protection. Use an N95 or better respirator when handling loose insulation or sanding wood. Wash exposed skin after work."]
    ]],
    ["Demolition", [
      ["Demolition", "Unstable structure; hidden services; hazardous materials; falling debris", "Confirm the demolition sequence and structural support with the responsible competent person. Survey hazardous materials and isolate services before disturbance. Establish exclusion zones and control debris/dust. Select task-specific PPE; stop if unexpected materials or instability appear."],
      ["Interior strip-out and selective demolition", "Live services behind finishes; falling ceiling materials; sharp debris; dust; overloaded floors or bins", "Confirm the scope and that electrical, gas and water services are isolated and marked. Work from the top down and keep people clear below. Remove debris frequently and do not overload floors, carts or bins. Contain dust in occupied buildings. Wear hard hat, eye protection, gloves and puncture-resistant footwear."],
      ["Concrete breaking (jackhammer or breaker)", "Hand-arm vibration; silica dust; flying fragments; noise; embedded services", "Scan for embedded services before breaking. Use water suppression or extraction and anti-vibration tools. Rotate workers to limit vibration and noise time. Barricade the area against flying fragments. Wear face protection, hearing protection, respiratory protection and protective footwear."]
    ]],
    ["Material handling & storage", [
      ["Manual lifting and handling", "Strains; crush/pinch points; sharp edges; obstructed routes", "Reduce load size or use a mechanical aid. Assess weight, grip, route and landing area before lifting. Arrange a coordinated team lift where appropriate; keep hands clear of pinch points. Use suitable gloves and protective footwear."],
      ["Carrying sheet goods (drywall, plywood, panels)", "Back and shoulder strain; wind catching sheets; pinch points; trips", "Use panel carts, dollies or a two-person carry. Plan the route and clear it first. Avoid carrying sheets in strong wind. Store sheets flat or secured against tipping. Wear gloves and protective footwear."],
      ["Hand trucks, dollies and pallet jacks", "Load tipping; crushed feet; losing control on ramps; overloading", "Stay within the rated capacity and strap unstable loads. Push rather than pull where possible and keep feet clear of wheels. Control speed on ramps with help from a second person. Wear protective footwear."],
      ["Receiving deliveries and unloading trucks", "Struck by delivery vehicles; loads falling from the deck; manual handling", "Set a delivery area away from pedestrians and use a spotter for reversing trucks. Check for shifted loads before opening doors or releasing straps. Use a forklift, tailgate lift or hoist for heavy items and keep people out from under loads. Wear high-visibility clothing and protective footwear."],
      ["Material stacking and storage", "Collapse of stacks; blocked access and exits; overloaded floors; rolling pipe", "Stack on firm, level ground to a stable height and chock pipe and round stock. Keep materials back from edges, openings and exits. Stay within floor loading limits on suspended slabs. Label and separate hazardous materials."]
    ]],
    ["Overhead work & falling objects", [
      ["Rigging and hoisting", "Dropped load; rigging failure; pinch points; load swing; overhead services", "Use a planned lift with competent riggers/operators. Verify load weight, lifting points and rated inspected equipment. Establish an exclusion zone and agreed signals; keep everyone clear of suspended loads. Assess ground, wind and service clearances before lifting."],
      ["Overhead drilling and installing (anchors, hangers, conduit)", "Dust and debris falling into eyes; neck and shoulder strain; dropped tools; falls from ladders", "Use a platform or lift instead of a ladder where practical. Use dust extraction and wear goggles or a face shield. Tether tools at height and barricade the area below. Take breaks to reduce strain."],
      ["Ceiling work and above-ceiling access", "Falling tiles and debris; hidden services; sharp hangers and wires; poor lighting", "Check the asbestos survey for ceiling materials before disturbing them. Isolate services that could be contacted. Barricade the area below and provide good lighting. Wear eye protection, gloves and a hard hat."],
      ["Working below other trades", "Struck by falling tools or materials; dropped loads", "Coordinate so crews are not working directly above one another. Use overhead protection, catch platforms or exclusion zones below the work. Require tool tethers and toe boards above. Wear a hard hat and stay out of marked zones."]
    ]],
    ["Electrical tools, cords & temporary power", [
      ["Electrical work / isolation", "Shock; arc flash; unexpected energization; overhead/underground services", "Use qualified authorized personnel. Identify every energy source, isolate and lock out under the approved procedure, and verify a safe state before work. Maintain assessed approach limits and protect others. Select electrical PPE and tools through the task-specific assessment."],
      ["Extension cords and temporary power", "Shock from damaged cords; tripping; overloading; water contact", "Use GFCI protection, especially outdoors and in wet areas. Inspect cords before use and remove any with damaged insulation, missing ground pins or taped repairs. Use cords rated for the load and length. Route cords overhead or cover them across walkways and keep them out of water and doorways."],
      ["Portable generators", "Carbon monoxide; electric shock; fire during refuelling; noise", "Run generators outdoors, well away from doors, windows and air intakes, and never in enclosed spaces. Ground and connect them as the manufacturer requires and use GFCI outlets. Shut down and let the unit cool before refuelling. Keep an extinguisher nearby and wear hearing protection."],
      ["Working near overhead power lines", "Electrocution from contact or arcing through ladders, tools, materials or equipment", "Identify all overhead lines before starting. Keep people, ladders, materials and equipment at least the required minimum distance away (at least 3 m for most distribution lines), or have the utility de-energize or cover the line. Use non-conductive ladders. Assign a signaller when equipment works near lines."]
    ]],
    ["Hot work & fire", [
      ["Hot work", "Fire; explosion; burns; fumes; sparks reaching adjacent spaces", "Use a cold-work method where practical. Obtain required authorization/permit; remove or protect combustibles and check adjoining spaces. Provide ventilation, fire watch and extinguishing equipment under the site plan. Select welding/face, hand and body protection for the process."],
      ["Oxy-fuel cutting, brazing and heating", "Flashback; cylinder damage or leaks; burns; fumes; fire", "Fit flashback arrestors and check hoses and connections for leaks. Keep cylinders upright, chained and capped when not in use, with oxygen stored apart from fuel gas. Shut off cylinder valves after work. Provide a fire watch and extinguisher. Wear the correct shade eye protection, gloves and flame-resistant clothing."],
      ["Propane heaters and cylinders", "Fire; carbon monoxide; cylinder damage; burns", "Only workers trained to handle propane may connect or move cylinders. Use approved heaters with clearance from combustibles and never leave them unattended. Ventilate enclosed areas and monitor for CO. Secure cylinders upright and leak-check connections."],
      ["Fire prevention and extinguishers", "Fire spread; blocked or missing extinguishers; flammable storage", "Keep extinguishers accessible, inspected and suited to the hazard. Store flammables in approved containers or cabinets away from ignition sources. Enforce designated smoking areas. Keep exits and fire routes clear and make sure everyone knows the evacuation route."]
    ]],
    ["Excavation & trenching", [
      ["Excavation", "Cave-in; buried services; falls; water; nearby equipment", "Locate and verify utilities before digging. Have a competent person assess soil, support/sloping, water and adjacent structures. Provide safe access and edge protection; control spoil and equipment near edges. No entry until protective measures and required inspections are in place."],
      ["Trenching and shoring", "Trench collapse; falls into the trench; water accumulation; spoil or tools falling in", "Trenches deeper than 1.2 m need sloping, shoring or a trench box as set by the competent person. Keep spoil and equipment back at least 1 m from the edge. Provide a ladder within easy reach and inspect the trench daily and after rain. Keep workers out while water is accumulating."],
      ["Utility locates and hand digging (daylighting)", "Striking gas, electrical, fibre or water services", "Have valid locates on site before any digging. Hand dig or hydrovac within the locate tolerance zone and expose services before machine digging nearby. Support exposed services. Stop and report any unmarked or damaged service immediately."],
      ["Backfilling and compaction", "Struck by equipment; trench wall failure; compactor vibration, noise and exhaust", "Keep workers out of the trench during machine backfilling. Run compactors outdoors or with good ventilation. Keep feet clear of the plate and use both hands. Wear hearing protection and protective footwear."]
    ]],
    ["Confined & restricted spaces", [
      ["Confined spaces", "Oxygen deficiency; toxic/flammable atmosphere; engulfment; restricted rescue", "Do not enter until the space has been assessed and an authorized entry plan/permit is in place. Confirm isolation, atmospheric testing/monitoring, ventilation, attendant, communications and a workable rescue plan. Only trained authorized entrants may proceed with the specified equipment."],
      ["Crawlspaces, attics and tight spaces", "Heat; poor air; sharp fasteners; insulation fibres; stepping through ceilings; getting stuck", "First confirm whether the space is a designated confined space and follow that procedure if it is. Arrange a buddy or regular check-ins and good lighting. Walk only on joists or boards. Ventilate and take breaks in hot spaces. Wear a respirator for insulation, knee pads, gloves and a bump cap."]
    ]],
    ["Concrete work", [
      ["Concrete placement and finishing", "Cement burns; pump/line movement; rebar; slips; manual handling", "Plan delivery and hose handling; inspect equipment and control access. Protect exposed reinforcing hazards. Prevent wet-cement skin/eye contact and provide washing facilities. Use suitable waterproof gloves/boots, eye protection and handling aids; assess dust when cutting or cleaning."],
      ["Formwork installation and stripping", "Formwork collapse; falls from decks; forms falling during stripping; nail punctures", "Build formwork and shoring to the drawings and have them inspected before the pour. Strip only when authorized and in the planned sequence, keeping the area below clear. Remove or bend protruding nails. Guard deck edges. Wear hard hat, gloves and puncture-resistant footwear."],
      ["Rebar placement and tying", "Impalement on protruding bars; back strain; cuts and punctures", "Cap or cover protruding rebar ends. Use tie-wire twisters or tying tools to reduce wrist strain. Team-lift or crane bundles. Wear gloves, eye protection and protective footwear."],
      ["Concrete pumping", "Hose whip; line blockage or burst; boom contact with power lines; outrigger failure", "Only trained pump operators; set outriggers on pads on firm ground. Keep everyone clear of the hose end during start-up and when clearing blockages. Keep the boom clear of power lines. Agree signals between the operator and the hose crew."],
      ["Grout, patching and small-batch mixing", "Cement burns; dust when opening and mixing bags; manual handling", "Mix outdoors or with extraction and add powder to water slowly. Use bag carts and team lifts for heavy bags. Wear waterproof gloves and eye protection and wash skin promptly after contact."]
    ]],
    ["Chemicals & WHMIS", [
      ["Chemicals / coatings", "Skin/eye contact; inhalation; fire; incompatible products; spills", "Review current SDS and substitute a less hazardous product where practical. Provide suitable ventilation, segregated storage and spill response. Keep containers labelled and control ignition sources. Select chemical-resistant gloves, eye protection and respiratory protection from the assessment."],
      ["Adhesives, solvents and sealants", "Vapour inhalation; flammable vapours; skin irritation", "Read the SDS before use and use low-VOC products where possible. Ventilate the area and remove ignition sources. Keep containers closed when not in use. Wear nitrile gloves and eye protection, and a respirator if the SDS requires it."],
      ["Spray painting and coating application", "Overspray inhalation; flammable vapour build-up; skin and eye contact", "Ventilate or use local exhaust and keep ignition sources away. Mask off and protect nearby people and areas. Select respiratory protection from the SDS and assessment. Wear coveralls, gloves and eye protection."],
      ["WHMIS labelling and decanting", "Unlabelled containers; using the wrong product; splashes when pouring", "Put a workplace label on every decanted container. Keep current SDS accessible on site. Pour with a funnel over a drip tray. Only WHMIS-trained workers handle controlled products. Wear gloves and eye protection."],
      ["Fuel handling and refuelling", "Fire; spills; vapour inhalation", "Shut off and cool engines before refuelling. Use approved, labelled containers and do not overfill. No smoking or ignition sources nearby. Keep a spill kit and extinguisher close."]
    ]],
    ["Vehicles & mobile equipment", [
      ["Mobile equipment", "Struck-by; blind spots; overturning; reversing; overhead hazards", "Use authorized operators and complete pre-use checks. Separate pedestrians and equipment; plan travel routes, ground conditions and overhead clearances. Use agreed signals/spotters where required. Wear seat belts and site visibility PPE; stay outside operating zones."],
      ["Forklift and telehandler operation", "Tip-over; falling loads; struck pedestrians; overhead contact", "Only trained, authorized operators; complete the daily inspection. Stay within the load chart and keep forks low when travelling. Wear the seat belt. Keep pedestrians clear and use a spotter in congested areas. Check overhead clearance before lifting."],
      ["Mini excavator and skid steer", "Struck by swing or attachment; rollover; buried services; quick-coupler failure", "Only trained operators; do a walk-around and confirm locates first. Barricade the swing radius and keep people out. Check that the attachment coupler is locked. Wear the seat belt and lower the bucket or attachment when parked."],
      ["Driving company vehicles and towing trailers", "Collisions; distracted or tired driving; load shift; hitching errors", "Do a circle check and confirm the hitch, safety chains, breakaway and lights before towing. Secure all loads. No handheld phone use while driving. Plan the route and take breaks on long drives."],
      ["Reversing vehicles and spotters", "Struck by reversing vehicles or equipment; blind spots", "Plan routes that minimize reversing. Use backup alarms and cameras where fitted. Use a trained spotter who stays in the operator's view and uses agreed signals. Keep pedestrians out of reversing areas."],
      ["Securing loads on trucks and trailers", "Loads shifting or falling; strap failure; falls from the deck", "Use rated straps or chains with edge protectors and secure the load to the rules for the load type. Do not climb on loads; use a platform or ladder. Recheck the load shortly after starting out."]
    ]],
    ["Traffic & public protection", [
      ["Occupied areas / public protection", "Public entry; dust/noise; blocked exits; interference with building services", "Coordinate with the client and occupants. Isolate the work, maintain accessible exits and protect essential services. Schedule disruptive work and contain dust at source. Provide clear signs/barriers and inspect the separation throughout the work."],
      ["Traffic control and work near roadways", "Struck by traffic; poor visibility; driver confusion", "Set up signs, cones and barriers under a traffic control plan following Ontario Traffic Manual Book 7. Use trained traffic control persons where required. Wear high-visibility clothing and add lighting at night. Park vehicles as a buffer and face oncoming traffic."],
      ["Site hoarding, fencing and pedestrian routes", "Public entering the site; fence blow-over; blocked sidewalks", "Secure fence panels with bases, clamps and bracing. Post site signs and contact information. Keep a safe, accessible alternate pedestrian route. Inspect fencing daily and after high wind."],
      ["Work on or near active rail property", "Struck by trains; unfamiliar railway rules; restricted areas", "Get railway access permission and complete the required orientation before starting. Stay within the approved work area and never go on or near the tracks without railway-provided protection. Wear high-visibility clothing and keep a lookout."]
    ]],
    ["Housekeeping & waste", [
      ["Housekeeping and access", "Slips/trips; sharp waste; blocked exits; poor lighting", "Keep access routes and emergency exits clear. Remove waste regularly, cover or route leads safely, and maintain lighting. Control spills promptly and segregate sharp waste. Use task-appropriate footwear and hand protection."],
      ["Waste bins and debris removal", "Overloaded bins; debris falling from chutes; manual handling; sharp waste", "Enclose chutes and barricade the landing area. Do not overload bins or climb into them. Break down large items and use carts. Wear gloves and eye protection."],
      ["Needles and sharps found on site", "Needlestick injury; exposure to blood", "Do not pick up sharps by hand. Use tongs or a pickup tool and a puncture-resistant sharps container. Report the find to the supervisor. Get first aid and medical follow-up after any needlestick."]
    ]],
    ["Heat, cold & weather", [
      ["Weather and outdoor work", "Heat/cold stress; lightning; wind; ice; reduced visibility", "Check conditions and adjust or stop exposed work when unsafe. Plan shelter, drinking water, rest breaks and communication. Treat slippery access and secure materials. Select clothing/PPE for the conditions without compromising task protection."],
      ["Hot weather and heat stress", "Heat exhaustion and heat stroke; dehydration; fatigue", "Provide cool drinking water and shade and encourage frequent drinks. Schedule heavy work for cooler times and increase rest breaks as the humidex rises. Allow new or returning workers to acclimatize. Watch coworkers for heat illness signs and stop work and cool down anyone affected."],
      ["Cold weather, snow and ice", "Frostbite; hypothermia; slips on ice; strain from snow removal", "Wear layered clothing, insulated gloves and footwear with good grip or ice cleats. Take warm-up breaks. Salt or sand walkways before work. Push rather than lift snow and use the right shovel."]
    ]],
    ["Noise & hearing protection", [
      ["Noise exposure and hearing protection", "Hearing loss; tinnitus; missed warnings", "Use quieter tools and methods and increase distance from noisy work. Wear hearing protection when you must raise your voice to be heard at arm's length. Post hearing protection signs at noisy areas. Keep earplugs and earmuffs clean and fitted properly."]
    ]],
    ["Spill response", [
      ["Fuel, oil or chemical spill response", "Slips; fire; exposure to the product; release to drains or soil", "Stop the source if safe to do so and keep ignition sources away. Contain the spill with the spill kit and protect drains. Check the SDS and wear the required PPE. Report the spill to the supervisor, who reports externally if required. Bag and dispose of contaminated material properly."]
    ]],
    ["Lockout / tagout", [
      ["Lockout of machinery and equipment", "Unexpected start-up; stored hydraulic, pneumatic or spring energy; gravity", "Identify every energy source before work. Apply a personal lock and tag at each isolation point. Release or block stored energy. Try to start the equipment to verify isolation. Only the person who applied a lock removes it."]
    ]],
    ["First aid & emergency", [
      ["First aid, eyewash and emergency readiness", "Delayed treatment; chemical splash to eyes; not knowing emergency contacts", "Know who the first aiders are and where the first aid kit is. Provide an eyewash station (plumbed or portable) where corrosives are used and flush eyes for at least 15 minutes. Post the site address, emergency numbers and route to the nearest hospital. Report every injury, however minor."],
      ["Working alone", "No help after an injury; no communication", "Set a check-in schedule with the supervisor and confirm phone coverage before starting. Do not do high-risk tasks alone. Carry a charged phone and know the site address. Leave details of your location and expected finish time."]
    ]],
    ["General building trades", [
      ["Steel stud framing", "Cuts from sharp edges; metal slivers in eyes; ladder falls", "Wear cut-resistant gloves and safety glasses. Use aviation snips or a stud cutter and keep cut ends turned in. Use platforms rather than ladders for top-track work. Keep offcuts picked up."],
      ["Drywall installation", "Heavy sheets; screw gun injuries; falls from stilts or platforms; dust", "Use a drywall lift for ceilings and team-lift sheets. Keep hands clear of the screw path. Use stilts only on clean, clear floors. Clean with a HEPA vacuum and wear eye protection."],
      ["Painting and wall finishing", "Solvent vapours; falls from ladders; paint splashes in eyes", "Use low-VOC products and ventilate the room. Work from stable platforms and keep ladders on firm footing. Wear goggles for overhead painting and gloves for solvents."],
      ["Flooring removal and installation", "Knee strain; adhesive vapours; sharp tools and staples; possible asbestos in old tile or mastic", "Check the asbestos survey before removing old flooring. Wear knee pads and take breaks. Ventilate when using adhesives. Keep blades sheathed and pick up staples and nails. Wear gloves and eye protection."],
      ["Door, frame and hardware installation", "Heavy doors; pinch points; power tool injuries", "Use a door cart or two-person lift. Wedge doors open during installation and keep fingers clear of hinge gaps. Wear gloves and eye protection when drilling or cutting."],
      ["Glass and glazing handling", "Lacerations; breakage; heavy lifting", "Inspect suction cups before use and carry glass on edge. Barricade the work area. Wear cut-resistant gloves and sleeves and eye protection."],
      ["Fence installation and removal", "Post-hole auger kickback; buried services; heavy panels; pinch points", "Confirm locates before digging. Use a two-person or anti-kickback auger and keep the area clear. Team-lift panels and keep fingers clear when fastening. Wear gloves, eye protection and protective footwear."],
      ["Site walk or inspection visit", "Unfamiliar hazards; entering restricted areas; missing PPE", "Sign in with the site contact and get a site orientation. Wear the PPE the site requires. Stay with an escort and out of restricted areas. Report any unsafe conditions seen."]
    ]]
  ];
  const slug = text => String(text).toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
  window.JgcJsaPresetCategories = library.map(([category]) => category);
  window.JgcJsaPresets = library.flatMap(([category, items]) => items.map(([task, hazards, controls]) => ({
    id: "system:" + slug(task),
    source: "system",
    category,
    task,
    hazards: hazards.split("; "),
    controls: controls.split(/\. (?=[A-Z])/).map(s => s.replace(/\.$/, ""))
  })));
}());
