import { useEffect, useRef, useState, type PointerEvent as ReactPointerEvent } from 'react';
import type { PDFDocumentProxy, PageViewport } from 'pdfjs-dist';
import type { Job } from '../lib/estimator-data';
import { calibrate, emptyDrawing, isMeasurement, measurement, validateContent, type DrawingContent, type Mark, type Point, type Scale } from '../lib/drawing-model';
import { addDrawing, listDrawings, loadDrawing, saveDrawing, type DrawingRecord } from '../src/drawings-api';
import './job-drawings.css';
let engine: ReturnType<typeof importEngine> | undefined;
async function importEngine() { const pdf = await import('pdfjs-dist/legacy/build/pdf.mjs'); pdf.GlobalWorkerOptions.workerSrc = './supplier-import/pdf.worker.min.mjs'; return pdf; }
async function openPdf(bytes: Uint8Array) { engine ??= importEngine(); const pdf = await engine; return pdf.getDocument({ data: bytes.slice() }).promise; }
function download(bytes: Uint8Array | string, filename: string, type: string) { const url=URL.createObjectURL(new Blob([typeof bytes === 'string' ? bytes : bytes.slice().buffer as ArrayBuffer],{type})); const a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000); }
function Thumb({ pdf, number, onClick, selected }: { pdf: PDFDocumentProxy; number: number; onClick: () => void; selected: boolean }) {
  const canvas=useRef<HTMLCanvasElement>(null);
  useEffect(()=>{ let stopped=false, task: ReturnType<Awaited<ReturnType<PDFDocumentProxy['getPage']>>['render']> | undefined;
    void pdf.getPage(number).then(page=>{if(stopped||!canvas.current)return;const base=page.getViewport({scale:1}),v=page.getViewport({scale:110/base.width});canvas.current.width=v.width;canvas.current.height=v.height;task=page.render({canvas:canvas.current,viewport:v});return task.promise;}).catch(()=>{});
    return()=>{stopped=true;task?.cancel();};
  },[pdf,number]);
  return <button className={selected?'selected':''} onClick={onClick} aria-label={`Page ${number}`} aria-current={selected?'page':undefined}><canvas ref={canvas}/><span>{number}</span></button>;
}
export function JobDrawings({job,actor,active}:{job:Job;actor:string;active:boolean}) {
  const [records,setRecords]=useState<DrawingRecord[]>([]),[record,setRecord]=useState<DrawingRecord|null>(null),[title,setTitle]=useState(''),[content,setContent]=useState<DrawingContent>(emptyDrawing),[pdf,setPdf]=useState<PDFDocumentProxy|null>(null);
  const [page,setPage]=useState(1),[zoom,setZoom]=useState(1),[rotation,setRotation]=useState(0),[viewport,setViewport]=useState<PageViewport|null>(null),[tool,setTool]=useState('select'),[color,setColor]=useState('#d62828'),[layer,setLayer]=useState<Mark['layer']>('Review');
  const [error,setError]=useState(''),[busy,setBusy]=useState(false),[saveStatus,setSaveStatus]=useState(''),[draft,setDraft]=useState<Point[]>([]),[selected,setSelected]=useState(''),[note,setNote]=useState(''),[known,setKnown]=useState(''),[unit,setUnit]=useState<Scale['unit']>('ft'),[reference,setReference]=useState<Point[]>([]),[showPages,setShowPages]=useState(true),[showNotes,setShowNotes]=useState(true);
  const canvas=useRef<HTMLCanvasElement>(null),stage=useRef<HTMLDivElement>(null),source=useRef<Uint8Array|null>(null),generation=useRef(0),recordRef=useRef<DrawingRecord|null>(null),current=useRef({content,title}),dirty=useRef(false),saving=useRef(false),blocked=useRef(false),loaded=useRef(false),history=useRef<DrawingContent[]>([]),future=useRef<DrawingContent[]>([]),[historyTick,setHistoryTick]=useState(0),gesture=useRef<Point[]|null>(null),timer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);
  current.current={content,title};
  const flush=async()=>{
    if(saving.current||blocked.current||!recordRef.current||!dirty.current)return;
    saving.current=true;
    try { while(dirty.current&&recordRef.current){dirty.current=false;const snapshot=current.current,base=recordRef.current;setSaveStatus('Savingâ€¦');const saved=await saveDrawing(base,snapshot.content,snapshot.title);recordRef.current=saved;setRecord(saved);setRecords(items=>items.map(r=>r.id===saved.id?saved:r));}setSaveStatus('All drawing changes saved'); }
    catch(e){dirty.current=true;blocked.current=true;setSaveStatus('Not saved');setError(e instanceof Error?e.message:'Could not save drawings.');}
    finally {saving.current=false;}
  };
  const change=(next:DrawingContent)=>{history.current.push(current.current.content);if(history.current.length>50)history.current.shift();future.current=[];setHistoryTick(x=>x+1);current.current={...current.current,content:next};setContent(next);dirty.current=true;setSaveStatus('Unsaved drawing changes');clearTimeout(timer.current);timer.current=setTimeout(()=>void flush(),600);};
  useEffect(()=>{if(!active||loaded.current)return;loaded.current=true;let cancelled=false;setBusy(true);void listDrawings(job.id).then(rows=>{if(!cancelled)setRecords(rows);}).catch(e=>{if(!cancelled)setError(e.message);}).finally(()=>{if(!cancelled)setBusy(false);});return()=>{cancelled=true;loaded.current=false;};},[job.id,active]);
  useEffect(()=>{ const onLeave=(event:BeforeUnloadEvent)=>{if(dirty.current||saving.current){event.preventDefault();event.returnValue='';}};window.addEventListener('beforeunload',onLeave);return()=>{window.removeEventListener('beforeunload',onLeave);clearTimeout(timer.current);void flush();generation.current++;};},[]);
  useEffect(()=>{if(!pdf)return;let cancelled=false,task:ReturnType<Awaited<ReturnType<PDFDocumentProxy['getPage']>>['render']>|undefined;setViewport(null);
    void pdf.getPage(page).then(p=>{if(cancelled||!canvas.current)return;const v=p.getViewport({scale:zoom,rotation:(p.rotate+rotation)%360});const ratio=Math.min(window.devicePixelRatio||1,2,Math.sqrt(16000000/(v.width*v.height)),8192/v.width,8192/v.height);canvas.current.width=Math.ceil(v.width*ratio);canvas.current.height=Math.ceil(v.height*ratio);canvas.current.style.width=`${v.width}px`;canvas.current.style.height=`${v.height}px`;setViewport(v);task=p.render({canvas:canvas.current,viewport:v,transform:ratio===1?undefined:[ratio,0,0,ratio,0,0]});return task.promise;}).catch(e=>{if(!cancelled)setError(e.message);});return()=>{cancelled=true;task?.cancel();};
  },[pdf,page,zoom,rotation]);
  const open=async(r:DrawingRecord,bytes?:Uint8Array)=>{
    if(dirty.current||saving.current){await flush();if(dirty.current||saving.current){setError('Wait for saving to finish, or recover your unsaved markups before switching drawings.');return;}}
    const token=++generation.current;setBusy(true);setError('');
    try { const data=bytes??await loadDrawing(r), doc=await openPdf(data),c=validateContent(r.content);if(token!==generation.current){void doc.loadingTask.destroy();return;}if(c.marks.some(m=>m.page>doc.numPages))throw new Error('A markup references a missing PDF page.');const previous=pdf;setPdf(doc);if(previous)void previous.loadingTask.destroy();source.current=data;recordRef.current=r;current.current={content:c,title:r.title};dirty.current=false;blocked.current=false;setRecord(r);setTitle(r.title);setContent(c);setPage(1);setRotation(0);const first=await doc.getPage(1),v=first.getViewport({scale:1});setZoom(Math.min(1.5,Math.max(.2,((stage.current?.clientWidth||850)-40)/v.width)));history.current=[];future.current=[];setHistoryTick(x=>x+1);setDraft([]);setSelected('');setSaveStatus('All drawing changes saved'); }
    catch(e){setError(e instanceof Error?e.message:'Could not open PDF.');}finally{if(token===generation.current)setBusy(false);}
  };
  const upload=async(file?:File)=>{if(!file)return;if(dirty.current||saving.current){setError('Save the current drawing before uploading another.');return;}setBusy(true);setError('');try{const data=new Uint8Array(await file.arrayBuffer());if(data.length>25*1024*1024)throw new Error('Choose a PDF smaller than 25 MB.');const test=await openPdf(data);await test.loadingTask.destroy();const result=await addDrawing(job.id,file);setRecords(items=>[result.record,...items]);await open(result.record,result.bytes);}catch(e){setError(e instanceof Error?e.message:'Upload failed. Refresh the register to check for an incomplete upload before retrying.');}finally{setBusy(false);}};
  const point=(event:ReactPointerEvent<SVGSVGElement>):Point=>{const box=event.currentTarget.getBoundingClientRect();const [x,y]=viewport!.convertToPdfPoint((event.clientX-box.left)*viewport!.width/box.width,(event.clientY-box.top)*viewport!.height/box.height);return{x,y};};
  const append=(kind:Mark['kind'],points:Point[])=>{if(blocked.current)return;if(kind==='text'&&!note.trim()){setError('Type your note in the Markup text box, then click the drawing to place it.');return;}const mark:Mark={id:crypto.randomUUID(),page,kind,points,color,text:note.trim(),author:actor,createdAt:new Date().toISOString(),layer};change({...current.current.content,marks:[...current.current.content.marks,mark]});setSelected(mark.id);setDraft([]);};
  const down=(event:ReactPointerEvent<SVGSVGElement>)=>{if(!viewport||busy||blocked.current||tool==='select'||event.button!==0)return;event.preventDefault();const p=point(event);if(tool==='area'||tool==='perimeter'){setDraft(points=>[...points,p]);return;}if(tool==='text'){append('text',[p]);return;}event.currentTarget.setPointerCapture(event.pointerId);gesture.current=[p];setDraft([p]);};
  const move=(event:ReactPointerEvent<SVGSVGElement>)=>{if(!gesture.current||!viewport)return;const p=point(event),first=gesture.current[0];gesture.current=tool==='pen'?[...gesture.current,p]:[first,p];setDraft(gesture.current);};
  const up=()=>{const points=gesture.current;gesture.current=null;if(!points||points.length<2){setDraft([]);return;}if(tool==='calibrate'){setReference(points);setShowNotes(true);setDraft([]);}else if(['line','rectangle','distance','pen'].includes(tool))append(tool as Mark['kind'],points);};
  const finish=()=>{if((tool==='area'&&draft.length<3)||(tool==='perimeter'&&draft.length<2))return;append(tool as Mark['kind'],draft);};
  const undo=(redo=false)=>{const from=redo?future.current:history.current,to=redo?history.current:future.current,next=from.pop();if(!next||blocked.current)return;to.push(current.current.content);current.current={...current.current,content:next};setContent(next);dirty.current=true;setHistoryTick(x=>x+1);clearTimeout(timer.current);timer.current=setTimeout(()=>void flush(),600);setSaveStatus('Unsaved drawing changes');};
  const scale=content.scales[String(page)],marks=content.marks.filter(m=>m.page===page),selectedMark=content.marks.find(m=>m.id===selected);
  const transform=(p:Point)=>viewport?viewport.convertToViewportPoint(p.x,p.y):[0,0];
  const shape=(m:Mark,preview=false)=>{const pts=m.points.map(transform),coords=pts.map(p=>p.join(',')).join(' '),label=isMeasurement(m.kind)?measurement(m,scale):m.kind==='text'?m.text:'';
    return <g key={m.id} className={!preview&&selected===m.id?'drawing-mark selected':'drawing-mark'} style={{color:m.color,strokeWidth:1.5*zoom}} onPointerDown={event=>{if(tool==='select'&&!preview){event.stopPropagation();setSelected(m.id);setShowNotes(true);}}} role={!preview?'button':undefined} tabIndex={!preview&&tool==='select'?0:undefined} aria-label={!preview?`${m.kind}: ${label||m.text||m.layer}`:undefined} onKeyDown={event=>{if(event.key==='Enter'){setSelected(m.id);setShowNotes(true);}}}>
      {m.kind==='rectangle'&&pts[1]?<rect x={Math.min(pts[0][0],pts[1][0])} y={Math.min(pts[0][1],pts[1][1])} width={Math.abs(pts[1][0]-pts[0][0])} height={Math.abs(pts[1][1]-pts[0][1])}/>:m.kind==='area'?<polygon points={coords}/>:m.kind!=='text'?<polyline points={coords}/>:null}
      {label&&<text x={pts[0][0]} y={pts[0][1]} fontSize={10*zoom}>{label.split("\n").map((line,i)=><tspan key={i} x={pts[0][0]} dy={i?12*zoom:0}>{line}</tspan>)}</text>}
    </g>;
  };
  const fit=async()=>{if(!pdf||!stage.current)return;const p=await pdf.getPage(page),v=p.getViewport({scale:1,rotation:(p.rotate+rotation)%360});setZoom(Math.min(4,Math.max(.1,(stage.current.clientWidth-40)/v.width)));};
  const exportPdf=async()=>{if(!source.current||!record)return;setBusy(true);setError('');try{await flush();if(dirty.current)throw new Error('Save your markups before exporting. Use Recover markups if saving is blocked.');const {markedDrawingPdf}=await import('../lib/drawing-pdf');const bytes=await markedDrawingPdf(source.current,current.current.content);download(bytes,`${title.replace(/[^a-z0-9 _-]/gi,'').trim()||'Drawing'} - JGC marked.pdf`,'application/pdf');}catch(e){setError(e instanceof Error?e.message:'Could not export drawing.');}finally{setBusy(false);}};
  // Component stays mounted across Job tabs so pending saves finish safely.
  return <section className="job-drawings" hidden={!active} aria-label="Job drawings">
    <header className="drawing-heading"><div><span className="eyebrow">JGC Â· DRAWING WORKSPACE</span><h2>Drawings</h2><p>Review, measure and record as-built changes for Job {job.jobNumber}.</p></div><label className={`button primary ${busy?'disabled':''}`}>ï¼‹ Upload PDF<input type="file" accept="application/pdf,.pdf" disabled={busy||blocked.current} onChange={e=>{void upload(e.target.files?.[0]);e.target.value='';}}/></label></header>
    {error&&<div className="drawing-notice" role="alert"><p>{error}</p>{record&&<div><button className="button secondary compact" disabled={busy||saving.current} onClick={()=>{if(dirty.current&&!window.confirm('Reload will discard unsaved markups. Download Recover unsaved markups first if you need to keep them. Continue?'))return;dirty.current=false;blocked.current=false;void listDrawings(job.id).then(rows=>{setRecords(rows);const latest=rows.find(r=>r.id===record.id);if(latest)void open(latest);}).catch(e=>setError(e.message));}}>Reload saved drawing</button><button className="button secondary compact" onClick={()=>download(JSON.stringify({drawingId:record.id,fileName:record.file_name,...current.current.content},null,2),'JGC unsaved markups.json','application/json')}>Recover unsaved markups</button></div>}</div>}
    <div className="drawing-register"><label>Drawing<select aria-label="Select drawing" value={record?.id??''} disabled={busy||saving.current} onChange={e=>{const r=records.find(r=>r.id===e.target.value);if(r)void open(r);}}><option value="">Choose a drawingâ€¦</option>{records.map(r=><option key={r.id} value={r.id}>{r.title}</option>)}</select></label><span role="status">{busy?'Workingâ€¦':saveStatus||`${records.length} shared drawing${records.length===1?'':'s'}`}</span></div>
    {!pdf?<div className="drawing-empty"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M6 2h8l4 4v16H6zM14 2v5h5M9 12h6M9 16h6"/></svg><h3>{busy?'Opening drawingâ€¦':'Your Job drawings, together'}</h3><p>Upload a PDF or choose a saved drawing. The original stays intact; markups are saved separately and included in your marked PDF export.</p></div>:<>
      <div className="drawing-document-title"><input aria-label="Drawing title" value={title} disabled={busy||blocked.current} onChange={e=>{setTitle(e.target.value);current.current={...current.current,title:e.target.value};dirty.current=true;setSaveStatus('Unsaved drawing changes');clearTimeout(timer.current);timer.current=setTimeout(()=>void flush(),600);}}/><span>{record?.file_name} Â· Shared with JGC admins</span></div>
      <div className="drawing-toolbar" role="toolbar" aria-label="Drawing tools">
        <button aria-pressed={showPages} onClick={()=>setShowPages(v=>!v)}>Pages</button>
        {([['select','Select'],['pen','Pen'],['line','Line'],['rectangle','Box'],['text','Text'],['calibrate','Set scale'],['distance','Distance'],['perimeter','Perimeter'],['area','Area']] as const).map(([key,label])=><button key={key} disabled={busy||blocked.current||(isMeasurement(key)&&!scale)} aria-pressed={tool===key} title={isMeasurement(key)&&!scale?'Set this pageâ€™s scale first':label} onClick={()=>{setTool(key);setDraft([]);setError('');if(key==='text'||key==='calibrate')setShowNotes(true);}}>{label}</button>)}
        <label className="drawing-color">Colour<input type="color" aria-label="Markup colour" value={color} onChange={e=>setColor(e.target.value)}/></label>
        <select aria-label="Markup layer" value={layer} onChange={e=>setLayer(e.target.value as Mark['layer'])}><option>Review</option><option>As-built</option></select>
        <button disabled={!history.current.length||blocked.current||busy} onClick={()=>undo()}>Undo</button><button disabled={!future.current.length||blocked.current||busy} onClick={()=>undo(true)}>Redo</button>
        <button aria-pressed={showNotes} onClick={()=>setShowNotes(v=>!v)}>Comments</button><button className="drawing-export" disabled={busy||blocked.current} onClick={()=>void exportPdf()}>Download marked PDF</button>
      </div>
      <div className="drawing-viewbar"><button disabled={page===1||busy} onClick={()=>{setPage(p=>p-1);setDraft([]);setReference([]);}}>â€¹</button><label>Page <input aria-label="Page number" type="number" min={1} max={pdf.numPages} value={page} onChange={e=>{const n=Number(e.target.value);if(Number.isInteger(n)&&n>=1&&n<=pdf.numPages){setPage(n);setDraft([]);setReference([]);}}}/> of {pdf.numPages}</label><button disabled={page===pdf.numPages||busy} onClick={()=>{setPage(p=>p+1);setDraft([]);setReference([]);}}>â€º</button><button onClick={()=>setZoom(z=>Math.max(.1,z/1.25))}>âˆ’</button><span>{Math.round(zoom*100)}%</span><button onClick={()=>setZoom(z=>Math.min(4,z*1.25))}>ï¼‹</button><button onClick={()=>void fit()}>Fit width</button><button onClick={()=>setRotation(r=>(r+90)%360)}>Rotate view</button><span className="drawing-scale-label">{scale?`Calibrated Â· ${scale.knownLength} ${scale.unit} reference`:'Page scale not set'}</span></div>
      <div className={`drawing-workspace ${showPages?'with-pages':''} ${showNotes?'with-comments':''}`}>
        {showPages&&<aside className="drawing-thumbnails" aria-label="Page thumbnails">{Array.from({length:pdf.numPages},(_,i)=><Thumb key={i} pdf={pdf} number={i+1} selected={page===i+1} onClick={()=>{setPage(i+1);setDraft([]);setReference([]);}}/>)}</aside>}
        <div ref={stage} className="drawing-stage" tabIndex={0} aria-label="PDF drawing view"><div className="drawing-sheet" style={viewport?{width:viewport.width,height:viewport.height}:undefined}><canvas ref={canvas}/>{viewport&&<svg aria-label="Drawing markup canvas" viewBox={`0 0 ${viewport.width} ${viewport.height}`} width={viewport.width} height={viewport.height} className={`drawing-overlay tool-${tool}`} onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={()=>{gesture.current=null;setDraft([]);}}>{marks.map(m=>shape(m))}{draft.length>0&&shape({id:'preview',page,kind:tool==='calibrate'?'line':tool as Mark['kind'],points:draft,color,text:note,author:actor,createdAt:'',layer},true)}</svg>}</div></div>
        {showNotes&&<aside className="drawing-comments"><h3>Page {page} Â· Markups</h3><p className="drawing-hint">{tool==='select'?'Select a markup to view its details.':tool==='area'||tool==='perimeter'?'Click each corner, then Finish.':tool==='text'?'Type below, then click the drawing.':tool==='calibrate'?'Drag along a known dimension, then enter its actual length below.':'Drag on the drawing to add a markup.'}</p>
          {['area','perimeter'].includes(tool)&&<div><button className="button primary compact" disabled={draft.length<(tool==='area'?3:2)} onClick={finish}>Finish {tool}</button><button className="button secondary compact" onClick={()=>setDraft([])}>Cancel</button></div>}
          <label>Markup text<textarea aria-label="Markup text" value={note} maxLength={2000} onChange={e=>setNote(e.target.value)}/></label>
          <fieldset><legend>Page scale</legend><p>{scale?`${scale.knownLength} ${scale.unit} reference saved`:'Calibrate each page before measuring.'}</p><label>Known length<input aria-label="Known length" type="number" min="0.0001" step="any" value={known} onChange={e=>setKnown(e.target.value)}/></label><select aria-label="Scale units" value={unit} onChange={e=>setUnit(e.target.value as Scale['unit'])}><option value="ft">Feet (decimal)</option><option value="m">Metres</option></select><button className="button secondary compact" disabled={reference.length!==2||blocked.current} onClick={()=>{try{const s=calibrate(reference,Number(known),unit);change({...current.current.content,scales:{...current.current.content.scales,[page]:s}});setReference([]);setTool('distance');setError('');}catch(e){setError((e as Error).message);}}}>Apply page scale</button></fieldset>
          {selectedMark&&<div className="drawing-selection"><strong>{selectedMark.kind} Â· {selectedMark.layer}</strong><p>{selectedMark.text||'No comment'}</p>{isMeasurement(selectedMark.kind)&&<p>{measurement(selectedMark,content.scales[String(selectedMark.page)])}</p>}<small>{selectedMark.author} Â· {new Date(selectedMark.createdAt).toLocaleString()}</small><button className="button secondary compact" disabled={blocked.current} onClick={()=>{change({...current.current.content,marks:current.current.content.marks.filter(m=>m.id!==selected)});setSelected('');}}>Remove markup</button></div>}
          <ul>{marks.map(m=><li key={m.id}><button className={m.id===selected?'selected':''} onClick={()=>setSelected(m.id)}><span style={{background:m.color}}/><strong>{m.layer} Â· {m.kind}</strong><small>{isMeasurement(m.kind)?measurement(m,scale):m.text||m.author}</small></button></li>)}</ul>
        </aside>}
      </div><footer className="drawing-footer">Original PDF preserved Â· Markups autosave separately Â· Scale is specific to each page; verify against a known dimension. <button onClick={()=>source.current&&download(source.current,record?.file_name||'Original.pdf','application/pdf')}>Download original</button></footer>
    </>}
  </section>;
}
