import { useEffect, useId, useLayoutEffect, useRef, useState, type PointerEvent as ReactPointerEvent, type MouseEvent as ReactMouseEvent } from 'react';
import { createPortal } from 'react-dom';
import type { PDFDocumentProxy, PageViewport } from 'pdfjs-dist';
import type { Job } from '../lib/estimator-data';
import { calibrate, commentLines, dimensionGeometry, drawingPageOrder, reorderDrawingPages, DRAWING_MAX_BYTES, DRAWING_MAX_MB, emptyDrawing, isMeasurement, measurement, replacePageScale, scaleReferenceLabel, validateContent, type DrawingContent, type Mark, type MeasurementUnit, type Point, type Scale, type ReviewStamp } from '../lib/drawing-model';
import { addDrawing, listDrawings, loadDrawing, saveDrawing, type DrawingRecord } from '../src/drawings-api';
import { drawingSegments, snapPoint, type Segment } from '../lib/drawing-snap';
import { DrawingIcon, ReviewStampGraphic, StampFields } from './drawing-controls';
import './job-drawings.css';
const phoneQuery='(max-width: 600px), (max-width: 1000px) and (max-height: 500px)';
let engine: ReturnType<typeof importEngine> | undefined;
async function importEngine() { const pdf = await import('pdfjs-dist/legacy/build/pdf.mjs'); pdf.GlobalWorkerOptions.workerSrc = './supplier-import/pdf.worker.min.mjs'; return pdf; }
async function openPdf(bytes: Uint8Array) { engine ??= importEngine(); const pdf = await engine; return pdf.getDocument({ data: bytes.slice() }).promise; }
function download(bytes: Uint8Array | string, filename: string, type: string) { const url=URL.createObjectURL(new Blob([typeof bytes === 'string' ? bytes : bytes.slice().buffer as ArrayBuffer],{type})); const a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000); }
const lineCache=new WeakMap<PDFDocumentProxy,Map<number,Promise<Segment[]>>>();
async function pageLines(pdf:PDFDocumentProxy,number:number):Promise<Segment[]> {
  let pages=lineCache.get(pdf);if(!pages){pages=new Map();lineCache.set(pdf,pages);}
  if(!pages.has(number))pages.set(number,(async()=>{engine??=importEngine();const lib=await engine;return drawingSegments(await pdf.getPage(number),lib.OPS);})().catch(()=>[]));
  return pages.get(number)!;
}
function Thumb({ pdf, number, label, onClick, selected, selection }: { pdf: PDFDocumentProxy; number: number; label: number; onClick: (event: ReactMouseEvent<HTMLButtonElement>) => void; selected: boolean; selection?: boolean }) {
  const canvas=useRef<HTMLCanvasElement>(null),[visible,setVisible]=useState(false);
  useEffect(()=>{if(!canvas.current)return;const observer=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting))setVisible(true);});observer.observe(canvas.current);return()=>observer.disconnect();},[]);
  useEffect(()=>{ if(!visible&&!selected)return;let stopped=false, task: ReturnType<Awaited<ReturnType<PDFDocumentProxy['getPage']>>['render']> | undefined;
    void pageLines(pdf,number).then(()=>pdf.getPage(number)).then(page=>{if(stopped||!canvas.current)return;const base=page.getViewport({scale:1}),v=page.getViewport({scale:110/base.width});canvas.current.width=v.width;canvas.current.height=v.height;task=page.render({canvas:canvas.current,viewport:v});return task.promise;}).catch(()=>{});
    return()=>{stopped=true;task?.cancel();};
  },[pdf,number,visible,selected]);
  return <button className={selected?'selected':''} onClick={onClick} aria-label={`Page ${label}`} aria-current={!selection&&selected?'page':undefined} aria-pressed={selection?selected:undefined}><canvas ref={canvas}/><span>Page {label}</span></button>;
}
function PanelTab({ side, expanded, controls, onClick }: { side: 'pages'|'markups'; expanded: boolean; controls: string; onClick: () => void }) {
  const label=`${expanded?'Hide':'Show'} ${side==='pages'?'pages':'markup panel'}`,right=side==='pages'?!expanded:expanded;
  return <button type="button" className={`drawing-panel-tab drawing-${side}-tab`} aria-label={label} title={label} aria-expanded={expanded} aria-controls={controls} onClick={onClick}><svg viewBox="0 0 20 16" aria-hidden="true"><path d={right?'m8 3 5 5-5 5z':'m12 3-5 5 5 5z'}/></svg></button>;
}
export function JobDrawings({job,actor,active}:{job:Job;actor:string;active:boolean}) {
  const [records,setRecords]=useState<DrawingRecord[]>([]),[record,setRecord]=useState<DrawingRecord|null>(null),[title,setTitle]=useState(''),[content,setContent]=useState<DrawingContent>(emptyDrawing),[pdf,setPdf]=useState<PDFDocumentProxy|null>(null);
  const [showRemoved,setShowRemoved]=useState(false),visibleRecords=records.filter(r=>showRemoved||!r.content.archived);
  const [page,setPage]=useState(1),[zoom,setZoom]=useState(1),[rotation,setRotation]=useState(0),[viewport,setViewport]=useState<PageViewport|null>(null),[tool,setTool]=useState('select'),[color,setColor]=useState('#d62828'),[layer,setLayer]=useState<Mark['layer']>('Review');
  const [error,setError]=useState(''),[busy,setBusy]=useState(false),[saveStatus,setSaveStatus]=useState(''),[draft,setDraft]=useState<Point[]>([]),[selected,setSelected]=useState(''),[known,setKnown]=useState(''),[unit,setUnit]=useState<Scale['unit']>('ft-in'),[outputUnit,setOutputUnit]=useState<MeasurementUnit|null>(null),[reference,setReference]=useState<Point[]>([]),[showPages,setShowPages]=useState(()=>!window.matchMedia(phoneQuery).matches),[showNotes,setShowNotes]=useState(()=>!window.matchMedia(phoneQuery).matches);
  const [uploadProgress,setUploadProgress]=useState<number|null>(null),[mode,setMode]=useState('navigate'),[snap,setSnap]=useState(false),[snapAt,setSnapAt]=useState<Point|null>(null),[lines,setLines]=useState<Segment[]>([]),[inches,setInches]=useState(''),[full,setFull]=useState<'none'|'native'|'window'>('none'),[files,setFiles]=useState<File[]>([]);
  const [mobileTools,setMobileTools]=useState(false);
  const [stamp,setStamp]=useState<ReviewStamp>({status:'Reviewed',reviewer:actor,date:new Intl.DateTimeFormat('en-CA',{timeZone:'America/Toronto',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()),width:260});
  const viewer=useRef<HTMLDivElement>(null),commentInput=useRef<HTMLTextAreaElement>(null),scrollEdge=useRef<'top'|'bottom'|null>(null),pageLock=useRef(0),wheelTime=useRef(0),wheelDelta=useRef(0),touchStart=useRef<number|null>(null),dragPage=useRef<number[]|null>(null),[pageDrop,setPageDrop]=useState<{page:number|null;after:boolean}|null>(null),[selectedPages,setSelectedPages]=useState<number[]>([]),[multiSelect,setMultiSelect]=useState(false),organizer=useRef<HTMLDivElement>(null),selectionAnchor=useRef<number|null>(null),organizerMode=useRef('navigate'),organizerOrder=useRef<number[]>([]);
  const order=pdf?drawingPageOrder(content,pdf.numPages):[],sourcePage=order[page-1]??1;
  const organizerTrigger=useRef<HTMLButtonElement|null>(null);
  const measureStart=useRef<Point|null>(null),dimensionDrag=useRef<Mark|null>(null),dimensionLatest=useRef<{id:string;offset:number}|null>(null),[dimensionPreview,setDimensionPreview]=useState<{id:string;offset:number}|null>(null);
  const pan=useRef<{x:number;y:number;left:number;top:number}|null>(null),uploading=useRef(false);
  const stampDrag=useRef<{kind:'move'|'resize';mark:Mark;start:Point;latest:Mark|null}|null>(null),[markPreview,setMarkPreview]=useState<Mark|null>(null);
  const panelId=useId(),zoomValue=useRef(zoom),zoomAnchor=useRef<{x:number;y:number;offsetX:number;offsetY:number;page:number;zoom:number}|null>(null),renderedView=useRef<{pdf:PDFDocumentProxy;page:number;rotation:number}|null>(null);
  zoomValue.current=zoom;organizerOrder.current=order;
  const canvas=useRef<HTMLCanvasElement>(null),stage=useRef<HTMLDivElement>(null),source=useRef<Uint8Array|null>(null),generation=useRef(0),recordRef=useRef<DrawingRecord|null>(null),current=useRef({content,title}),dirty=useRef(false),saving=useRef(false),blocked=useRef(false),loaded=useRef(false),history=useRef<DrawingContent[]>([]),future=useRef<DrawingContent[]>([]),[historyTick,setHistoryTick]=useState(0),gesture=useRef<Point[]|null>(null),timer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);
  current.current={content,title};
  const reportSave=(value:string)=>{setSaveStatus(value);window.dispatchEvent(new CustomEvent('jgc-drawing-save-status',{detail:value==='Not saved'?'error':value==='Saving\u2026'||value==='Unsaved drawing changes'?'saving':'saved'}));};
  const stash=()=>{if(!recordRef.current)return;try{localStorage.setItem('jgc-drawing-recovery-'+recordRef.current.id,JSON.stringify({...current.current,baseRevision:recordRef.current.revision}));}catch{setError('Local recovery is unavailable. Keep this page open until shared saving finishes.');}};

  const flush=async()=>{
    if(saving.current||blocked.current||!recordRef.current||!dirty.current)return;
    saving.current=true;
    try { while(dirty.current&&recordRef.current){dirty.current=false;const snapshot=current.current,base=recordRef.current;reportSave('Saving…');const saved=await saveDrawing(base,snapshot.content,snapshot.title);recordRef.current=saved;setRecord(saved);setRecords(items=>items.map(r=>r.id===saved.id?saved:r));}if(recordRef.current)localStorage.removeItem('jgc-drawing-recovery-'+recordRef.current.id);reportSave('All drawing changes saved');
    }
    catch(e){dirty.current=true;blocked.current=true;reportSave('Not saved');setError(e instanceof Error?e.message:'Could not save drawings.');}
    finally {saving.current=false;}
  };
  const change=(next:DrawingContent)=>{history.current.push(current.current.content);if(history.current.length>50)history.current.shift();future.current=[];setHistoryTick(x=>x+1);current.current={...current.current,content:next};setContent(next);dirty.current=true;stash();reportSave('Unsaved drawing changes');clearTimeout(timer.current);timer.current=setTimeout(()=>void flush(),600);};
  const patchMark=(id:string,patch:Partial<Mark>)=>{if(busy||blocked.current)return;change({...current.current.content,marks:current.current.content.marks.map(m=>m.id===id?{...m,...patch}:m)});};
  const removeMark=(id:string)=>{if(busy||blocked.current)return;change({...current.current.content,marks:current.current.content.marks.filter(m=>m.id!==id)});setSelected('');};
  useEffect(()=>{const mark=content.marks.find(m=>m.id===selected);if(mark&&['text','callout'].includes(mark.kind))requestAnimationFrame(()=>commentInput.current?.focus({preventScroll:true}));},[selected]);
  useEffect(()=>{if(!active||loaded.current)return;loaded.current=true;let cancelled=false;setBusy(true);void listDrawings(job.id).then(rows=>{if(!cancelled)setRecords(rows);}).catch(e=>{if(!cancelled)setError(e.message);}).finally(()=>{if(!cancelled)setBusy(false);});return()=>{cancelled=true;loaded.current=false;};},[job.id,active]);
  useEffect(()=>{ const onLeave=(event:BeforeUnloadEvent)=>{if(dirty.current||saving.current||uploading.current){event.preventDefault();event.returnValue='';}};window.addEventListener('beforeunload',onLeave);return()=>{window.removeEventListener('beforeunload',onLeave);clearTimeout(timer.current);void flush();generation.current++;};},[]);
  useEffect(()=>{
    const changed=()=>{if(document.fullscreenElement===viewer.current)setFull('native');else setFull(value=>value==='native'?'none':value);};
    const escape=(event:KeyboardEvent)=>{if(event.key==='Escape')setFull(value=>value==='window'?'none':value);};
    document.addEventListener('fullscreenchange',changed);window.addEventListener('keydown',escape);
    return()=>{document.removeEventListener('fullscreenchange',changed);window.removeEventListener('keydown',escape);};
  },[]);
  useEffect(()=>{if(full==='window'){const previous=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=previous;};}},[full]);
  useEffect(()=>{if(!active&&full!=='none'){if(document.fullscreenElement)void document.exitFullscreen();setFull('none');}},[active,full]);
  const toggleFull=async()=>{if(full!=='none'){if(document.fullscreenElement)await document.exitFullscreen();setFull('none');return;}if(viewer.current?.requestFullscreen){try{await viewer.current.requestFullscreen();setFull('native');return;}catch{/* Use a full-window viewer on unsupported devices. */}}setFull('window');};
  const navigate=(next:number,edge:'top'|'bottom'='top')=>{if(!pdf||busy||next<1||next>pdf.numPages||next===page)return;zoomAnchor.current=null;scrollEdge.current=edge;pageLock.current=Date.now()+850;setPage(next);setDraft([]);setSelected('');setReference([]);setTool(value=>value==='calibrate'?'select':value);setSnapAt(null);measureStart.current=null;};
  useEffect(()=>{if(!pdf)return;let cancelled=false,task:ReturnType<Awaited<ReturnType<PDFDocumentProxy['getPage']>>['render']>|undefined;const previous=renderedView.current;if(previous?.pdf!==pdf||previous.page!==sourcePage||previous.rotation!==rotation)setViewport(null);renderedView.current={pdf,page:sourcePage,rotation};
    void pageLines(pdf,sourcePage).then(found=>{if(!cancelled)setLines(found);return pdf.getPage(sourcePage);}).then(p=>{if(cancelled||!canvas.current)return;const v=p.getViewport({scale:zoom,rotation:(p.rotate+rotation)%360});const ratio=Math.min(window.devicePixelRatio||1,2,Math.sqrt(16000000/(v.width*v.height)),8192/v.width,8192/v.height);canvas.current.width=Math.ceil(v.width*ratio);canvas.current.height=Math.ceil(v.height*ratio);canvas.current.style.width=`${v.width}px`;canvas.current.style.height=`${v.height}px`;setViewport(v);task=p.render({canvas:canvas.current,viewport:v,transform:ratio===1?undefined:[ratio,0,0,ratio,0,0]});return task.promise.then(()=>{if(!cancelled&&stage.current&&scrollEdge.current){stage.current.scrollTop=scrollEdge.current==='bottom'?stage.current.scrollHeight:0;scrollEdge.current=null;}});}).catch(e=>{if(!cancelled)setError(e.message);});return()=>{cancelled=true;task?.cancel();};
  },[pdf,sourcePage,zoom,rotation,full]);
  useLayoutEffect(()=>{if(!pdf||!stage.current)return;let cancelled=false;const view=stage.current;void pdf.getPage(drawingPageOrder(current.current.content,pdf.numPages)[0]).then(p=>{if(!cancelled){const v=p.getViewport({scale:1});setZoom(Math.min(1.5,Math.max(.1,(view.clientWidth-(window.matchMedia(phoneQuery).matches?16:40))/v.width)));}});return()=>{cancelled=true;};},[pdf]);
  useLayoutEffect(()=>{
    const anchor=zoomAnchor.current,view=stage.current,sheet=view?.querySelector('.drawing-sheet');
    if(!anchor||!view||!sheet||!viewport||anchor.page!==sourcePage||anchor.zoom!==viewport.scale)return;
    const box=sheet.getBoundingClientRect(),bounds=view.getBoundingClientRect();
    view.scrollLeft+=box.left+anchor.x*viewport.width-bounds.left-view.clientLeft-anchor.offsetX;
    view.scrollTop+=box.top+anchor.y*viewport.height-bounds.top-view.clientTop-anchor.offsetY;
    zoomAnchor.current=null;
  },[viewport,sourcePage]);
  useEffect(()=>()=>{void pdf?.loadingTask.destroy().catch(()=>{});},[pdf]);
  const open=async(r:DrawingRecord,bytes?:Uint8Array)=>{
    if(dirty.current||saving.current){await flush();if(dirty.current||saving.current){setError('Wait for saving to finish, or recover your unsaved markups before switching drawings.');return;}}
    const token=++generation.current;setBusy(true);setError('');
    try { const data=bytes??await loadDrawing(r), doc=await openPdf(data),c=validateContent(r.content);if(token!==generation.current){void doc.loadingTask.destroy();return;}drawingPageOrder(c,doc.numPages);if(c.marks.some(m=>m.page>doc.numPages))throw new Error('A markup references a missing PDF page.');const previous=pdf;setPdf(doc);if(previous)void previous.loadingTask.destroy();source.current=data;recordRef.current=r;current.current={content:c,title:r.title};dirty.current=false;blocked.current=false;setRecord(r);setTitle(r.title);setContent(c);setPage(1);setRotation(0);const first=await doc.getPage(drawingPageOrder(c,doc.numPages)[0]),v=first.getViewport({scale:1});setZoom(Math.min(1.5,Math.max(.2,((stage.current?.clientWidth||850)-40)/v.width)));history.current=[];future.current=[];setHistoryTick(x=>x+1);setDraft([]);setSelected('');setReference([]);setFiles([]);scrollEdge.current='top';reportSave('All drawing changes saved');
      const local=localStorage.getItem('jgc-drawing-recovery-'+r.id);
      if(local){const recovered=JSON.parse(local);if(window.confirm('Unsaved markups from an interrupted session were found. Restore them?')){const restored=validateContent(recovered.content);drawingPageOrder(restored,doc.numPages);current.current={content:restored,title:recovered.title};setContent(restored);setTitle(recovered.title);dirty.current=true;if(recovered.baseRevision!==r.revision){blocked.current=true;reportSave('Not saved');setError('The shared drawing changed after this recovery draft. Recover unsaved markups before reloading the shared drawing.');}else{reportSave('Unsaved drawing changes');timer.current=setTimeout(()=>void flush(),600);}}} }
    catch(e){setError(e instanceof Error?e.message:'Could not open PDF.');}finally{if(token===generation.current)setBusy(false);}
  };
  const upload=async(file?:File)=>{if(!file)return;if(dirty.current||saving.current){setError('Save the current drawing before uploading another.');return;}uploading.current=true;setBusy(true);setError('');try{if(file.size>DRAWING_MAX_BYTES)throw new Error(`Choose a PDF no larger than ${DRAWING_MAX_MB} MB.`);const data=new Uint8Array(await file.arrayBuffer());const test=await openPdf(data);await test.loadingTask.destroy();setUploadProgress(0);const result=await addDrawing(job.id,file,setUploadProgress);setRecords(items=>[result.record,...items]);await open(result.record,result.bytes);}catch(e){setError(e instanceof Error?e.message:'Upload failed. Refresh the register to check for an incomplete upload before retrying.');}finally{uploading.current=false;setBusy(false);setUploadProgress(null);}};
  const setRemoved=async(removed:boolean)=>{
    if(!record||busy||blocked.current)return;if(removed&&!window.confirm(`Remove "${title}" from this job's drawing list? You can restore it using Show removed drawings.`))return;
    await flush();if(dirty.current||saving.current){setError('Wait for drawing changes to save before changing the drawing list.');return;}
    change({...current.current.content,archived:removed});await flush();if(dirty.current||saving.current)return;
    if(removed){if(document.fullscreenElement)await document.exitFullscreen();setFull('none');setPdf(null);setRecord(null);recordRef.current=null;source.current=null;setSelected('');setDraft([]);}
  };
  const point=(event:{clientX:number;clientY:number},allowSnap=true):Point=>{const box=canvas.current!.getBoundingClientRect();const [x,y]=viewport!.convertToPdfPoint((event.clientX-box.left)*viewport!.width/box.width,(event.clientY-box.top)*viewport!.height/box.height);const raw={x,y},found=allowSnap&&snap&&tool!=='pen'?snapPoint(raw,lines,8/zoom):{point:raw,snapped:false};setSnapAt(found.snapped?found.point:null);return found.point;};
  const append=(kind:Mark['kind'],points:Point[])=>{if(blocked.current)return;const mark:Mark={id:crypto.randomUUID(),page:sourcePage,kind,points,color:kind==='stamp'?'#b31a1f':color,text:'',...(kind==='stamp'?{stamp:{...stamp}}:{}),...(isMeasurement(kind)&&current.current.content.scales[String(sourcePage)]?{calibration:{unit:current.current.content.scales[String(sourcePage)].unit,unitsPerPoint:current.current.content.scales[String(sourcePage)].unitsPerPoint}}:{}),...(kind==='distance'?{dimensionOffset:0}:{}),author:actor,createdAt:new Date().toISOString(),layer,rotation:viewport?.rotation??0};change({...current.current.content,marks:[...current.current.content.marks,mark]});setSelected(mark.id);setDraft([]);if(['callout','text','stamp'].includes(kind))setTool('select');};
  const down=(event:ReactPointerEvent<SVGSVGElement>)=>{if(!viewport||busy||blocked.current||event.button!==0)return;if(tool==='select'){setSelected('');return;}event.preventDefault();if(tool==='hand'&&event.pointerType==='touch')return;if(tool==='hand'&&stage.current){pan.current={x:event.clientX,y:event.clientY,left:stage.current.scrollLeft,top:stage.current.scrollTop};event.currentTarget.setPointerCapture(event.pointerId);return;}const p=point(event);if(tool==='distance'||tool==='calibrate'){if(measureStart.current){if(Math.hypot(p.x-measureStart.current.x,p.y-measureStart.current.y)<.5)return;if(tool==='calibrate'){setReference([measureStart.current,p]);setDraft([]);setShowNotes(true);}else append('distance',[measureStart.current,p]);measureStart.current=null;}else{measureStart.current=p;setDraft([p]);if(tool==='calibrate')setReference([]);}return;}if(tool==='area'||tool==='perimeter'){setDraft(points=>[...points,p]);return;}if(tool==='text'||tool==='stamp'){if(tool==='stamp'&&(!stamp.date||!stamp.reviewer.trim())){setError('Enter the reviewer and review date before placing a stamp.');return;}append(tool,[p]);return;}event.currentTarget.setPointerCapture(event.pointerId);gesture.current=[p];setDraft([p]);};
  const move=(event:ReactPointerEvent<SVGSVGElement>)=>{
    if(stampDrag.current&&viewport){const drag=stampDrag.current,p=point(event,false),dx=p.x-drag.start.x,dy=p.y-drag.start.y;let next=drag.mark;if(Math.hypot(dx,dy)<1)return;if(drag.kind==='move')next={...next,points:next.points.map(p=>({x:p.x+dx,y:p.y+dy}))};else{const angle=(next.rotation??0)*Math.PI/180,across=dx*Math.cos(angle)+dy*Math.sin(angle),down=dx*Math.sin(angle)-dy*Math.cos(angle);next={...next,stamp:{...next.stamp!,width:Math.max(100,Math.min(600,next.stamp!.width+(across+down*350/222)/2))}};}drag.latest=next;setMarkPreview(next);return;}
    if(dimensionDrag.current&&viewport){const p=point(event,false),d=dimensionGeometry(dimensionDrag.current);const value={id:dimensionDrag.current.id,offset:(p.x-d.a.x)*d.normal.x+(p.y-d.a.y)*d.normal.y};dimensionLatest.current=value;setDimensionPreview(value);return;}if(['distance','calibrate'].includes(tool)&&measureStart.current&&viewport){setDraft([measureStart.current,point(event)]);return;}if(pan.current&&stage.current){stage.current.scrollLeft=pan.current.left-event.clientX+pan.current.x;stage.current.scrollTop=pan.current.top-event.clientY+pan.current.y;return;}if(!gesture.current||!viewport)return;const p=point(event),first=gesture.current[0];gesture.current=tool==='pen'?[...gesture.current,p]:[first,p];setDraft(gesture.current);
  };
  const up=()=>{if(stampDrag.current){const next=stampDrag.current.latest;stampDrag.current=null;setMarkPreview(null);if(next)patchMark(next.id,{points:next.points,stamp:next.stamp});return;}if(dimensionDrag.current){const id=dimensionDrag.current.id;dimensionDrag.current=null;const value=dimensionLatest.current;dimensionLatest.current=null;if(value)change({...current.current.content,marks:current.current.content.marks.map(m=>m.id===id?{...m,dimensionOffset:value.offset}:m)});setDimensionPreview(null);return;}pan.current=null;if(['area','perimeter','distance','calibrate'].includes(tool))return;const points=gesture.current;gesture.current=null;if(!points||points.length<2){setDraft([]);return;}if(tool==='calibrate'){setReference(points);setShowNotes(true);setDraft([]);}else if(['line','rectangle','highlight','distance','pen','callout'].includes(tool))append(tool as Mark['kind'],points);};
  const finish=()=>{if((tool==='area'&&draft.length<3)||(tool==='perimeter'&&draft.length<2))return;append(tool as Mark['kind'],draft);};
  const undo=(redo=false)=>{const from=redo?future.current:history.current,to=redo?history.current:future.current,next=from.pop();if(!next||blocked.current)return;to.push(current.current.content);current.current={...current.current,content:next};setContent(next);dirty.current=true;stash();setHistoryTick(x=>x+1);clearTimeout(timer.current);timer.current=setTimeout(()=>void flush(),600);reportSave('Unsaved drawing changes');};
  const scale=content.scales[String(sourcePage)],marks=content.marks.filter(m=>m.page===sourcePage),selectedMark=content.marks.find(m=>m.id===selected);
  const transform=(p:Point)=>viewport?viewport.convertToViewportPoint(p.x,p.y):[0,0];
  const startStampDrag=(event:ReactPointerEvent<SVGElement>,mark:Mark,kind:'move'|'resize')=>{if(busy||blocked.current||tool==='hand'||event.button!==0)return;event.preventDefault();event.stopPropagation();setSelected(mark.id);setTool('select');stampDrag.current={kind,mark,start:point(event,false),latest:null};event.currentTarget.ownerSVGElement?.setPointerCapture(event.pointerId);};
  const shape=(m:Mark,preview=false)=>{
    if(markPreview?.id===m.id)m=markPreview;
    if(dimensionPreview?.id===m.id)m={...m,dimensionOffset:dimensionPreview.offset};const dimension=m.kind==='distance'&&m.points.length===2?dimensionGeometry(m):null;
    const pts=m.points.map(transform),coords=pts.map(p=>p.join(',')).join(' '),label=isMeasurement(m.kind)?measurement(m,scale):m.kind==='text'?m.text:'';
    const angle=(m.rotation??viewport?.rotation??0)*Math.PI/180,p=m.points[0],q=transform({x:p.x+Math.cos(angle),y:p.y+Math.sin(angle)}),screenAngle=Math.atan2(q[1]-pts[0][1],q[0]-pts[0][0])*180/Math.PI;
    const box=pts[1]??pts[0],comment=commentLines(m.text),arrow=pts[1]?Math.atan2(pts[1][1]-pts[0][1],pts[1][0]-pts[0][0]):0;
    const arrowPoints=[-.45,.45].map(offset=>`${pts[0][0]+9*zoom*Math.cos(arrow+offset)},${pts[0][1]+9*zoom*Math.sin(arrow+offset)}`).join(' ');
    const editing=!preview&&selected===m.id,commentHeight=Math.max(38,comment.length*12+14),commentOrigin=m.kind==='callout'?box:pts[0];
    return <g key={m.id} className={editing?'drawing-mark selected':'drawing-mark'} style={{color:m.color,strokeWidth:1.5*zoom}} onPointerDown={event=>{if(preview||busy||blocked.current||tool==='hand'||event.button!==0)return;if(m.kind==='stamp'){startStampDrag(event,m,'move');return;}if(dimension&&['select','distance'].includes(tool)){event.stopPropagation();setSelected(m.id);dimensionDrag.current=m;dimensionLatest.current=null;setDimensionPreview(null);event.currentTarget.ownerSVGElement?.setPointerCapture(event.pointerId);return;}if(tool==='select'||['text','callout'].includes(m.kind)){event.stopPropagation();setSelected(m.id);setTool('select');}}} role={!preview?(['stamp','text','callout'].includes(m.kind)?'group':'button'):undefined} tabIndex={!preview&&tool==='select'?0:undefined} aria-label={!preview?`${m.kind}: ${label||m.text||m.layer}`:undefined} onKeyDown={event=>{if(event.key==='Enter'){event.preventDefault();setSelected(m.id);setTool('select');}if(editing&&isMeasurement(m.kind)&&['Delete','Backspace'].includes(event.key)){event.preventDefault();removeMark(m.id);}}}>
      {dimension?<g className="drawing-dimension">
        <line x1={pts[0][0]} y1={pts[0][1]} x2={transform(dimension.start)[0]} y2={transform(dimension.start)[1]} strokeWidth={.75*zoom}/><line x1={pts[1][0]} y1={pts[1][1]} x2={transform(dimension.end)[0]} y2={transform(dimension.end)[1]} strokeWidth={.75*zoom}/>
        <line className="drawing-dimension-line" x1={transform(dimension.start)[0]} y1={transform(dimension.start)[1]} x2={transform(dimension.end)[0]} y2={transform(dimension.end)[1]}/>
        <line className="drawing-dimension-hit" x1={transform(dimension.start)[0]} y1={transform(dimension.start)[1]} x2={transform(dimension.end)[0]} y2={transform(dimension.end)[1]}/>
        {[dimension.start,dimension.end].map((p,i)=>{const a=transform({x:p.x-dimension.normal.x*4,y:p.y-dimension.normal.y*4}),b=transform({x:p.x+dimension.normal.x*4,y:p.y+dimension.normal.y*4});return <line key={i} x1={a[0]} y1={a[1]} x2={b[0]} y2={b[1]}/>;})}
        {(()=>{const a=transform(dimension.start),b=transform(dimension.end),mid=transform(dimension.middle);let rotation=Math.atan2(b[1]-a[1],b[0]-a[0])*180/Math.PI;if(Math.abs(rotation)>90)rotation+=180;return <text className="drawing-dimension-label" transform={`translate(${mid[0]} ${mid[1]}) rotate(${rotation})`} textAnchor="middle" y={-4*zoom} fontSize={10*zoom}>{label}</text>;})()}
      </g>:m.kind==='stamp'&&m.stamp?<g className="drawing-stamp" transform={`translate(${pts[0][0]} ${pts[0][1]}) rotate(${screenAngle}) scale(${m.stamp.width*zoom/350})`}><ReviewStampGraphic stamp={m.stamp} onStatusChange={!preview&&!busy&&!blocked.current&&tool!=='hand'?status=>{setSelected(m.id);setTool('select');patchMark(m.id,{stamp:{...m.stamp!,status}});}:undefined}/>{editing&&<><rect className="drawing-stamp-frame" width="350" height="222" fill="none"/><rect className="drawing-stamp-resize" aria-label="Resize stamp" role="button" tabIndex={0} x="337" y="209" width="26" height="26" onPointerDown={e=>startStampDrag(e,m,'resize')} onKeyDown={e=>{if(['ArrowLeft','ArrowDown','ArrowRight','ArrowUp'].includes(e.key)){e.preventDefault();e.stopPropagation();patchMark(m.id,{stamp:{...m.stamp!,width:Math.max(100,Math.min(600,m.stamp!.width+(['ArrowRight','ArrowUp'].includes(e.key)?10:-10)))}});}}}/></>}</g>
      :['callout','text'].includes(m.kind)?<>{m.kind==='callout'&&<><polyline points={coords}/><polyline points={`${arrowPoints.split(' ')[0]} ${pts[0].join(',')} ${arrowPoints.split(' ')[1]}`}/></>}<g className={m.kind==='callout'?'drawing-callout':'drawing-text-comment'} transform={`translate(${commentOrigin[0]} ${commentOrigin[1]}) rotate(${screenAngle}) scale(${zoom})`}><rect width="185" height={commentHeight} fill="white"/><text className={editing?'drawing-comment-display is-editing':'drawing-comment-display'} x="7" y="16" fontSize="10">{comment.map((line,i)=><tspan key={i} x="7" dy={i?12:0}>{line}</tspan>)}</text>{editing&&<foreignObject width="185" height={commentHeight}><textarea ref={commentInput} className="drawing-inline-comment" aria-label="Edit drawing comment" placeholder="Type your comment…" value={m.text} maxLength={2000} disabled={busy||blocked.current} style={{color:m.color,borderColor:m.color}} onPointerDown={e=>e.stopPropagation()} onKeyDown={e=>e.stopPropagation()} onChange={e=>patchMark(m.id,{text:e.target.value})}/></foreignObject>}</g></>
      :['rectangle','highlight'].includes(m.kind)&&pts[1]?<rect fill={m.kind==='highlight'?'currentColor':'none'} fillOpacity={m.kind==='highlight'?.25:0} stroke={m.kind==='highlight'?'none':undefined} x={Math.min(pts[0][0],pts[1][0])} y={Math.min(pts[0][1],pts[1][1])} width={Math.abs(pts[1][0]-pts[0][0])} height={Math.abs(pts[1][1]-pts[0][1])}/>
      :['area','perimeter'].includes(m.kind)?<polygon points={coords}/>:m.kind!=='text'?<polyline points={coords}/>:null}
      {label&&m.kind!=='distance'&&m.kind!=='text'&&<text transform={`rotate(${screenAngle},${pts[0][0]},${pts[0][1]})`} x={pts[0][0]} y={pts[0][1]} fontSize={10*zoom}>{label}</text>}
      {editing&&(isMeasurement(m.kind)||m.kind==='stamp')&&(()=>{const anchor=m.kind==='stamp'&&m.stamp?transform({x:p.x+m.stamp.width*Math.cos(angle),y:p.y+m.stamp.width*Math.sin(angle)}):dimension?transform(dimension.middle):pts[0];const title=m.kind==='stamp'?'Delete stamp':'Delete measurement';return <foreignObject x={m.kind==='stamp'?Math.min(viewport!.width-26,Math.max(2,anchor[0]-12)):anchor[0]+Math.min(100,label.length*3*zoom)+8} y={m.kind==='stamp'?Math.min(viewport!.height-26,Math.max(2,anchor[1]-12)):anchor[1]-28} width="24" height="24"><button type="button" className="drawing-delete-markup" aria-label={title} title={title} disabled={busy||blocked.current} onPointerDown={e=>e.stopPropagation()} onKeyDown={e=>e.stopPropagation()} onClick={e=>{e.stopPropagation();removeMark(m.id);}}>×</button></foreignObject>;})()}
    </g>;
  };
  const referenceGraphic=(points:Point[],label:string,pending=false)=>{if(points.length!==2)return null;const a=transform(points[0]),b=transform(points[1]),mid=[(a[0]+b[0])/2,(a[1]+b[1])/2];return <g className="drawing-scale-reference" aria-label={label} role="img" style={{stroke:'#216aa7',color:'#216aa7',strokeWidth:1.5*zoom}}><line x1={a[0]} y1={a[1]} x2={b[0]} y2={b[1]} strokeDasharray={pending?'5 3':undefined}/>{[a,b].map((p,i)=><circle key={i} cx={p[0]} cy={p[1]} r={3*zoom} fill="white"/>)}<text x={mid[0]} y={mid[1]-7*zoom} textAnchor="middle" fontSize={10*zoom}>{label}</text></g>;};
  const togglePanel=(panel:'pages'|'markups')=>{const phone=window.matchMedia(phoneQuery).matches;if(panel==='pages'){setShowPages(v=>!v);if(phone)setShowNotes(false);}else{setShowNotes(v=>!v);if(phone)setShowPages(false);}};
  const fit=async()=>{if(!pdf||!stage.current)return;const p=await pdf.getPage(sourcePage),v=p.getViewport({scale:1,rotation:(p.rotate+rotation)%360});setZoom(Math.min(4,Math.max(.1,(stage.current.clientWidth-40)/v.width)));};
  const exportPdf=async(pages?:number[])=>{if(!source.current||!record)return;setBusy(true);setError('');try{await flush();if(dirty.current)throw new Error('Save your markups before exporting. Use Recover markups if saving is blocked.');const {markedDrawingPdf}=await import('../lib/drawing-pdf');const bytes=await markedDrawingPdf(source.current,current.current.content,pages);download(bytes,`${title.replace(/[^a-z0-9 _-]/gi,'').trim()||'Drawing'}${pages?.length===1?` - Page ${order.indexOf(pages[0])+1}`:pages?' - Selected pages':''} - JGC marked.pdf`,'application/pdf');}catch(e){setError(e instanceof Error?e.message:'Could not export drawing.');}finally{setBusy(false);}};
  const chooseMode=(value:string)=>{if(value==='organize'){organizerMode.current=mode;setSelectedPages([sourcePage]);selectionAnchor.current=sourcePage;setMultiSelect(false);}measureStart.current=null;setMode(value);setReference([]);setTool(value==='measure'?(scale?'distance':'calibrate'):value==='stamps'?'stamp':value==='comments'?'callout':'select');setDraft([]);setError('');setShowNotes(value!=='organize'&&value!=='navigate');if(window.matchMedia(phoneQuery).matches)setShowPages(false);};
  const closeOrganizer=()=>{setMode(organizerMode.current==='organize'?'navigate':organizerMode.current);setTool('select');setPageDrop(null);dragPage.current=null;};
  useEffect(()=>{
    if(mode!=='organize')return;
    const previousOverflow=document.body.style.overflow,previousFocus=organizerTrigger.current??document.activeElement as HTMLElement|null;
    const surface=organizer.current;document.body.style.overflow='hidden';surface?.querySelector<HTMLButtonElement>('button')?.focus();
    const key=(event:KeyboardEvent)=>{
      if(event.key==='Escape'){event.preventDefault();event.stopPropagation();closeOrganizer();return;}
      if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='a'&&!(event.target instanceof HTMLInputElement)){event.preventDefault();setSelectedPages(organizerOrder.current);return;}
      if(event.key==='Tab'){
        const targets=Array.from(organizer.current?.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),[tabindex="0"]')??[]).filter(e=>e.getClientRects().length);
        const first=targets[0],last=targets.at(-1);
        if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus();}
        else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus();}
      }
    };
    surface?.addEventListener('keydown',key);
    return()=>{document.body.style.overflow=previousOverflow;surface?.removeEventListener('keydown',key);if(previousFocus?.isConnected)previousFocus.focus({preventScroll:true});};
  },[mode]);
  const selectOrganizerPage=(n:number,event:ReactMouseEvent)=>{
    if(event.shiftKey&&selectionAnchor.current!==null){const a=order.indexOf(selectionAnchor.current),b=order.indexOf(n),range=order.slice(Math.min(a,b),Math.max(a,b)+1);setSelectedPages(event.ctrlKey||event.metaKey?Array.from(new Set([...selectedPages,...range])):range);}
    else{setSelectedPages(event.ctrlKey||event.metaKey||multiSelect?selectedPages.includes(n)?selectedPages.filter(page=>page!==n):[...selectedPages,n]:[n]);selectionAnchor.current=n;}
  };
  const movePages=(pages:number[],target:number|null,after=false)=>{
    if(blocked.current||busy)return;
    const next=reorderDrawingPages(order,pages,target,after);
    if(next.join(',')===order.join(','))return;
    change({...current.current.content,pageOrder:next});setPage(next.indexOf(sourcePage)+1);
  };
  const combine=async()=>{
    if(!source.current||!record||!files.length)return;await flush();if(dirty.current||saving.current){setError('Wait for shared saving to finish before combining PDFs.');return;}
    uploading.current=true;setBusy(true);setError('');
    try{
      if(files.reduce((sum,file)=>sum+file.size,source.current.length)>2*DRAWING_MAX_BYTES)throw new Error(`Choose a smaller set of files to combine (${DRAWING_MAX_MB*2} MB total input limit).`);
      const additional:Uint8Array[]=[];for(const file of files)additional.push(new Uint8Array(await file.arrayBuffer()));
      const {combinedDrawingPdf}=await import('../lib/drawing-pdf'),result=await combinedDrawingPdf(source.current,current.current.content,additional);
      const file=new File([result.bytes.slice().buffer as ArrayBuffer],`${title||'Drawing'} - Combined.pdf`,{type:'application/pdf'}),created=await addDrawing(job.id,file,setUploadProgress);
      setRecords(items=>[created.record,...items]);await open(created.record,created.bytes);change(result.content);await flush();setFiles([]);
    }catch(e){setError(e instanceof Error?e.message:'Could not combine PDFs. Refresh the register before retrying.');}finally{uploading.current=false;setBusy(false);setUploadProgress(null);}
  };
  useEffect(()=>{
    const view=stage.current;if(!view||!pdf)return;
    const boundary=(delta:number)=>delta>0?view.scrollTop+view.clientHeight>=view.scrollHeight-2:view.scrollTop<=2;
    const advance=(delta:number)=>{if(Date.now()<pageLock.current||busy||!delta||!boundary(delta))return false;const next=page+(delta>0?1:-1);if(next<1||next>pdf.numPages)return false;navigate(next,delta>0?'top':'bottom');return true;};
    const wheel=(event:WheelEvent)=>{
      if(event.ctrlKey||event.metaKey){
        event.preventDefault();wheelDelta.current=0;wheelTime.current=0;
        const sheet=view.querySelector('.drawing-sheet');if(!sheet||busy||!event.deltaY)return;
        const delta=event.deltaY*(event.deltaMode===1?16:event.deltaMode===2?view.clientHeight:1);
        const next=Math.min(4,Math.max(.1,zoomValue.current*Math.exp(-Math.max(-240,Math.min(240,delta))*.002)));
        if(next===zoomValue.current)return;
        const box=sheet.getBoundingClientRect(),bounds=view.getBoundingClientRect();if(!box.width||!box.height)return;
        zoomAnchor.current={x:Math.max(0,Math.min(1,(event.clientX-box.left)/box.width)),y:Math.max(0,Math.min(1,(event.clientY-box.top)/box.height)),offsetX:event.clientX-bounds.left-view.clientLeft,offsetY:event.clientY-bounds.top-view.clientTop,page:sourcePage,zoom:next};
        zoomValue.current=next;setZoom(next);return;
      }
      if(Math.abs(event.deltaX)>Math.abs(event.deltaY))return;if(Date.now()-wheelTime.current>250)wheelDelta.current=0;wheelTime.current=Date.now();wheelDelta.current+=event.deltaY;
      if(boundary(event.deltaY)&&Math.abs(wheelDelta.current)>35&&advance(event.deltaY)){event.preventDefault();wheelDelta.current=0;}};
    const scroll=()=>{if(Date.now()-wheelTime.current<250&&Math.abs(wheelDelta.current)>35)advance(wheelDelta.current);};
    let finger:{x:number;y:number;left:number;top:number;edgeLeft:boolean;edgeRight:boolean;at:number}|null=null;
    let pinch:{distance:number;zoom:number;x:number;y:number}|null=null,pinched=false;
    const distance=(touches:TouchList)=>Math.hypot(touches[1].clientX-touches[0].clientX,touches[1].clientY-touches[0].clientY);
    const center=(touches:TouchList)=>({x:(touches[0].clientX+touches[1].clientX)/2,y:(touches[0].clientY+touches[1].clientY)/2});
    const start=(event:TouchEvent)=>{
      if(!['select','hand'].includes(tool)||busy||(event.target as Element).closest('button,input,textarea,select'))return;
      if(event.touches.length===2){
        event.preventDefault();finger=null;pinched=true;touchStart.current=null;
        pan.current=null;stampDrag.current=null;dimensionDrag.current=null;setMarkPreview(null);setDimensionPreview(null);
        const sheet=view.querySelector('.drawing-sheet'),middle=center(event.touches),box=sheet?.getBoundingClientRect();
        if(box&&box.width&&box.height)pinch={distance:Math.max(1,distance(event.touches)),zoom:zoomValue.current,x:Math.max(0,Math.min(1,(middle.x-box.left)/box.width)),y:Math.max(0,Math.min(1,(middle.y-box.top)/box.height))};
        return;
      }
      if(event.touches.length!==1||pinched||(event.target as Element).closest('.drawing-mark'))return;
      const t=event.touches[0];finger={x:t.clientX,y:t.clientY,left:view.scrollLeft,top:view.scrollTop,edgeLeft:view.scrollLeft<=2,edgeRight:view.scrollLeft+view.clientWidth>=view.scrollWidth-2,at:Date.now()};
    };
    const touchMove=(event:TouchEvent)=>{
      if(pinch&&event.touches.length===2){
        event.preventDefault();const middle=center(event.touches),bounds=view.getBoundingClientRect(),next=Math.min(4,Math.max(.1,pinch.zoom*distance(event.touches)/pinch.distance));
        zoomAnchor.current={x:pinch.x,y:pinch.y,offsetX:middle.x-bounds.left-view.clientLeft,offsetY:middle.y-bounds.top-view.clientTop,page:sourcePage,zoom:next};zoomValue.current=next;setZoom(next);return;
      }
      if(pinched){event.preventDefault();return;}
      if(finger&&event.touches.length===1){event.preventDefault();const t=event.touches[0];view.scrollLeft=finger.left+finger.x-t.clientX;view.scrollTop=finger.top+finger.y-t.clientY;}
    };
    const end=(event:TouchEvent)=>{
      if(pinched){pinch=null;finger=null;if(!event.touches.length)pinched=false;return;}
      if(!finger)return;const first=finger,last=event.changedTouches[0];finger=null;if(!last)return;
      const dx=first.x-last.clientX,dy=first.y-last.clientY;
      if(Math.abs(dx)>60&&Math.abs(dx)>Math.abs(dy)*1.4&&Date.now()-first.at<1200&&Date.now()>=pageLock.current){
        if((dx>0&&first.edgeRight)||(dx<0&&first.edgeLeft))navigate(page+(dx>0?1:-1));
      }else if(Math.abs(dy)>60&&Math.abs(dy)>Math.abs(dx)*1.4)advance(dy);
    };
    const cancel=()=>{finger=null;pinch=null;pinched=false;};
    view.addEventListener('wheel',wheel,{passive:false});view.addEventListener('scroll',scroll);view.addEventListener('touchstart',start,{passive:false});view.addEventListener('touchmove',touchMove,{passive:false});view.addEventListener('touchend',end);view.addEventListener('touchcancel',cancel);
    return()=>{view.removeEventListener('wheel',wheel);view.removeEventListener('scroll',scroll);view.removeEventListener('touchstart',start);view.removeEventListener('touchmove',touchMove);view.removeEventListener('touchend',end);view.removeEventListener('touchcancel',cancel);};
  },[pdf,page,sourcePage,busy,full,tool]);
  const scaleDescription=scale?`${scale.knownLength} ${scale.unit==='ft-in'?'ft':scale.unit} reference saved`:'Calibrate each page before measuring.';
  const tools:Record<string,[string,string][]>={
    navigate:[],measure:[['calibrate',scale?'Replace scale':'Set scale'],['distance','Distance'],['perimeter','Perimeter'],['area','Area']],
    stamps:[['stamp','Shop drawing stamp']],comments:[['callout','Arrow comment'],['text','Text']],edit:[['pen','Pen'],['line','Line'],['rectangle','Box'],['highlight','Highlight'],['text','Text']],organize:[],
  };
  const organizerContent=pdf&&mode==='organize'?<div ref={organizer} className="drawing-organizer-full" role="dialog" aria-modal="true" aria-labelledby={`${panelId}-organizer-title`}>
    <header className="drawing-organizer-header"><div><h2 id={`${panelId}-organizer-title`}>Organize pages</h2><p>{title} · {order.length} pages · {selectedPages.length} selected</p></div><button type="button" className="button secondary compact" onClick={closeOrganizer}>Close organizer</button></header>
    <div className="drawing-organizer-actions"><p>Ctrl-click selects individual pages. Shift-click selects a range. Drag the selection before or after a page.</p><label><input type="checkbox" checked={multiSelect} onChange={e=>setMultiSelect(e.target.checked)}/>Select multiple</label><button type="button" className="button secondary compact" onClick={()=>setSelectedPages(order)}>Select all pages</button><button type="button" className="button secondary compact" onClick={()=>setSelectedPages([])}>Clear selection</button><button type="button" className="button secondary compact" disabled={!history.current.length||busy||blocked.current} onClick={()=>undo()}>Undo</button><button type="button" className="button primary compact" disabled={!selectedPages.length||busy||blocked.current} onClick={()=>void exportPdf(selectedPages)}>Download selected pages</button><span role="status">{saveStatus}</span></div>
    {error&&<div className="drawing-organizer-error" role="alert">{error}</div>}
    <div className="drawing-organizer-scroll"><div className="drawing-page-cards" role="list" aria-label="Page order">{order.map((n,i)=><div key={n} role="listitem" tabIndex={0} aria-label={`Source page ${n}, position ${i+1} of ${order.length}`} className={`${selectedPages.includes(n)?'selected':''} ${pageDrop?.page===n?(pageDrop.after?'drop-after':'drop-before'):''}`} draggable={!busy&&!blocked.current} onKeyDown={e=>{if(e.altKey&&['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();const selected=selectedPages.includes(n)?selectedPages:[n],positions=selected.map(p=>order.indexOf(p)),target=e.key==='ArrowRight'?order[Math.max(...positions)+1]:order[Math.min(...positions)-1];if(target)movePages(selected,target,e.key==='ArrowRight');}}} onDragStart={e=>{const moving=selectedPages.includes(n)?order.filter(p=>selectedPages.includes(p)):[n];setSelectedPages(moving);dragPage.current=moving;e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',moving.join(','));}} onDragOver={e=>{if(dragPage.current){e.preventDefault();e.dataTransfer.dropEffect='move';const box=e.currentTarget.getBoundingClientRect();setPageDrop({page:n,after:e.clientX>=box.x+box.width/2});}}} onDrop={e=>{e.preventDefault();const box=e.currentTarget.getBoundingClientRect();if(dragPage.current)movePages(dragPage.current,n,e.clientX>=box.x+box.width/2);dragPage.current=null;setPageDrop(null);}} onDragEnd={()=>{dragPage.current=null;setPageDrop(null);}}>
      <Thumb pdf={pdf} number={n} label={i+1} selected={selectedPages.includes(n)} selection onClick={e=>selectOrganizerPage(n,e)}/><small>Source page {n}</small>
    </div>)}</div><div className={`drawing-organizer-end ${pageDrop?.page===null?'drop-target':''}`} onDragOver={e=>{if(dragPage.current){e.preventDefault();setPageDrop({page:null,after:true});}}} onDrop={e=>{e.preventDefault();if(dragPage.current)movePages(dragPage.current,null);dragPage.current=null;setPageDrop(null);}}>Drop selected pages here to move them to the end</div></div>
    <footer className="drawing-organizer-footer"><small>Page order saves automatically. Markups and scales stay with their source page. Keyboard: Alt + left/right moves selected pages.</small><div className="drawing-combine"><label>Append PDFs to this drawing<input aria-label="PDFs to combine" type="file" accept="application/pdf,.pdf" multiple disabled={busy||blocked.current} onChange={e=>setFiles(Array.from(e.target.files??[]))}/></label><span>{files.map(file=>file.name).join(' · ')}</span><button className="button primary compact" disabled={!files.length||busy||blocked.current} onClick={()=>void combine()}><DrawingIcon name="combine"/>Create combined PDF</button><small>Creates a new shared drawing. Original PDFs and markups stay intact.</small></div></footer>
  </div>:null;
  const viewerContent=pdf?(      <div ref={viewer} className={`drawing-viewer ${full!=='none'?'is-fullscreen':''} ${mobileTools?'mobile-tools-open':''}`} aria-label="Drawing viewer">
      {full!=='none'&&<div className="drawing-full-title"><strong>{title}</strong><span>Job {job.jobNumber}</span><button className="drawing-mobile-exit" aria-label="Exit full screen" onClick={()=>void toggleFull()}>Exit</button></div>}
      <div className="drawing-modes" role="toolbar" aria-label="Drawing modes">
        {([['navigate','View'],['measure','Measure'],['stamps','Stamps'],['comments','Comments'],['edit','Edit'],['organize','Organize pages']] as const).map(([key,label])=><button key={key} aria-pressed={mode===key} onClick={event=>{if(key==='organize')organizerTrigger.current=event.currentTarget;chooseMode(key);}}><DrawingIcon name={key}/>{label}</button>)}
        <button className="drawing-full-button" onClick={()=>void toggleFull()}><DrawingIcon name={full==='none'?'fullscreen':'exit'}/>{full==='none'?'Full screen':'Exit full screen'}</button>
      </div>
      <div className="drawing-toolbar" role="toolbar" aria-label="Drawing tools">
        {[['select','Select'],['hand','Hand'],...tools[mode]].map(([key,label])=><button key={key} disabled={busy||blocked.current||(isMeasurement(key)&&!scale)} aria-pressed={tool===key} title={isMeasurement(key)&&!scale?'Set this page’s scale first':label} onClick={()=>{setTool(key);measureStart.current=null;setDraft([]);setReference([]);setError('');if(key==='calibrate'){setKnown('');setInches('');setSelected('');}if(['text','calibrate','stamp','callout'].includes(key))setShowNotes(true);}}><DrawingIcon name={key}/>{label}</button>)}
        {['measure','edit','comments'].includes(mode)&&<button aria-pressed={snap} onClick={()=>{setSnap(v=>!v);setSnapAt(null);}} title="Snap to vector line endpoints and edges"><DrawingIcon name="snap"/>Snap to lines</button>}
        {['edit','comments','measure'].includes(mode)&&<label className="drawing-color">Colour<input type="color" aria-label="Markup colour" value={color} onChange={e=>setColor(e.target.value)}/></label>}
        <select aria-label="Markup layer" value={layer} onChange={e=>setLayer(e.target.value as Mark['layer'])}><option>Review</option><option>As-built</option></select>
        {mode==='measure'&&<label className="drawing-output-unit">Display<select aria-label="Measurement output" value={scale?.displayUnit??(scale?.unit==='ft'?'ft-in':scale?.unit)??outputUnit??unit} onChange={e=>{const displayUnit=e.target.value as MeasurementUnit;setOutputUnit(displayUnit);if(scale)change({...current.current.content,scales:{...current.current.content.scales,[sourcePage]:{...scale,displayUnit}}});}} disabled={busy||blocked.current}><option value="ft">Feet</option><option value="ft-in">Feet &amp; inches</option><option value="in">Inches</option><option value="yd">Yards</option><option value="m">Metres</option><option value="cm">Centimetres</option><option value="mm">Millimetres</option></select></label>}
        <button disabled={!history.current.length||blocked.current||busy} onClick={()=>undo()}><DrawingIcon name="undo"/>Undo</button><button disabled={!future.current.length||blocked.current||busy} onClick={()=>undo(true)}><DrawingIcon name="redo"/>Redo</button>
        <button className="drawing-export" disabled={busy||blocked.current} onClick={()=>void exportPdf()}><DrawingIcon name="download"/>Download marked PDF</button><button disabled={busy||blocked.current} onClick={()=>void exportPdf([sourcePage])}><DrawingIcon name="download"/>Download this page</button>
      </div>
      <div className="drawing-mobile-panels">{full!=='none'&&<button aria-expanded={mobileTools} onClick={()=>setMobileTools(v=>!v)}>Tools</button>}<button aria-expanded={showPages} aria-controls={`${panelId}-pages`} onClick={()=>togglePanel('pages')}>Pages</button><button aria-expanded={showNotes} aria-controls={`${panelId}-markups`} onClick={()=>togglePanel('markups')}>Markups</button><span role="status">{busy?'Working…':saveStatus}</span></div>
      <div className="drawing-viewbar"><button aria-label="Previous page" disabled={page===1||busy} onClick={()=>navigate(page-1,'bottom')}>‹</button><label>Page <input aria-label="Page number" type="number" min={1} max={pdf.numPages} value={page} onChange={e=>{const n=Number(e.target.value);if(Number.isInteger(n)&&n>=1&&n<=pdf.numPages)navigate(n);}}/> of {pdf.numPages}</label><button aria-label="Next page" disabled={page===pdf.numPages||busy} onClick={()=>navigate(page+1)}>›</button><button aria-label="Zoom out" onClick={()=>setZoom(z=>Math.max(.1,z/1.25))}>−</button><span>{Math.round(zoom*100)}%</span><button aria-label="Zoom in" onClick={()=>setZoom(z=>Math.min(4,z*1.25))}>＋</button><button onClick={()=>void fit()}><DrawingIcon name="fit"/>Fit width</button><button onClick={()=>setRotation(r=>(r+90)%360)}><DrawingIcon name="rotate"/>Rotate view</button><span className="drawing-scale-label">{scale?`Calibrated · ${scaleDescription}`:'Page scale not set'}</span></div>
      {snap&&<div className="drawing-snap-hint">{lines.length?'Snapping to drawing line endpoints and edges.':'No vector lines found on this page. Scanned drawings can be measured manually.'}</div>}
      <div className={`drawing-workspace ${showPages?'with-pages':''} ${showNotes?'with-comments':''}`}>
        {showPages&&<aside id={`${panelId}-pages`} className="drawing-thumbnails" aria-label="Page thumbnails"><div className="drawing-mobile-panel-heading"><strong>Pages</strong><button onClick={()=>setShowPages(false)}>Close pages</button></div>{order.map((n,i)=><Thumb key={n} pdf={pdf} number={n} label={i+1} selected={page===i+1} onClick={()=>navigate(i+1)}/>)}</aside>}
        <PanelTab side="pages" expanded={showPages} controls={`${panelId}-pages`} onClick={()=>togglePanel('pages')}/>
        <div ref={stage} className={`drawing-stage ${['select','hand'].includes(tool)?'touch-navigation':''}`} tabIndex={0} aria-label="PDF drawing view"><div className="drawing-sheet" style={viewport?{width:viewport.width,height:viewport.height}:undefined}><canvas ref={canvas}/>{viewport&&<svg aria-label="Drawing markup canvas" viewBox={`0 0 ${viewport.width} ${viewport.height}`} width={viewport.width} height={viewport.height} className={`drawing-overlay tool-${tool}`} onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={()=>{pan.current=null;gesture.current=null;dimensionDrag.current=null;stampDrag.current=null;setMarkPreview(null);setDimensionPreview(null);measureStart.current=null;setDraft([]);}}>{tool!=='calibrate'&&scale?.reference?.length===2&&referenceGraphic(scale.reference,scaleReferenceLabel(scale))}{tool==='calibrate'&&reference.length===2&&referenceGraphic(reference,'Scale reference - enter the known length',true)}{marks.map(m=>shape(m))}{draft.length>0&&shape({id:'preview',page:sourcePage,kind:tool==='calibrate'?'line':tool as Mark['kind'],points:draft,color:tool==='calibrate'?'#216aa7':color,text:'',author:actor,createdAt:'',layer},true)}{snapAt&&<circle className="drawing-snap-point" cx={transform(snapAt)[0]} cy={transform(snapAt)[1]} r="6"/>}</svg>}</div></div>
        <PanelTab side="markups" expanded={showNotes} controls={`${panelId}-markups`} onClick={()=>togglePanel('markups')}/>
        {showNotes&&<aside id={`${panelId}-markups`} className="drawing-comments" aria-label="Drawing comments"><div className="drawing-mobile-panel-heading"><strong>Markups</strong><button onClick={()=>setShowNotes(false)}>Close markups</button></div><h3>Page {page} · {mode==='stamps'?'Review stamp':'Markups'}</h3><p className="drawing-hint">{tool==='select'?'Click a comment to type, or select a stamp to move and resize it.':tool==='area'||tool==='perimeter'?'Click each corner, then Finish.':tool==='text'?'Click the drawing, then type in its comment box.':tool==='stamp'?'Choose your review status, then click the drawing to place the stamp.':tool==='callout'?'Drag from the arrow tip to the comment box, then type directly in the box.':tool==='distance'?'Click the first point, then the second. Drag the dimension line to offset it without changing the endpoints.':tool==='calibrate'?'Click each end of a known dimension, then enter its length below. The blue reference stays on the drawing.':'Drag on the drawing to add a markup.'}</p>
          {['area','perimeter'].includes(tool)&&<div><button className="button primary compact" disabled={draft.length<(tool==='area'?3:2)} onClick={finish}>Finish {tool}</button><button className="button secondary compact" onClick={()=>setDraft([])}>Cancel</button></div>}
          {mode==='stamps'&&<StampFields value={stamp} onChange={setStamp} disabled={busy||blocked.current}/>}
          {mode==='measure'&&<fieldset><legend>Page scale</legend><p>{tool==='calibrate'&&scale?'Replacing this page’s scale. Earlier measurements keep their original scale.':scaleDescription}</p><label>Scale units<select aria-label="Scale units" value={unit} onChange={e=>setUnit(e.target.value as Scale['unit'])}><option value="ft">Feet</option><option value="in">Inches</option><option value="ft-in">Feet &amp; inches</option><option value="m">Metres</option><option value="cm">Centimetres</option><option value="mm">Millimetres</option></select></label><label>{unit==='ft-in'?'Known feet':'Known length'}<input aria-label="Known length" type="number" min="0" step="any" value={known} onChange={e=>setKnown(e.target.value)}/></label>{unit==='ft-in'&&<label>Known inches<input aria-label="Known inches" type="number" min="0" step="any" value={inches} onChange={e=>setInches(e.target.value)}/></label>}<button className="button secondary compact" disabled={busy||reference.length!==2||blocked.current} onClick={()=>{try{const s=calibrate(reference,Number(known)+(unit==='ft-in'?Number(inches)/12:0),unit);s.displayUnit=outputUnit??(scale?(scale.displayUnit??(scale.unit==='ft'?'ft-in':scale.unit)):s.displayUnit);change(replacePageScale(current.current.content,sourcePage,s));setReference([]);setTool('distance');if(window.matchMedia(phoneQuery).matches)setShowNotes(false);setError('');}catch(e){setError((e as Error).message);}}}>Apply page scale</button>{tool==='calibrate'&&scale&&<button className="button secondary compact" onClick={()=>{measureStart.current=null;setReference([]);setDraft([]);setTool('distance');}}>Cancel scale replacement</button>}<small>One active reference per page. Replacing it sets the scale for new measurements. Display units can be changed without recalibrating.</small></fieldset>}
          {selectedMark&&<div className="drawing-selection"><strong>{selectedMark.kind} · {selectedMark.layer}</strong>{selectedMark.kind==='stamp'&&selectedMark.stamp&&<><p>Drag the stamp to move it. Drag its corner to resize; click a review choice on the stamp.</p><StampFields prefix="Selected stamp" value={selectedMark.stamp} disabled={busy||blocked.current} onChange={value=>{if(value.date)patchMark(selectedMark.id,{stamp:value});}}/></>}{['text','callout'].includes(selectedMark.kind)?<p>Click the comment box on the drawing to type.</p>:<label>Comment<textarea aria-label="Edit selected comment" disabled={blocked.current} value={selectedMark.text} maxLength={2000} onChange={e=>patchMark(selectedMark.id,{text:e.target.value})}/></label>}{isMeasurement(selectedMark.kind)&&<p>{measurement(selectedMark,content.scales[String(selectedMark.page)])}</p>}<small>{selectedMark.author} · {new Date(selectedMark.createdAt).toLocaleString()}</small><button className="button secondary compact" disabled={blocked.current} onClick={()=>removeMark(selectedMark.id)}>Remove markup</button></div>}
          <ul>{marks.map(m=><li key={m.id}><button className={m.id===selected?'selected':''} onClick={()=>setSelected(m.id)}><span style={{background:m.color}}/><strong>{m.layer} · {m.kind}</strong><small>{isMeasurement(m.kind)?measurement(m,scale):m.kind==='stamp'?m.stamp?.status:m.text||m.author}</small></button></li>)}</ul>
        </aside>}
      </div><footer className="drawing-footer"><span className="drawing-desktop-help">Ctrl + scroll to zoom · Scroll to the bottom or top to move between pages</span><span className="drawing-phone-help">Swipe left/right for pages · Pinch to zoom · Drag to pan when zoomed</span> · Original PDF preserved · Markups autosave separately · Verify your page scale against a known dimension. <button onClick={()=>source.current&&download(source.current,record?.file_name||'Original.pdf','application/pdf')}>Download original</button></footer>
      </div>):null;
  // Component stays mounted across Job tabs so pending saves finish safely.
  return <section className="job-drawings" hidden={!active} aria-label="Job drawings">
    <header className="drawing-heading"><div><span className="eyebrow">JGC · DRAWING WORKSPACE</span><h2>Drawings</h2><p>Review, measure and record as-built changes for Job {job.jobNumber}. PDFs up to {DRAWING_MAX_MB} MB.</p></div><label className={`button primary ${busy?'disabled':''}`}>＋ Upload PDF<input type="file" accept="application/pdf,.pdf" disabled={busy||blocked.current} onChange={e=>{void upload(e.target.files?.[0]);e.target.value='';}}/></label></header>
    {error&&<div className="drawing-notice" role="alert"><p>{error}</p>{record&&<div><button className="button secondary compact" disabled={busy||saving.current} onClick={()=>{blocked.current=false;void flush();}}>Retry saving</button><button className="button secondary compact" disabled={busy||saving.current} onClick={()=>{if(dirty.current&&!window.confirm('Reload will discard unsaved markups. Download Recover unsaved markups first if you need to keep them. Continue?'))return;localStorage.removeItem('jgc-drawing-recovery-'+recordRef.current?.id);dirty.current=false;blocked.current=false;void listDrawings(job.id).then(rows=>{setRecords(rows);const latest=rows.find(r=>r.id===record.id);if(latest)void open(latest);}).catch(e=>setError(e.message));}}>Reload saved drawing</button><button className="button secondary compact" onClick={()=>download(JSON.stringify({drawingId:record.id,fileName:record.file_name,...current.current.content},null,2),'JGC unsaved markups.json','application/json')}>Recover unsaved markups</button></div>}</div>}
    <div className="drawing-register"><label>Drawing<select aria-label="Select drawing" value={record?.id??''} disabled={busy||saving.current} onChange={e=>{const r=records.find(r=>r.id===e.target.value);if(r)void open(r);}}><option value="">Choose a drawing…</option>{visibleRecords.map(r=><option key={r.id} value={r.id}>{r.title}{r.content.archived?' (removed)':''}</option>)}</select></label><button className="button secondary compact" disabled={busy||saving.current} onClick={()=>{void (async()=>{await flush();if(dirty.current||saving.current)return;setBusy(true);try{const rows=await listDrawings(job.id);setRecords(rows);const latest=rows.find(r=>r.id===record?.id);if(latest)await open(latest);}catch(e){setError((e as Error).message);}finally{setBusy(false);}})();}}>Refresh drawings</button><label className="drawing-removed-filter"><input type="checkbox" checked={showRemoved} onChange={e=>setShowRemoved(e.target.checked)}/>Show removed drawings</label>{record&&<button className="button secondary compact drawing-remove" disabled={busy||blocked.current||saving.current} onClick={()=>void setRemoved(!content.archived)}>{content.archived?'Restore drawing':'Remove drawing'}</button>}<span role="status">{busy?(uploadProgress!==null?`Uploading drawing · ${uploadProgress}%`:'Working…'):saveStatus||`${visibleRecords.length} shared drawing${visibleRecords.length===1?'':'s'}`}</span></div>
    {!pdf?<div className="drawing-empty"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M6 2h8l4 4v16H6zM14 2v5h5M9 12h6M9 16h6"/></svg><h3>{busy?'Opening drawing…':'Your Job drawings, together'}</h3><p>Upload a PDF or choose a saved drawing. The original stays intact; markups are saved separately and included in your marked PDF export.</p></div>:<>
      <div className="drawing-document-title"><input aria-label="Drawing title" value={title} disabled={busy||blocked.current} onChange={e=>{setTitle(e.target.value);current.current={...current.current,title:e.target.value};dirty.current=true;stash();reportSave('Unsaved drawing changes');clearTimeout(timer.current);timer.current=setTimeout(()=>void flush(),600);}}/><span>{record?.file_name} · Shared with JGC admins</span></div>
      {full==='window'?createPortal(viewerContent,document.body):viewerContent}{organizerContent&&createPortal(organizerContent,document.fullscreenElement===viewer.current&&viewer.current?viewer.current:document.body)}
    </>}
  </section>;
}
