import { useEffect, useRef, useState, type PointerEvent as ReactPointerEvent } from 'react';
import { createPortal } from 'react-dom';
import type { PDFDocumentProxy, PageViewport } from 'pdfjs-dist';
import type { Job } from '../lib/estimator-data';
import { calibrate, commentLines, dimensionGeometry, drawingPageOrder, DRAWING_MAX_BYTES, DRAWING_MAX_MB, emptyDrawing, isMeasurement, measurement, validateContent, type DrawingContent, type Mark, type Point, type Scale, type ReviewStamp } from '../lib/drawing-model';
import { addDrawing, listDrawings, loadDrawing, saveDrawing, type DrawingRecord } from '../src/drawings-api';
import { drawingSegments, snapPoint, type Segment } from '../lib/drawing-snap';
import { DrawingIcon, ReviewStampGraphic, StampFields } from './drawing-controls';
import './job-drawings.css';
let engine: ReturnType<typeof importEngine> | undefined;
async function importEngine() { const pdf = await import('pdfjs-dist/legacy/build/pdf.mjs'); pdf.GlobalWorkerOptions.workerSrc = './supplier-import/pdf.worker.min.mjs'; return pdf; }
async function openPdf(bytes: Uint8Array) { engine ??= importEngine(); const pdf = await engine; return pdf.getDocument({ data: bytes.slice() }).promise; }
function download(bytes: Uint8Array | string, filename: string, type: string) { const url=URL.createObjectURL(new Blob([typeof bytes === 'string' ? bytes : bytes.slice().buffer as ArrayBuffer],{type})); const a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000); }
const lineCache=new WeakMap<PDFDocumentProxy,Map<number,Promise<Segment[]>>>();
async function pageLines(pdf:PDFDocumentProxy,number:number):Promise<Segment[]> {
  let pages=lineCache.get(pdf);if(!pages){pages=new Map();lineCache.set(pdf,pages);}
  if(!pages.has(number))pages.set(number,(async()=>{engine??=importEngine();const lib=await engine;return drawingSegments(await pdf.getPage(number),lib.OPS);})().catch(()=>[]));
  return pages.get(number)!;
}
function Thumb({ pdf, number, label, onClick, selected }: { pdf: PDFDocumentProxy; number: number; label: number; onClick: () => void; selected: boolean }) {
  const canvas=useRef<HTMLCanvasElement>(null),[visible,setVisible]=useState(false);
  useEffect(()=>{if(!canvas.current)return;const observer=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting))setVisible(true);});observer.observe(canvas.current);return()=>observer.disconnect();},[]);
  useEffect(()=>{ if(!visible&&!selected)return;let stopped=false, task: ReturnType<Awaited<ReturnType<PDFDocumentProxy['getPage']>>['render']> | undefined;
    void pageLines(pdf,number).then(()=>pdf.getPage(number)).then(page=>{if(stopped||!canvas.current)return;const base=page.getViewport({scale:1}),v=page.getViewport({scale:110/base.width});canvas.current.width=v.width;canvas.current.height=v.height;task=page.render({canvas:canvas.current,viewport:v});return task.promise;}).catch(()=>{});
    return()=>{stopped=true;task?.cancel();};
  },[pdf,number,visible,selected]);
  return <button className={selected?'selected':''} onClick={onClick} aria-label={`Page ${label}`} aria-current={selected?'page':undefined}><canvas ref={canvas}/><span>Page {label}</span></button>;
}
export function JobDrawings({job,actor,active}:{job:Job;actor:string;active:boolean}) {
  const [records,setRecords]=useState<DrawingRecord[]>([]),[record,setRecord]=useState<DrawingRecord|null>(null),[title,setTitle]=useState(''),[content,setContent]=useState<DrawingContent>(emptyDrawing),[pdf,setPdf]=useState<PDFDocumentProxy|null>(null);
  const [page,setPage]=useState(1),[zoom,setZoom]=useState(1),[rotation,setRotation]=useState(0),[viewport,setViewport]=useState<PageViewport|null>(null),[tool,setTool]=useState('select'),[color,setColor]=useState('#d62828'),[layer,setLayer]=useState<Mark['layer']>('Review');
  const [error,setError]=useState(''),[busy,setBusy]=useState(false),[saveStatus,setSaveStatus]=useState(''),[draft,setDraft]=useState<Point[]>([]),[selected,setSelected]=useState(''),[note,setNote]=useState(''),[known,setKnown]=useState(''),[unit,setUnit]=useState<Scale['unit']>('ft-in'),[reference,setReference]=useState<Point[]>([]),[showPages,setShowPages]=useState(true),[showNotes,setShowNotes]=useState(true);
  const [uploadProgress,setUploadProgress]=useState<number|null>(null),[mode,setMode]=useState('navigate'),[snap,setSnap]=useState(false),[snapAt,setSnapAt]=useState<Point|null>(null),[lines,setLines]=useState<Segment[]>([]),[inches,setInches]=useState(''),[full,setFull]=useState<'none'|'native'|'window'>('none'),[files,setFiles]=useState<File[]>([]);
  const [stamp,setStamp]=useState<ReviewStamp>({status:'Reviewed',reviewer:actor,date:new Intl.DateTimeFormat('en-CA',{timeZone:'America/Toronto',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date()),width:260});
  const viewer=useRef<HTMLDivElement>(null),commentInput=useRef<HTMLTextAreaElement>(null),scrollEdge=useRef<'top'|'bottom'|null>(null),pageLock=useRef(0),wheelTime=useRef(0),wheelDelta=useRef(0),touchStart=useRef<number|null>(null),dragPage=useRef<number|null>(null);
  const order=pdf?drawingPageOrder(content,pdf.numPages):[],sourcePage=order[page-1]??1;
  const measureStart=useRef<Point|null>(null),dimensionDrag=useRef<Mark|null>(null),dimensionLatest=useRef<{id:string;offset:number}|null>(null),[dimensionPreview,setDimensionPreview]=useState<{id:string;offset:number}|null>(null);
  const pan=useRef<{x:number;y:number;left:number;top:number}|null>(null);
  const canvas=useRef<HTMLCanvasElement>(null),stage=useRef<HTMLDivElement>(null),source=useRef<Uint8Array|null>(null),generation=useRef(0),recordRef=useRef<DrawingRecord|null>(null),current=useRef({content,title}),dirty=useRef(false),saving=useRef(false),blocked=useRef(false),loaded=useRef(false),history=useRef<DrawingContent[]>([]),future=useRef<DrawingContent[]>([]),[historyTick,setHistoryTick]=useState(0),gesture=useRef<Point[]|null>(null),timer=useRef<ReturnType<typeof setTimeout>|undefined>(undefined);
  current.current={content,title};
  const reportSave=(value:string)=>{setSaveStatus(value);window.dispatchEvent(new CustomEvent('jgc-drawing-save-status',{detail:value==='Not saved'?'error':value==='Saving\u2026'||value==='Unsaved drawing changes'?'saving':'saved'}));};
  const stash=()=>{if(!recordRef.current)return;try{localStorage.setItem('jgc-drawing-recovery-'+recordRef.current.id,JSON.stringify({...current.current,baseRevision:recordRef.current.revision}));}catch{setError('Local recovery is unavailable. Keep this page open until shared saving finishes.');}};

  const flush=async()=>{
    if(saving.current||blocked.current||!recordRef.current||!dirty.current)return;
    saving.current=true;
    try { while(dirty.current&&recordRef.current){dirty.current=false;const snapshot=current.current,base=recordRef.current;reportSave('Saving…');const saved=await saveDrawing(base,snapshot.content,snapshot.title);recordRef.current=saved;setRecord(saved);setRecords(items=>items.map(r=>r.id===saved.id?saved:r));}if(recordRef.current)localStorage.removeItem('jgc-drawing-recovery-'+recordRef.current.id);reportSave('All drawing changes saved');
    }
    catch(e){dirty.current=true;blocked.current=true;reportSave('Not saved');setError(e instanceof Error?e.message:'Could not save drawings.');}
    finally {saving.current=false;}
  };
  const change=(next:DrawingContent)=>{history.current.push(current.current.content);if(history.current.length>50)history.current.shift();future.current=[];setHistoryTick(x=>x+1);current.current={...current.current,content:next};setContent(next);dirty.current=true;stash();reportSave('Unsaved drawing changes');clearTimeout(timer.current);timer.current=setTimeout(()=>void flush(),600);};
  useEffect(()=>{if(!active||loaded.current)return;loaded.current=true;let cancelled=false;setBusy(true);void listDrawings(job.id).then(rows=>{if(!cancelled)setRecords(rows);}).catch(e=>{if(!cancelled)setError(e.message);}).finally(()=>{if(!cancelled)setBusy(false);});return()=>{cancelled=true;loaded.current=false;};},[job.id,active]);
  useEffect(()=>{ const onLeave=(event:BeforeUnloadEvent)=>{if(dirty.current||saving.current){event.preventDefault();event.returnValue='';}};window.addEventListener('beforeunload',onLeave);return()=>{window.removeEventListener('beforeunload',onLeave);clearTimeout(timer.current);void flush();generation.current++;};},[]);
  useEffect(()=>{
    const changed=()=>{if(document.fullscreenElement===viewer.current)setFull('native');else setFull(value=>value==='native'?'none':value);};
    const escape=(event:KeyboardEvent)=>{if(event.key==='Escape')setFull(value=>value==='window'?'none':value);};
    document.addEventListener('fullscreenchange',changed);window.addEventListener('keydown',escape);
    return()=>{document.removeEventListener('fullscreenchange',changed);window.removeEventListener('keydown',escape);};
  },[]);
  useEffect(()=>{if(full==='window'){const previous=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=previous;};}},[full]);
  useEffect(()=>{if(!active&&full!=='none'){if(document.fullscreenElement)void document.exitFullscreen();setFull('none');}},[active,full]);
  const toggleFull=async()=>{if(full!=='none'){if(document.fullscreenElement)await document.exitFullscreen();setFull('none');return;}if(viewer.current?.requestFullscreen){try{await viewer.current.requestFullscreen();setFull('native');return;}catch{/* Use a full-window viewer on unsupported devices. */}}setFull('window');};
  const navigate=(next:number,edge:'top'|'bottom'='top')=>{if(!pdf||busy||next<1||next>pdf.numPages||next===page)return;scrollEdge.current=edge;pageLock.current=Date.now()+850;setPage(next);setDraft([]);setSelected('');setReference([]);setSnapAt(null);measureStart.current=null;};
  useEffect(()=>{if(!pdf)return;let cancelled=false,task:ReturnType<Awaited<ReturnType<PDFDocumentProxy['getPage']>>['render']>|undefined;setViewport(null);
    void pageLines(pdf,sourcePage).then(found=>{if(!cancelled)setLines(found);return pdf.getPage(sourcePage);}).then(p=>{if(cancelled||!canvas.current)return;const v=p.getViewport({scale:zoom,rotation:(p.rotate+rotation)%360});const ratio=Math.min(window.devicePixelRatio||1,2,Math.sqrt(16000000/(v.width*v.height)),8192/v.width,8192/v.height);canvas.current.width=Math.ceil(v.width*ratio);canvas.current.height=Math.ceil(v.height*ratio);canvas.current.style.width=`${v.width}px`;canvas.current.style.height=`${v.height}px`;setViewport(v);task=p.render({canvas:canvas.current,viewport:v,transform:ratio===1?undefined:[ratio,0,0,ratio,0,0]});return task.promise.then(()=>{if(!cancelled&&stage.current&&scrollEdge.current){stage.current.scrollTop=scrollEdge.current==='bottom'?stage.current.scrollHeight:0;scrollEdge.current=null;}});}).catch(e=>{if(!cancelled)setError(e.message);});return()=>{cancelled=true;task?.cancel();};
  },[pdf,sourcePage,zoom,rotation,full]);
  useEffect(()=>()=>{void pdf?.loadingTask.destroy().catch(()=>{});},[pdf]);
  const open=async(r:DrawingRecord,bytes?:Uint8Array)=>{
    if(dirty.current||saving.current){await flush();if(dirty.current||saving.current){setError('Wait for saving to finish, or recover your unsaved markups before switching drawings.');return;}}
    const token=++generation.current;setBusy(true);setError('');
    try { const data=bytes??await loadDrawing(r), doc=await openPdf(data),c=validateContent(r.content);if(token!==generation.current){void doc.loadingTask.destroy();return;}drawingPageOrder(c,doc.numPages);if(c.marks.some(m=>m.page>doc.numPages))throw new Error('A markup references a missing PDF page.');const previous=pdf;setPdf(doc);if(previous)void previous.loadingTask.destroy();source.current=data;recordRef.current=r;current.current={content:c,title:r.title};dirty.current=false;blocked.current=false;setRecord(r);setTitle(r.title);setContent(c);setPage(1);setRotation(0);const first=await doc.getPage(drawingPageOrder(c,doc.numPages)[0]),v=first.getViewport({scale:1});setZoom(Math.min(1.5,Math.max(.2,((stage.current?.clientWidth||850)-40)/v.width)));history.current=[];future.current=[];setHistoryTick(x=>x+1);setDraft([]);setSelected('');setReference([]);setFiles([]);scrollEdge.current='top';reportSave('All drawing changes saved');
      const local=localStorage.getItem('jgc-drawing-recovery-'+r.id);
      if(local){const recovered=JSON.parse(local);if(window.confirm('Unsaved markups from an interrupted session were found. Restore them?')){const restored=validateContent(recovered.content);drawingPageOrder(restored,doc.numPages);current.current={content:restored,title:recovered.title};setContent(restored);setTitle(recovered.title);dirty.current=true;if(recovered.baseRevision!==r.revision){blocked.current=true;reportSave('Not saved');setError('The shared drawing changed after this recovery draft. Recover unsaved markups before reloading the shared drawing.');}else{reportSave('Unsaved drawing changes');timer.current=setTimeout(()=>void flush(),600);}}} }
    catch(e){setError(e instanceof Error?e.message:'Could not open PDF.');}finally{if(token===generation.current)setBusy(false);}
  };
  const upload=async(file?:File)=>{if(!file)return;if(dirty.current||saving.current){setError('Save the current drawing before uploading another.');return;}setBusy(true);setError('');try{const data=new Uint8Array(await file.arrayBuffer());if(data.length>DRAWING_MAX_BYTES)throw new Error(`Choose a PDF no larger than ${DRAWING_MAX_MB} MB.`);const test=await openPdf(data);await test.loadingTask.destroy();setUploadProgress(0);const result=await addDrawing(job.id,file,setUploadProgress);setRecords(items=>[result.record,...items]);await open(result.record,result.bytes);}catch(e){setError(e instanceof Error?e.message:'Upload failed. Refresh the register to check for an incomplete upload before retrying.');}finally{setBusy(false);setUploadProgress(null);}};
  const point=(event:ReactPointerEvent<SVGSVGElement>,allowSnap=true):Point=>{const box=event.currentTarget.getBoundingClientRect();const [x,y]=viewport!.convertToPdfPoint((event.clientX-box.left)*viewport!.width/box.width,(event.clientY-box.top)*viewport!.height/box.height);const raw={x,y},found=allowSnap&&snap&&tool!=='pen'?snapPoint(raw,lines,8/zoom):{point:raw,snapped:false};setSnapAt(found.snapped?found.point:null);return found.point;};
  const append=(kind:Mark['kind'],points:Point[])=>{if(blocked.current)return;if(kind==='text'&&!note.trim()){setError('Type your note in the Markup text box, then click the drawing to place it.');return;}const mark:Mark={id:crypto.randomUUID(),page:sourcePage,kind,points,color:kind==='stamp'?'#b31a1f':color,text:kind==='callout'?'':note.trim(),...(kind==='stamp'?{stamp:{...stamp}}:{}),...(kind==='distance'?{dimensionOffset:0}:{}),author:actor,createdAt:new Date().toISOString(),layer,rotation:viewport?.rotation??0};change({...current.current.content,marks:[...current.current.content.marks,mark]});setSelected(mark.id);setDraft([]);if(kind==='callout'){setShowNotes(true);setTool('select');requestAnimationFrame(()=>commentInput.current?.focus());}};
  const down=(event:ReactPointerEvent<SVGSVGElement>)=>{if(!viewport||busy||blocked.current||tool==='select'||event.button!==0)return;event.preventDefault();if(tool==='hand'&&stage.current){pan.current={x:event.clientX,y:event.clientY,left:stage.current.scrollLeft,top:stage.current.scrollTop};event.currentTarget.setPointerCapture(event.pointerId);return;}const p=point(event);if(tool==='distance'){if(measureStart.current){if(Math.hypot(p.x-measureStart.current.x,p.y-measureStart.current.y)<.5)return;append('distance',[measureStart.current,p]);measureStart.current=null;}else{measureStart.current=p;setDraft([p]);}return;}if(tool==='area'||tool==='perimeter'){setDraft(points=>[...points,p]);return;}if(tool==='text'||tool==='stamp'){if(tool==='stamp'&&(!stamp.date||!stamp.reviewer.trim())){setError('Enter the reviewer and review date before placing a stamp.');return;}append(tool,[p]);return;}event.currentTarget.setPointerCapture(event.pointerId);gesture.current=[p];setDraft([p]);};
  const move=(event:ReactPointerEvent<SVGSVGElement>)=>{if(dimensionDrag.current&&viewport){const p=point(event,false),d=dimensionGeometry(dimensionDrag.current);const value={id:dimensionDrag.current.id,offset:(p.x-d.a.x)*d.normal.x+(p.y-d.a.y)*d.normal.y};dimensionLatest.current=value;setDimensionPreview(value);return;}if(tool==='distance'&&measureStart.current&&viewport){setDraft([measureStart.current,point(event)]);return;}if(pan.current&&stage.current){stage.current.scrollLeft=pan.current.left-event.clientX+pan.current.x;stage.current.scrollTop=pan.current.top-event.clientY+pan.current.y;return;}if(!gesture.current||!viewport)return;const p=point(event),first=gesture.current[0];gesture.current=tool==='pen'?[...gesture.current,p]:[first,p];setDraft(gesture.current);};
  const up=()=>{if(dimensionDrag.current){const id=dimensionDrag.current.id;dimensionDrag.current=null;const value=dimensionLatest.current;dimensionLatest.current=null;if(value)change({...current.current.content,marks:current.current.content.marks.map(m=>m.id===id?{...m,dimensionOffset:value.offset}:m)});setDimensionPreview(null);return;}pan.current=null;if(['area','perimeter','distance'].includes(tool))return;const points=gesture.current;gesture.current=null;if(!points||points.length<2){setDraft([]);return;}if(tool==='calibrate'){setReference(points);setShowNotes(true);setDraft([]);}else if(['line','rectangle','highlight','distance','pen','callout'].includes(tool))append(tool as Mark['kind'],points);};
  const finish=()=>{if((tool==='area'&&draft.length<3)||(tool==='perimeter'&&draft.length<2))return;append(tool as Mark['kind'],draft);};
  const undo=(redo=false)=>{const from=redo?future.current:history.current,to=redo?history.current:future.current,next=from.pop();if(!next||blocked.current)return;to.push(current.current.content);current.current={...current.current,content:next};setContent(next);dirty.current=true;stash();setHistoryTick(x=>x+1);clearTimeout(timer.current);timer.current=setTimeout(()=>void flush(),600);reportSave('Unsaved drawing changes');};
  const scale=content.scales[String(sourcePage)],marks=content.marks.filter(m=>m.page===sourcePage),selectedMark=content.marks.find(m=>m.id===selected);
  const transform=(p:Point)=>viewport?viewport.convertToViewportPoint(p.x,p.y):[0,0];
  const shape=(m:Mark,preview=false)=>{
    if(dimensionPreview?.id===m.id)m={...m,dimensionOffset:dimensionPreview.offset};const dimension=m.kind==='distance'&&m.points.length===2?dimensionGeometry(m):null;
    const pts=m.points.map(transform),coords=pts.map(p=>p.join(',')).join(' '),label=isMeasurement(m.kind)?measurement(m,scale):m.kind==='text'?m.text:'';
    const angle=(m.rotation??viewport?.rotation??0)*Math.PI/180,p=m.points[0],q=transform({x:p.x+Math.cos(angle),y:p.y+Math.sin(angle)}),screenAngle=Math.atan2(q[1]-pts[0][1],q[0]-pts[0][0])*180/Math.PI;
    const box=pts[1]??pts[0],comment=commentLines(m.text),arrow=pts[1]?Math.atan2(pts[1][1]-pts[0][1],pts[1][0]-pts[0][0]):0;
    const arrowPoints=[-.45,.45].map(offset=>`${pts[0][0]+9*zoom*Math.cos(arrow+offset)},${pts[0][1]+9*zoom*Math.sin(arrow+offset)}`).join(' ');
    return <g key={m.id} className={!preview&&selected===m.id?'drawing-mark selected':'drawing-mark'} style={{color:m.color,strokeWidth:1.5*zoom}} onPointerDown={event=>{if(dimension&&!preview&&!busy&&!blocked.current&&['select','distance'].includes(tool)){event.stopPropagation();setSelected(m.id);setShowNotes(true);dimensionDrag.current=m;dimensionLatest.current=null;setDimensionPreview(null);event.currentTarget.ownerSVGElement?.setPointerCapture(event.pointerId);return;}if(tool==='select'&&!preview){event.stopPropagation();setSelected(m.id);setShowNotes(true);}}} role={!preview?'button':undefined} tabIndex={!preview&&tool==='select'?0:undefined} aria-label={!preview?`${m.kind}: ${label||m.text||m.layer}`:undefined} onKeyDown={event=>{if(event.key==='Enter'){setSelected(m.id);setShowNotes(true);}}}>
      {dimension?<g className="drawing-dimension">
        <line x1={pts[0][0]} y1={pts[0][1]} x2={transform(dimension.start)[0]} y2={transform(dimension.start)[1]} strokeWidth={.75*zoom}/><line x1={pts[1][0]} y1={pts[1][1]} x2={transform(dimension.end)[0]} y2={transform(dimension.end)[1]} strokeWidth={.75*zoom}/>
        <line className="drawing-dimension-line" x1={transform(dimension.start)[0]} y1={transform(dimension.start)[1]} x2={transform(dimension.end)[0]} y2={transform(dimension.end)[1]}/>
        <line className="drawing-dimension-hit" x1={transform(dimension.start)[0]} y1={transform(dimension.start)[1]} x2={transform(dimension.end)[0]} y2={transform(dimension.end)[1]}/>
        {[dimension.start,dimension.end].map((p,i)=>{const a=transform({x:p.x-dimension.normal.x*4,y:p.y-dimension.normal.y*4}),b=transform({x:p.x+dimension.normal.x*4,y:p.y+dimension.normal.y*4});return <line key={i} x1={a[0]} y1={a[1]} x2={b[0]} y2={b[1]}/>;})}
        {(()=>{const a=transform(dimension.start),b=transform(dimension.end),mid=transform(dimension.middle);let rotation=Math.atan2(b[1]-a[1],b[0]-a[0])*180/Math.PI;if(Math.abs(rotation)>90)rotation+=180;return <text className="drawing-dimension-label" transform={`translate(${mid[0]} ${mid[1]}) rotate(${rotation})`} textAnchor="middle" y={-4*zoom} fontSize={10*zoom}>{label}</text>;})()}
      </g>:m.kind==='stamp'&&m.stamp?<g className="drawing-stamp" transform={`translate(${pts[0][0]} ${pts[0][1]}) rotate(${screenAngle}) scale(${m.stamp.width*zoom/350})`}><ReviewStampGraphic stamp={m.stamp}/></g>
      :m.kind==='callout'?<><polyline points={coords}/><polyline points={`${arrowPoints.split(' ')[0]} ${pts[0].join(',')} ${arrowPoints.split(' ')[1]}`}/><g className="drawing-callout" transform={`translate(${box[0]} ${box[1]}) rotate(${screenAngle}) scale(${zoom})`}><rect width="185" height={comment.length*12+14} fill="white"/><text x="7" y="16" fontSize="10">{comment.map((line,i)=><tspan key={i} x="7" dy={i?12:0}>{line}</tspan>)}</text></g></>
      :['rectangle','highlight'].includes(m.kind)&&pts[1]?<rect fill={m.kind==='highlight'?'currentColor':'none'} fillOpacity={m.kind==='highlight'?.25:0} stroke={m.kind==='highlight'?'none':undefined} x={Math.min(pts[0][0],pts[1][0])} y={Math.min(pts[0][1],pts[1][1])} width={Math.abs(pts[1][0]-pts[0][0])} height={Math.abs(pts[1][1]-pts[0][1])}/>
      :['area','perimeter'].includes(m.kind)?<polygon points={coords}/>:m.kind!=='text'?<polyline points={coords}/>:null}
      {label&&m.kind!=='distance'&&<text transform={`rotate(${screenAngle},${pts[0][0]},${pts[0][1]})`} x={pts[0][0]} y={pts[0][1]} fontSize={10*zoom}>{label.split("\n").map((line,i)=><tspan key={i} x={pts[0][0]} dy={i?12*zoom:0}>{line}</tspan>)}</text>}
    </g>;
  };
  const fit=async()=>{if(!pdf||!stage.current)return;const p=await pdf.getPage(sourcePage),v=p.getViewport({scale:1,rotation:(p.rotate+rotation)%360});setZoom(Math.min(4,Math.max(.1,(stage.current.clientWidth-40)/v.width)));};
  const exportPdf=async()=>{if(!source.current||!record)return;setBusy(true);setError('');try{await flush();if(dirty.current)throw new Error('Save your markups before exporting. Use Recover markups if saving is blocked.');const {markedDrawingPdf}=await import('../lib/drawing-pdf');const bytes=await markedDrawingPdf(source.current,current.current.content);download(bytes,`${title.replace(/[^a-z0-9 _-]/gi,'').trim()||'Drawing'} - JGC marked.pdf`,'application/pdf');}catch(e){setError(e instanceof Error?e.message:'Could not export drawing.');}finally{setBusy(false);}};
  const chooseMode=(value:string)=>{measureStart.current=null;setMode(value);setTool(value==='measure'?'calibrate':value==='stamps'?'stamp':value==='comments'?'callout':'select');setDraft([]);setError('');setShowNotes(value!=='organize');};
  const reorderPage=(from:number,to:number)=>{if(from===to||blocked.current||busy||to<0||to>=order.length)return;const next=[...order],[moved]=next.splice(from,1);next.splice(to,0,moved);change({...current.current.content,pageOrder:next});setPage(next.indexOf(sourcePage)+1);};
  const combine=async()=>{
    if(!source.current||!record||!files.length)return;await flush();if(dirty.current||saving.current){setError('Wait for shared saving to finish before combining PDFs.');return;}
    setBusy(true);setError('');
    try{
      if(files.reduce((sum,file)=>sum+file.size,source.current.length)>2*DRAWING_MAX_BYTES)throw new Error(`Choose a smaller set of files to combine (${DRAWING_MAX_MB*2} MB total input limit).`);
      const additional:Uint8Array[]=[];for(const file of files)additional.push(new Uint8Array(await file.arrayBuffer()));
      const {combinedDrawingPdf}=await import('../lib/drawing-pdf'),result=await combinedDrawingPdf(source.current,current.current.content,additional);
      const file=new File([result.bytes.slice().buffer as ArrayBuffer],`${title||'Drawing'} - Combined.pdf`,{type:'application/pdf'}),created=await addDrawing(job.id,file,setUploadProgress);
      setRecords(items=>[created.record,...items]);await open(created.record,created.bytes);change(result.content);await flush();setFiles([]);
    }catch(e){setError(e instanceof Error?e.message:'Could not combine PDFs. Refresh the register before retrying.');}finally{setBusy(false);setUploadProgress(null);}
  };
  useEffect(()=>{
    const view=stage.current;if(!view||!pdf)return;
    const boundary=(delta:number)=>delta>0?view.scrollTop+view.clientHeight>=view.scrollHeight-2:view.scrollTop<=2;
    const advance=(delta:number)=>{if(Date.now()<pageLock.current||busy||!delta||!boundary(delta))return false;const next=page+(delta>0?1:-1);if(next<1||next>pdf.numPages)return false;navigate(next,delta>0?'top':'bottom');return true;};
    const wheel=(event:WheelEvent)=>{if(event.ctrlKey||event.metaKey||Math.abs(event.deltaX)>Math.abs(event.deltaY))return;if(Date.now()-wheelTime.current>250)wheelDelta.current=0;wheelTime.current=Date.now();wheelDelta.current+=event.deltaY;
      if(boundary(event.deltaY)&&Math.abs(wheelDelta.current)>35&&advance(event.deltaY)){event.preventDefault();wheelDelta.current=0;}};
    const scroll=()=>{if(Date.now()-wheelTime.current<250&&Math.abs(wheelDelta.current)>35)advance(wheelDelta.current);};
    const start=(event:TouchEvent)=>{if(['select','hand'].includes(tool)&&event.touches.length===1)touchStart.current=event.touches[0].clientY;else touchStart.current=null;};
    const end=(event:TouchEvent)=>{if(touchStart.current===null)return;const delta=touchStart.current-(event.changedTouches[0]?.clientY??touchStart.current);touchStart.current=null;if(Math.abs(delta)>60)advance(delta);};
    view.addEventListener('wheel',wheel,{passive:false});view.addEventListener('scroll',scroll);view.addEventListener('touchstart',start,{passive:true});view.addEventListener('touchend',end,{passive:true});
    return()=>{view.removeEventListener('wheel',wheel);view.removeEventListener('scroll',scroll);view.removeEventListener('touchstart',start);view.removeEventListener('touchend',end);};
  },[pdf,page,busy,full,tool]);
  const scaleDescription=scale?`${scale.knownLength} ${scale.displayUnit??(scale.unit==='ft'?'ft-in':scale.unit)} reference saved`:'Calibrate each page before measuring.';
  const tools:Record<string,[string,string][]>={
    navigate:[],measure:[['calibrate','Set scale'],['distance','Distance'],['perimeter','Perimeter'],['area','Area']],
    stamps:[['stamp','Shop drawing stamp']],comments:[['callout','Arrow comment'],['text','Text']],edit:[['pen','Pen'],['line','Line'],['rectangle','Box'],['highlight','Highlight'],['text','Text']],organize:[],
  };
  const viewerContent=pdf?(      <div ref={viewer} className={`drawing-viewer ${full!=='none'?'is-fullscreen':''}`} aria-label="Drawing viewer">
      {full!=='none'&&<div className="drawing-full-title"><strong>{title}</strong><span>Job {job.jobNumber}</span></div>}
      <div className="drawing-modes" role="toolbar" aria-label="Drawing modes">
        {([['navigate','View'],['measure','Measure'],['stamps','Stamps'],['comments','Comments'],['edit','Edit'],['organize','Organize pages']] as const).map(([key,label])=><button key={key} aria-pressed={mode===key} onClick={()=>chooseMode(key)}><DrawingIcon name={key}/>{label}</button>)}
        <button className="drawing-full-button" onClick={()=>void toggleFull()}><DrawingIcon name={full==='none'?'fullscreen':'exit'}/>{full==='none'?'Full screen':'Exit full screen'}</button>
      </div>
      <div className="drawing-toolbar" role="toolbar" aria-label="Drawing tools">
        <button aria-pressed={showPages} onClick={()=>setShowPages(v=>!v)}><DrawingIcon name="pages"/>Pages</button>
        {[['select','Select'],['hand','Hand'],...tools[mode]].map(([key,label])=><button key={key} disabled={busy||blocked.current||(isMeasurement(key)&&!scale)} aria-pressed={tool===key} title={isMeasurement(key)&&!scale?'Set this page’s scale first':label} onClick={()=>{setTool(key);measureStart.current=null;setDraft([]);setError('');if(['text','calibrate','stamp','callout'].includes(key))setShowNotes(true);}}><DrawingIcon name={key}/>{label}</button>)}
        {['measure','edit','comments'].includes(mode)&&<button aria-pressed={snap} onClick={()=>{setSnap(v=>!v);setSnapAt(null);}} title="Snap to vector line endpoints and edges"><DrawingIcon name="snap"/>Snap to lines</button>}
        {['edit','comments','measure'].includes(mode)&&<label className="drawing-color">Colour<input type="color" aria-label="Markup colour" value={color} onChange={e=>setColor(e.target.value)}/></label>}
        <select aria-label="Markup layer" value={layer} onChange={e=>setLayer(e.target.value as Mark['layer'])}><option>Review</option><option>As-built</option></select>
        <button disabled={!history.current.length||blocked.current||busy} onClick={()=>undo()}><DrawingIcon name="undo"/>Undo</button><button disabled={!future.current.length||blocked.current||busy} onClick={()=>undo(true)}><DrawingIcon name="redo"/>Redo</button>
        <button aria-pressed={showNotes} onClick={()=>setShowNotes(v=>!v)}><DrawingIcon name="comments"/>Markup panel</button><button className="drawing-export" disabled={busy||blocked.current} onClick={()=>void exportPdf()}><DrawingIcon name="download"/>Download marked PDF</button>
      </div>
      {mode==='organize'&&<div className="drawing-organizer">
        <div><h3>Organize pages</h3><p>Drag a page to its new position, or use its arrows. Markups and scales follow their original page.</p></div>
        <div className="drawing-page-cards">{order.map((n,i)=><div key={n} className={page===i+1?'selected':''} draggable={!busy&&!blocked.current} onDragStart={e=>{dragPage.current=i;e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',String(i));}} onDragOver={e=>{if(dragPage.current!==null)e.preventDefault();}} onDrop={e=>{e.preventDefault();if(dragPage.current!==null)reorderPage(dragPage.current,i);dragPage.current=null;}} onDragEnd={()=>{dragPage.current=null;}}>
          <Thumb pdf={pdf} number={n} label={i+1} selected={page===i+1} onClick={()=>navigate(i+1)}/><small>Source page {n}</small><div><button aria-label={`Move page ${i+1} earlier`} disabled={i===0||busy||blocked.current} onClick={()=>reorderPage(i,i-1)}>←</button><button aria-label={`Move page ${i+1} later`} disabled={i===order.length-1||busy||blocked.current} onClick={()=>reorderPage(i,i+1)}>→</button></div>
        </div>)}</div>
        <div className="drawing-combine"><label>Append PDFs to this drawing<input aria-label="PDFs to combine" type="file" accept="application/pdf,.pdf" multiple disabled={busy||blocked.current} onChange={e=>setFiles(Array.from(e.target.files??[]))}/></label>
          <span>{files.map(file=>file.name).join(' · ')}</span><button className="button primary compact" disabled={!files.length||busy||blocked.current} onClick={()=>void combine()}><DrawingIcon name="combine"/>Create combined PDF</button><small>Creates a new shared drawing using the page order above. The current drawing and each source file stay intact.</small>
        </div>
      </div>}
      <div className="drawing-viewbar"><button aria-label="Previous page" disabled={page===1||busy} onClick={()=>navigate(page-1,'bottom')}>‹</button><label>Page <input aria-label="Page number" type="number" min={1} max={pdf.numPages} value={page} onChange={e=>{const n=Number(e.target.value);if(Number.isInteger(n)&&n>=1&&n<=pdf.numPages)navigate(n);}}/> of {pdf.numPages}</label><button aria-label="Next page" disabled={page===pdf.numPages||busy} onClick={()=>navigate(page+1)}>›</button><button aria-label="Zoom out" onClick={()=>setZoom(z=>Math.max(.1,z/1.25))}>−</button><span>{Math.round(zoom*100)}%</span><button aria-label="Zoom in" onClick={()=>setZoom(z=>Math.min(4,z*1.25))}>＋</button><button onClick={()=>void fit()}><DrawingIcon name="fit"/>Fit width</button><button onClick={()=>setRotation(r=>(r+90)%360)}><DrawingIcon name="rotate"/>Rotate view</button><span className="drawing-scale-label">{scale?`Calibrated · ${scaleDescription}`:'Page scale not set'}</span></div>
      {snap&&<div className="drawing-snap-hint">{lines.length?'Snapping to drawing line endpoints and edges.':'No vector lines found on this page. Scanned drawings can be measured manually.'}</div>}
      <div className={`drawing-workspace ${showPages?'with-pages':''} ${showNotes?'with-comments':''}`}>
        {showPages&&<aside className="drawing-thumbnails" aria-label="Page thumbnails">{order.map((n,i)=><Thumb key={n} pdf={pdf} number={n} label={i+1} selected={page===i+1} onClick={()=>navigate(i+1)}/>)}</aside>}
        <div ref={stage} className="drawing-stage" tabIndex={0} aria-label="PDF drawing view"><div className="drawing-sheet" style={viewport?{width:viewport.width,height:viewport.height}:undefined}><canvas ref={canvas}/>{viewport&&<svg aria-label="Drawing markup canvas" viewBox={`0 0 ${viewport.width} ${viewport.height}`} width={viewport.width} height={viewport.height} className={`drawing-overlay tool-${tool}`} onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={()=>{pan.current=null;gesture.current=null;dimensionDrag.current=null;setDimensionPreview(null);measureStart.current=null;setDraft([]);}}>{marks.map(m=>shape(m))}{draft.length>0&&shape({id:'preview',page:sourcePage,kind:tool==='calibrate'?'line':tool as Mark['kind'],points:draft,color,text:note,author:actor,createdAt:'',layer},true)}{snapAt&&<circle className="drawing-snap-point" cx={transform(snapAt)[0]} cy={transform(snapAt)[1]} r="6"/>}</svg>}</div></div>
        {showNotes&&<aside className="drawing-comments"><h3>Page {page} · {mode==='stamps'?'Review stamp':'Markups'}</h3><p className="drawing-hint">{tool==='select'?'Select a markup to view its details.':tool==='area'||tool==='perimeter'?'Click each corner, then Finish.':tool==='text'?'Type below, then click the drawing.':tool==='stamp'?'Choose your review status, then click the drawing to place the stamp.':tool==='callout'?'Drag from the arrow tip to the comment box, then type your comment.':tool==='distance'?'Click the first point, then the second. Drag the dimension line to offset it without changing the endpoints.':tool==='calibrate'?'Drag along a known dimension, then enter its actual length below.':'Drag on the drawing to add a markup.'}</p>
          {['area','perimeter'].includes(tool)&&<div><button className="button primary compact" disabled={draft.length<(tool==='area'?3:2)} onClick={finish}>Finish {tool}</button><button className="button secondary compact" onClick={()=>setDraft([])}>Cancel</button></div>}
          {mode==='stamps'&&<StampFields value={stamp} onChange={setStamp} disabled={busy||blocked.current}/>}
          {['edit','comments'].includes(mode)&&<label>Markup text<textarea aria-label="Markup text" value={note} maxLength={2000} onChange={e=>setNote(e.target.value)}/></label>}
          {mode==='measure'&&<fieldset><legend>Page scale</legend><p>{scaleDescription}</p><label>Scale units<select aria-label="Scale units" value={unit} onChange={e=>setUnit(e.target.value as Scale['unit'])}><option value="ft">Feet</option><option value="in">Inches</option><option value="ft-in">Feet &amp; inches</option><option value="m">Metres</option><option value="cm">Centimetres</option><option value="mm">Millimetres</option></select></label><label>{unit==='ft-in'?'Known feet':'Known length'}<input aria-label="Known length" type="number" min="0" step="any" value={known} onChange={e=>setKnown(e.target.value)}/></label>{unit==='ft-in'&&<label>Known inches<input aria-label="Known inches" type="number" min="0" step="any" value={inches} onChange={e=>setInches(e.target.value)}/></label>}<button className="button secondary compact" disabled={busy||reference.length!==2||blocked.current} onClick={()=>{try{const s=calibrate(reference,Number(known)+(unit==='ft-in'?Number(inches)/12:0),unit);change({...current.current.content,scales:{...current.current.content.scales,[sourcePage]:s}});setReference([]);setTool('distance');setError('');}catch(e){setError((e as Error).message);}}}>Apply page scale</button></fieldset>}
          {selectedMark&&<div className="drawing-selection"><strong>{selectedMark.kind} · {selectedMark.layer}</strong>{selectedMark.kind==='stamp'&&selectedMark.stamp&&<StampFields prefix="Selected stamp" value={selectedMark.stamp} disabled={busy||blocked.current} onChange={value=>{if(value.date)change({...current.current.content,marks:current.current.content.marks.map(m=>m.id===selected?{...m,stamp:value}:m)});}}/>}<label>Comment<textarea ref={commentInput} aria-label="Edit selected comment" disabled={blocked.current} value={selectedMark.text} maxLength={2000} onChange={e=>change({...current.current.content,marks:current.current.content.marks.map(m=>m.id===selected?{...m,text:e.target.value}:m)})}/></label>{isMeasurement(selectedMark.kind)&&<p>{measurement(selectedMark,content.scales[String(selectedMark.page)])}</p>}<small>{selectedMark.author} · {new Date(selectedMark.createdAt).toLocaleString()}</small><button className="button secondary compact" disabled={blocked.current} onClick={()=>{change({...current.current.content,marks:current.current.content.marks.filter(m=>m.id!==selected)});setSelected('');}}>Remove markup</button></div>}
          <ul>{marks.map(m=><li key={m.id}><button className={m.id===selected?'selected':''} onClick={()=>setSelected(m.id)}><span style={{background:m.color}}/><strong>{m.layer} · {m.kind}</strong><small>{isMeasurement(m.kind)?measurement(m,scale):m.kind==='stamp'?m.stamp?.status:m.text||m.author}</small></button></li>)}</ul>
        </aside>}
      </div><footer className="drawing-footer">Scroll to the bottom or top to move between pages · Original PDF preserved · Markups autosave separately · Verify your page scale against a known dimension. <button onClick={()=>source.current&&download(source.current,record?.file_name||'Original.pdf','application/pdf')}>Download original</button></footer>
      </div>):null;
  // Component stays mounted across Job tabs so pending saves finish safely.
  return <section className="job-drawings" hidden={!active} aria-label="Job drawings">
    <header className="drawing-heading"><div><span className="eyebrow">JGC · DRAWING WORKSPACE</span><h2>Drawings</h2><p>Review, measure and record as-built changes for Job {job.jobNumber}. PDFs up to {DRAWING_MAX_MB} MB.</p></div><label className={`button primary ${busy?'disabled':''}`}>＋ Upload PDF<input type="file" accept="application/pdf,.pdf" disabled={busy||blocked.current} onChange={e=>{void upload(e.target.files?.[0]);e.target.value='';}}/></label></header>
    {error&&<div className="drawing-notice" role="alert"><p>{error}</p>{record&&<div><button className="button secondary compact" disabled={busy||saving.current} onClick={()=>{blocked.current=false;void flush();}}>Retry saving</button><button className="button secondary compact" disabled={busy||saving.current} onClick={()=>{if(dirty.current&&!window.confirm('Reload will discard unsaved markups. Download Recover unsaved markups first if you need to keep them. Continue?'))return;localStorage.removeItem('jgc-drawing-recovery-'+recordRef.current?.id);dirty.current=false;blocked.current=false;void listDrawings(job.id).then(rows=>{setRecords(rows);const latest=rows.find(r=>r.id===record.id);if(latest)void open(latest);}).catch(e=>setError(e.message));}}>Reload saved drawing</button><button className="button secondary compact" onClick={()=>download(JSON.stringify({drawingId:record.id,fileName:record.file_name,...current.current.content},null,2),'JGC unsaved markups.json','application/json')}>Recover unsaved markups</button></div>}</div>}
    <div className="drawing-register"><label>Drawing<select aria-label="Select drawing" value={record?.id??''} disabled={busy||saving.current} onChange={e=>{const r=records.find(r=>r.id===e.target.value);if(r)void open(r);}}><option value="">Choose a drawing…</option>{records.map(r=><option key={r.id} value={r.id}>{r.title}</option>)}</select></label><button className="button secondary compact" disabled={busy||saving.current} onClick={()=>{void (async()=>{await flush();if(dirty.current||saving.current)return;setBusy(true);try{const rows=await listDrawings(job.id);setRecords(rows);const latest=rows.find(r=>r.id===record?.id);if(latest)await open(latest);}catch(e){setError((e as Error).message);}finally{setBusy(false);}})();}}>Refresh drawings</button><span role="status">{busy?(uploadProgress!==null?`Uploading drawing · ${uploadProgress}%`:'Working…'):saveStatus||`${records.length} shared drawing${records.length===1?'':'s'}`}</span></div>
    {!pdf?<div className="drawing-empty"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M6 2h8l4 4v16H6zM14 2v5h5M9 12h6M9 16h6"/></svg><h3>{busy?'Opening drawing…':'Your Job drawings, together'}</h3><p>Upload a PDF or choose a saved drawing. The original stays intact; markups are saved separately and included in your marked PDF export.</p></div>:<>
      <div className="drawing-document-title"><input aria-label="Drawing title" value={title} disabled={busy||blocked.current} onChange={e=>{setTitle(e.target.value);current.current={...current.current,title:e.target.value};dirty.current=true;stash();reportSave('Unsaved drawing changes');clearTimeout(timer.current);timer.current=setTimeout(()=>void flush(),600);}}/><span>{record?.file_name} · Shared with JGC admins</span></div>
      {full==='window'?createPortal(viewerContent,document.body):viewerContent}
    </>}
  </section>;
}
