import { useEffect, useMemo, useRef, useState, type Dispatch, type SetStateAction } from 'react';
import type { AppState, Job } from '../lib/estimator-data';
import { createSitePlan, createTaskPage, safetyId, sitePlanDate, sitePlanErrors, sitePlanFileName, type SafetyPage, type SiteSpecificPlan } from '../lib/site-specific';
import { loadSafetyAttachments, uploadSafetyAttachment, readSafetyAttachment, publishSafetyPlan } from '../src/site-specific-api';
import './site-specific-builder.css';
type Props={job:Job;state:AppState;setState:Dispatch<SetStateAction<AppState>>;actor:string;workspaceSaved:boolean};
export function SiteSpecificBuilder({job,state,setState,actor,workspaceSaved}:Props) {
 const initial=useMemo(()=>createSitePlan(job,actor),[job.id,actor,job.jobNumber,job.project,job.portalJobName,job.portalAddress,job.portalCustomer,job.projectManager]);const plan=job.siteSpecific||initial;
 const [view,setView]=useState('Details'),[pageId,setPageId]=useState('scope'),[kind,setKind]=useState<SafetyPage['kind']>('task'),[search,setSearch]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(false),[files,setFiles]=useState<File[]>([]),[pdfLink,setPdfLink]=useState('');
 const fileInput=useRef<HTMLInputElement>(null),cachedPdf=useRef<{stamp:string;blob:Blob;pages:number}|null>(null),oldUrls=useRef<string[]>([]);
 const current=plan.pages.find(p=>p.id===pageId)||plan.pages[0],included=plan.pages.filter(p=>p.included);
 useEffect(()=>()=>{oldUrls.current.forEach(url=>URL.revokeObjectURL(url));},[]);
 function notice(text:string,bad=false){setMessage(text);setError(bad);}
 function change(update:(p:SiteSpecificPlan)=>SiteSpecificPlan){cachedPdf.current=null;setPdfLink('');setState(s=>({...s,jobs:s.jobs.map(j=>j.id===job.id?{...j,siteSpecific:{...update(j.siteSpecific||createSitePlan(j,actor)),updatedAt:new Date().toISOString()}}:j)}));}
 function field(key:keyof SiteSpecificPlan,value:string){change(p=>({...p,[key]:value}));}
 function pageChange(update:(p:SafetyPage)=>SafetyPage){change(p=>({...p,pages:p.pages.map(x=>x.id===current.id?update(x):x)}));}
 function move(id:string,delta:number){change(p=>{const pages=[...p.pages],index=pages.findIndex(x=>x.id===id),next=index+delta;if(next<0||next>=pages.length)return p;[pages[index],pages[next]]=[pages[next],pages[index]];return {...p,pages};});}
 function savePage(){if(!current.fields.some(f=>f.value.trim()))return notice('Fill out this page before saving it to the library.',true);const saved={...structuredClone(current),id:safetyId(),savedAt:new Date().toISOString(),savedBy:actor,jobNumber:job.jobNumber};setState(s=>({...s,safetyLibrary:[saved,...(s.safetyLibrary||[])]}));notice('Page saved to the reusable library. The log keeps each saved version.');}
 function addPage(){const next=createTaskPage(kind);change(p=>({...p,pages:[...p.pages,next]}));setPageId(next.id);setView('Pages');}
 async function sources(){setBusy(true);notice('Loading Portal documents…');try{const data=await loadSafetyAttachments(job);change(p=>{const selected=new Map(p.attachments.map(a=>[a.id,a]));const merged=data.items.map(a=>({...a,included:selected.get(a.id)?.included||false}));return {...p,attachments:[...merged,...p.attachments.filter(a=>!merged.some(b=>b.id===a.id))]};});notice(data.warnings.length?data.warnings.join(' '):`${data.items.length} Portal documents loaded. Select what belongs in this plan.`,!!data.warnings.length);}catch(e){notice(e instanceof Error?e.message:'Documents could not be loaded.',true);}finally{setBusy(false);}}
 async function upload(){if(!files.length)return;setBusy(true);try{for(const [i,file] of files.entries()){notice(`Uploading supporting file ${i+1} of ${files.length}: ${file.name}`);const item=await uploadSafetyAttachment(job,file);change(p=>({...p,attachments:p.attachments.some(a=>a.id===item.id)?p.attachments:[...p.attachments,item]}));}setFiles([]);if(fileInput.current)fileInput.current.value='';notice('Supporting files saved privately. They will be included in the combined PDF when selected.');}catch(e){notice(e instanceof Error?e.message:'Upload failed. Your files are kept for retry.',true);}finally{setBusy(false);}}
 async function output(mode:'download'|'preview'|'publish') {
 const errors=sitePlanErrors(plan);if(errors.length)return notice('Complete: '+errors.join(', ')+'.',true);if(!workspaceSaved||!job.siteSpecific)return notice('Save the plan and wait for the workspace to finish syncing.',true);if(files.length)return notice('Upload the selected supporting files first.',true);
 let preview:Window|null=null;if(mode==='preview')preview=window.open('about:blank','_blank');setBusy(true);setPdfLink('');try{
  const stamp=plan.updatedAt;let built=cachedPdf.current;if(!built||built.stamp!==stamp){notice('Preparing the PDF…');const module=await import('../lib/site-specific-pdf');const logo=await fetch('jgc-logo-transparent.png');if(!logo.ok)throw new Error('The JGC logo could not load.');const generated=await module.buildSiteSpecificPdf({plan,logoBytes:new Uint8Array(await logo.arrayBuffer()),readAttachment:a=>readSafetyAttachment(job,a),progress:t=>notice(t)});built={stamp,...generated};cachedPdf.current=built;}
  if(mode==='publish'){notice('Publishing the completed PDF to this Job Board…');const published=await publishSafetyPlan(job,plan,built.blob);setState(s=>({...s,jobs:s.jobs.map(j=>j.id===job.id&&j.siteSpecific?.updatedAt===stamp?{...j,siteSpecific:{...j.siteSpecific,published}}:j)}));window.dispatchEvent(new CustomEvent('jgc-site-plan-published',{detail:{jobId:job.id}}));notice(`Revision ${plan.revision} published in the Job Board’s Site Specific section (${built.pages} pages).`);}
  else{const url=URL.createObjectURL(built.blob);oldUrls.current.push(url);while(oldUrls.current.length>3)URL.revokeObjectURL(oldUrls.current.shift()!);setPdfLink(url);if(mode==='preview'&&preview){preview.opener=null;preview.location.href=url;}else if(mode==='download'){const a=document.createElement('a');a.href=url;a.download=sitePlanFileName(plan);a.click();}notice(`${built.pages}-page PDF ready. Selected attachments are included in full.`);}
 }catch(e){preview?.close();notice(e instanceof Error?e.message:'The PDF could not be created. Your plan is kept.',true);}finally{setBusy(false);}
 }
 const library=(state.safetyLibrary||[]).filter(p=>`${p.title} ${p.kind} ${p.jobNumber}`.toLowerCase().includes(search.toLowerCase())).slice().sort((a,b)=>b.savedAt.localeCompare(a.savedAt));
 return <section className="panel ss-builder" aria-label="Site-specific plan builder">
  <div className="panel-heading"><div><span className="eyebrow">JOB {job.jobNumber} · SAFETY</span><h2>Create Site Specific</h2><p>Build the plan, choose its pages and combine supporting documents into one JGC PDF.</p></div></div>
  <div className="ss-toolbar"><button type="button" className="button secondary" disabled={busy} onClick={()=>{change(p=>p);notice('Plan saved to the job. Check the workspace save status before leaving.');}}>Save plan</button><button type="button" className="button secondary" disabled={busy||!workspaceSaved||!job.siteSpecific||!!files.length} onClick={()=>void output('preview')}>Preview PDF</button><button type="button" className="button secondary" disabled={busy||!workspaceSaved||!job.siteSpecific||!!files.length} onClick={()=>void output('download')}>Download PDF</button><button type="button" className="button primary" disabled={busy||!workspaceSaved||!job.siteSpecific||!!files.length} onClick={()=>void output('publish')}>Publish to Job Board</button></div>
  <p className="ss-save-state">{!job.siteSpecific?'Save the plan to start.':workspaceSaved?'Plan saved with the job.':'Saving plan to the workspace…'}{plan.published&&` Published revision ${plan.published.revision} · ${new Date(plan.published.at).toLocaleString('en-CA',{timeZone:'America/Toronto'})}.`}</p>
  {message&&<p className={`ss-message ${error?'error':''}`} role="status">{message}</p>}{pdfLink&&<p className="ss-message"><a href={pdfLink} target="_blank" rel="noopener">Open PDF</a> · <a href={pdfLink} download={sitePlanFileName(plan)}>Download {sitePlanFileName(plan)}</a></p>}
  <nav className="ss-tabs" aria-label="Plan editor">{['Details','Pages','Saved pages','Attachments'].map(tab=><button type="button" key={tab} aria-pressed={view===tab} className={view===tab?'active':''} onClick={()=>{setView(tab);setSearch('');}}>{tab}</button>)}</nav>
  <div className="ss-body"><fieldset className="ss-editor" disabled={busy}>
   {view==='Details'&&<><h3>Plan details</h3><div className="ss-grid">{([['project','Project'],['jobNumber','Job number'],['address','Site address'],['client','Client / owner'],['preparedBy','Prepared by'],['planDate','Plan date'],['revision','Revision']] as const).map(([key,label])=><label className="field" key={key}><span>{label}</span><input readOnly={key==='jobNumber'} type={key==='planDate'?'date':'text'} maxLength={key==='address'?700:240} value={plan[key]} onChange={e=>field(key,e.target.value)} /></label>)}</div><p>Use Pages to enter the safety information. Blank fields are marked “Not entered” in the PDF.</p></>}
   {view==='Pages'&&<><h3>Plan pages</h3><details className="ss-page-list"><summary>{included.length} pages included · Choose or arrange pages</summary>{plan.pages.map((p,index)=><div className="ss-page-row" key={p.id}><label><input type="checkbox" checked={p.included} onChange={e=>{const checked=e.target.checked;change(x=>({...x,pages:x.pages.map(y=>y.id===p.id?{...y,included:checked}:y)}));}} /><span>{p.title}</span></label><div><button type="button" onClick={()=>setPageId(p.id)}>Edit</button><button type="button" aria-label={`Move ${p.title} up`} disabled={index===0} onClick={()=>move(p.id,-1)}>↑</button><button type="button" aria-label={`Move ${p.title} down`} disabled={index===plan.pages.length-1} onClick={()=>move(p.id,1)}>↓</button></div></div>)}</details><div className="ss-grid"><label className="field"><span>Edit plan page</span><select value={current.id} onChange={e=>setPageId(e.target.value)}>{plan.pages.map(p=><option key={p.id} value={p.id}>{p.title}{p.included?'':' (not included)'}</option>)}</select></label><div className="ss-add-page"><label className="field"><span>New page type</span><select value={kind} onChange={e=>setKind(e.target.value as SafetyPage['kind'])}>{['task','procedure','risk','custom'].map(k=><option key={k} value={k}>{k[0].toUpperCase()+k.slice(1)}</option>)}</select></label><button type="button" className="button secondary" onClick={addPage}>Add page</button></div></div><label className="field"><span>Page title</span><input value={current.title} maxLength={200} onChange={e=>{const value=e.target.value;pageChange(p=>({...p,title:value}));}} /></label>{current.fields.map(f=><label className="field" key={f.id}><span>{f.label}</span><textarea rows={4} maxLength={20000} value={f.value} onChange={e=>{const value=e.target.value;pageChange(p=>({...p,fields:p.fields.map(x=>x.id===f.id?{...x,value}:x)}));}} /></label>)}<div className="ss-actions"><button type="button" className="button secondary" onClick={savePage}>Save page to library</button>{current.kind!=='section'&&<button type="button" className="button secondary" onClick={()=>{change(p=>({...p,pages:p.pages.filter(x=>x.id!==current.id)}));setPageId('scope');}}>Remove this page</button>}</div></>}
   {view==='Saved pages'&&<><h3>Reusable page log</h3><p>Each saved task, procedure or risk page is kept as a separate version, newest first. Reusing it creates an editable copy in this job’s plan.</p><label className="field"><span>Find saved pages</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Title, type or job number" /></label>{library.length?library.map(p=><details className="ss-library" key={p.id}><summary>{p.title}<small>{p.kind} · Job {p.jobNumber} · {new Date(p.savedAt).toLocaleDateString('en-CA',{timeZone:'America/Toronto'})}</small></summary><p>Saved by {p.savedBy}</p>{p.fields.map(f=><div key={f.id}><strong>{f.label}</strong><p className="ss-preserve">{f.value||'Not entered'}</p></div>)}<button type="button" className="button secondary" onClick={()=>{const copy={...structuredClone(p),id:safetyId(),included:true};change(x=>({...x,pages:[...x.pages,copy]}));setPageId(copy.id);setView('Pages');notice('Saved page copied into this plan. Edit it for this site.');}}>Use in this plan</button></details>):<p>No saved pages yet. Fill a page under Pages, then choose Save page to library.</p>}</>}
   {view==='Attachments'&&<><h3>Supporting documents</h3><p>Select Portal certificates, this job’s JSAs, the complete JGC policy and other documents. Every selected file is appended in full to the exported PDF.</p><button type="button" className="button secondary" onClick={()=>void sources()}>Load Portal documents</button><label className="field"><span>Find supporting documents</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Employee, policy, JSA or file name" /></label>{plan.attachments.filter(a=>`${a.title} ${a.category} ${a.kind}`.toLowerCase().includes(search.toLowerCase())).map(a=><label className="ss-attachment" key={a.id}><input type="checkbox" checked={a.included} onChange={e=>{const checked=e.target.checked;change(p=>({...p,visibility:checked&&a.kind==='certificate'?'restricted':p.visibility,attachments:p.attachments.map(x=>x.id===a.id?{...x,included:checked}:x)}));}} /><span><strong>{a.title}</strong><small>{a.kind==='certificate'?'Portal certificate':a.category==='jgc-policy'?'Complete JGC policy':a.category==='jsa'?'Job safety analysis': 'Job document'}{a.expiryDate&&` · ${a.expiryDate<sitePlanDate()?'Expired':'Expires'} ${a.expiryDate}`}</small></span></label>)}<div className="ss-upload"><label className="field"><span>Additional PDFs, forms or photos</span><input ref={fileInput} type="file" accept=".pdf,.jpg,.jpeg,.png,.webp" multiple onChange={e=>setFiles(Array.from(e.target.files||[]))} /></label><p>Originals are saved privately and kept separately from the combined PDF. Each file can be up to 20 MB.</p>{files.length>0&&<button type="button" className="button secondary" onClick={()=>void upload()}>Upload {files.length} supporting {files.length===1?'file':'files'}</button>}</div><label className="field"><span>Published PDF access</span><select value={plan.visibility} onChange={e=>field('visibility',e.target.value)}><option value="public">Public safety document</option><option value="restricted">Staff/client sign-in required</option></select></label><p>Including a certificate selects restricted access. You can change the access above if this complete plan must be shared publicly.</p></>}
  </fieldset><aside className="ss-overview" aria-label="Plan contents"><img src="jgc-logo-transparent.png" alt="John Gordon Construction" /><p className="eyebrow">JOB {plan.jobNumber} · REVISION {plan.revision}</p><h3>Site Specific Health and Safety Plan</h3><strong>{plan.project}</strong><p>{plan.address}</p><h4>Included pages</h4><ol>{included.map(p=><li key={p.id}>{p.title}</li>)}</ol><h4>Attachments</h4>{plan.attachments.some(a=>a.included)?<ul>{plan.attachments.filter(a=>a.included).map(a=><li key={a.id}>{a.title}</li>)}</ul>:<p>No attachments selected.</p>}<p>Cover, contents and page numbers are generated with the PDF.</p></aside></div>
 </section>;
}
