import { useEffect, useMemo, useRef, useState, type Dispatch, type SetStateAction } from 'react';
import type { AppState, Job } from '../lib/estimator-data';
import { createSitePlan, createTaskPage, createStandardProcedure, addStandardSafetyContent, addStructuredSafetyContent, pageHasContent, safetyId, sitePlanDate, sitePlanErrors, sitePlanFileName, type SafetyPage, type SiteSpecificPlan } from '../lib/site-specific';
import { standardProcedureChoices } from '../lib/site-specific-content';
import { loadSafetyAttachments, uploadSafetyAttachment, readSafetyAttachment, publishSafetyPlan } from '../src/site-specific-api';
import { SafetyBlocksEditor, SafetyIllustrations } from './site-specific-blocks';
import { DocumentFields, DocumentText } from './site-specific-entry';
import './site-specific-builder.css';
type Props={job:Job;state:AppState;setState:Dispatch<SetStateAction<AppState>>;actor:string;workspaceSaved:boolean};
export function SiteSpecificBuilder({job,state,setState,actor,workspaceSaved}:Props) {
 const initial=useMemo(()=>createSitePlan(job,actor),[job.id,actor,job.jobNumber,job.project,job.portalJobName,job.portalAddress,job.portalCustomer,job.projectManager]);const plan=job.siteSpecific||initial;
 const [view,setView]=useState('Details'),[pageId,setPageId]=useState('scope'),[kind,setKind]=useState<SafetyPage['kind']>('custom'),[search,setSearch]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(false),[files,setFiles]=useState<File[]>([]),[pdfLink,setPdfLink]=useState('');
 const fileInput=useRef<HTMLInputElement>(null),mapInput=useRef<HTMLInputElement>(null),cachedPdf=useRef<{stamp:string;blob:Blob;pages:number}|null>(null),oldUrls=useRef<string[]>([]);
 const controls=useRef<HTMLDivElement>(null);
 const [procedureId,setProcedureId]=useState<string>(standardProcedureChoices[0].id),[mapFile,setMapFile]=useState<File|null>(null),[mapUrl,setMapUrl]=useState(''),[mapIssue,setMapIssue]=useState(''),[mapReload,setMapReload]=useState(0);
 const current=plan.pages.find(p=>p.id===pageId)||plan.pages[0],included=plan.pages.filter(p=>p.included);
 useEffect(()=>()=>{oldUrls.current.forEach(url=>URL.revokeObjectURL(url));},[]);
 useEffect(()=>{
  let active=true,url='';setMapUrl('');setMapIssue('');
  if(view==='Pages'&&current.id==='emergency'&&plan.hospitalMap)void readSafetyAttachment(job,plan.hospitalMap).then(blob=>{
   if(!active)return;url=URL.createObjectURL(blob);setMapUrl(url);
  }).catch(e=>{if(active)setMapIssue(e instanceof Error?e.message:'The hospital map preview could not load.');});
  return ()=>{active=false;if(url)URL.revokeObjectURL(url);};
 },[view,current.id,job.id,plan.hospitalMap?.id,mapReload]);
 function notice(text:string,bad=false){setMessage(text);setError(bad);}
 function change(update:(p:SiteSpecificPlan)=>SiteSpecificPlan){cachedPdf.current=null;setPdfLink('');setState(s=>({...s,jobs:s.jobs.map(j=>j.id===job.id?{...j,siteSpecific:{...update(j.siteSpecific||createSitePlan(j,actor)),updatedAt:new Date().toISOString()}}:j)}));}
 function field(key:keyof SiteSpecificPlan,value:string){change(p=>({...p,[key]:value}));}
 function pageChange(update:(p:SafetyPage)=>SafetyPage){change(p=>({...p,pages:p.pages.map(x=>x.id===current.id?update(x):x)}));}
 function move(id:string,delta:number){change(p=>{const pages=[...p.pages],index=pages.findIndex(x=>x.id===id),next=index+delta;if(next<0||next>=pages.length)return p;[pages[index],pages[next]]=[pages[next],pages[index]];return {...p,pages};});}
 function savePage(){if(!pageHasContent(current))return notice('Fill out this page before saving it to the library.',true);const saved={...structuredClone(current),id:safetyId(),savedAt:new Date().toISOString(),savedBy:actor,jobNumber:job.jobNumber};setState(s=>({...s,safetyLibrary:[saved,...(s.safetyLibrary||[])]}));notice('Page saved to the reusable library. The log keeps each saved version.');}
 function addPage(){const next=createTaskPage(kind);if(kind==='custom')next.fields=[];change(p=>({...p,pages:[...p.pages,next]}));setPageId(next.id);setView('Pages');scrollToPage();}
 function addStandardContent(){const result=addStandardSafetyContent(plan);if(!result.fieldsAdded&&!result.pagesAdded)return notice('Standard JGC content is already present. Your entered information is kept.');change(p=>addStandardSafetyContent(p).plan);notice(`Standard JGC content added to ${result.fieldsAdded} blank fields${result.pagesAdded?` and ${result.pagesAdded} missing pages`:''}. Your entered information and page choices are kept.`);}
 function addProcedure(){const next=createStandardProcedure(procedureId);change(p=>({...p,pages:[...p.pages,next]}));setPageId(next.id);setView('Pages');scrollToPage();notice('Standard procedure added. Review and adapt it for this site; save it to the library to reuse your completed version.');}
 function addStructure(){const result=addStructuredSafetyContent(plan);if(!result.blocksAdded&&!result.pagesAdded&&!result.fieldsAdded)return notice('Structured sections are already present.');change(p=>addStructuredSafetyContent(p).plan);notice('Tables, checklists and procedure sections added. Existing wording, page choices, files and published revisions are kept.');}
 async function uploadMap(){if(!mapFile)return;setBusy(true);try{
  if(!['image/png','image/jpeg','image/webp'].includes(mapFile.type))throw new Error('Choose a JPG, PNG or WebP hospital map image.');
  if(mapFile.size>20*1024*1024)throw new Error('The hospital map must be 20 MB or smaller.');
  const decoded=await createImageBitmap(mapFile);decoded.close();notice('Uploading the nearest hospital map…');
  const item=await uploadSafetyAttachment(job,mapFile);change(p=>({...p,hospitalMap:{...item,title:'Nearest hospital map',included:true},attachments:p.attachments.filter(a=>a.id!==item.id)}));
  setMapFile(null);if(mapInput.current)mapInput.current.value='';notice('Hospital map saved privately with this plan. It will appear in the Emergency response and evacuation section of the PDF.');
 }catch(e){notice(e instanceof Error?e.message:'Hospital map upload failed. Your selected image is kept for retry.',true);}finally{setBusy(false);}}
 async function sources(){setBusy(true);notice('Loading Portal documents…');try{const data=await loadSafetyAttachments(job);change(p=>{const selected=new Map(p.attachments.map(a=>[a.id,a]));const illustrationIds=new Set(p.pages.flatMap(page=>(page.illustrations||[]).map(i=>i.id)));const merged=data.items.filter(a=>a.id!==p.hospitalMap?.id&&!illustrationIds.has(a.id)).map(a=>({...a,included:selected.get(a.id)?.included||false}));return {...p,attachments:[...merged,...p.attachments.filter(a=>!merged.some(b=>b.id===a.id))]};});notice(data.warnings.length?data.warnings.join(' '):`${data.items.length} Portal documents loaded. Select what belongs in this plan.`,!!data.warnings.length);}catch(e){notice(e instanceof Error?e.message:'Documents could not be loaded.',true);}finally{setBusy(false);}}
 async function upload(){if(!files.length)return;setBusy(true);try{for(const [i,file] of files.entries()){notice(`Uploading supporting file ${i+1} of ${files.length}: ${file.name}`);const item=await uploadSafetyAttachment(job,file);change(p=>({...p,attachments:p.attachments.some(a=>a.id===item.id)?p.attachments:[...p.attachments,item]}));}setFiles([]);if(fileInput.current)fileInput.current.value='';notice('Supporting files saved privately. They will be included in the combined PDF when selected.');}catch(e){notice(e instanceof Error?e.message:'Upload failed. Your files are kept for retry.',true);}finally{setBusy(false);}}
 async function output(mode:'download'|'preview'|'publish') {
 const errors=sitePlanErrors(plan);if(errors.length)return notice('Complete: '+errors.join(', ')+'.',true);if(!workspaceSaved||!job.siteSpecific)return notice('Save the plan and wait for the workspace to finish syncing.',true);if(files.length||mapFile)return notice('Upload the selected supporting files and hospital map first.',true);
 let preview:Window|null=null;if(mode==='preview')preview=window.open('about:blank','_blank');setBusy(true);setPdfLink('');try{
  const stamp=plan.updatedAt;let built=cachedPdf.current;if(!built||built.stamp!==stamp){notice('Preparing the PDF…');const module=await import('../lib/site-specific-pdf');const logo=await fetch('jgc-logo-transparent.png');if(!logo.ok)throw new Error('The JGC logo could not load.');const generated=await module.buildSiteSpecificPdf({plan,logoBytes:new Uint8Array(await logo.arrayBuffer()),readAttachment:a=>readSafetyAttachment(job,a),progress:t=>notice(t)});built={stamp,...generated};cachedPdf.current=built;}
  if(mode==='publish'){notice('Publishing the completed PDF to this Job Board…');const published=await publishSafetyPlan(job,plan,built.blob);setState(s=>({...s,jobs:s.jobs.map(j=>j.id===job.id&&j.siteSpecific?.updatedAt===stamp?{...j,siteSpecific:{...j.siteSpecific,published}}:j)}));window.dispatchEvent(new CustomEvent('jgc-site-plan-published',{detail:{jobId:job.id}}));notice(`Revision ${plan.revision} published in the Job Board’s Site Specific section (${built.pages} pages).`);}
  else{const url=URL.createObjectURL(built.blob);oldUrls.current.push(url);while(oldUrls.current.length>3)URL.revokeObjectURL(oldUrls.current.shift()!);setPdfLink(url);if(mode==='preview'&&preview){preview.opener=null;preview.location.href=url;}else if(mode==='download'){const a=document.createElement('a');a.href=url;a.download=sitePlanFileName(plan);a.click();}notice(`${built.pages}-page PDF ready. Selected attachments are included in full.`);}
 }catch(e){preview?.close();notice(e instanceof Error?e.message:'The PDF could not be created. Your plan is kept.',true);}finally{setBusy(false);}
 }
 const library=(state.safetyLibrary||[]).filter(p=>`${p.title} ${p.kind} ${p.jobNumber}`.toLowerCase().includes(search.toLowerCase())).slice().sort((a,b)=>b.savedAt.localeCompare(a.savedAt));
 const pageIndex=view==='Details'?0:view==='Pages'?plan.pages.findIndex(p=>p.id===current.id)+1:plan.pages.length+1;
 const canOutput=!busy&&workspaceSaved&&!!job.siteSpecific&&!files.length&&!mapFile;
 function scrollToPage(){requestAnimationFrame(()=>controls.current?.scrollIntoView({block:'start'}));}
 function turnPage(delta:number){const target=Math.max(0,Math.min(plan.pages.length+1,pageIndex+delta));setSearch('');if(target===0)setView('Details');else if(target>plan.pages.length)setView('Attachments');else{setPageId(plan.pages[target-1].id);setView('Pages');}scrollToPage();}
 function addText(){pageChange(p=>({...p,fields:[...p.fields,{id:safetyId(),label:'Additional information',value:'',multiline:true}]}));}
 function addTable(){pageChange(p=>({...p,blocks:[...(p.blocks||[]),{type:'table',id:safetyId(),title:'Additional details',columns:[{id:'item',label:'Item',weight:1},{id:'details',label:'Details',weight:2},{id:'responsible',label:'Responsible person',weight:1}],rows:[{id:safetyId(),cells:{item:'',details:'',responsible:''}}]}]}));}
 const position=view==='Details'?'Cover':view==='Pages'?`Section ${pageIndex} of ${plan.pages.length}`:view==='Saved pages'?'Saved sections':'Supporting documents';
 const navigation=(bottom=false)=><div className="ss-page-navigation"><button type="button" className="button secondary" aria-label={bottom?'Previous page (bottom)':'Previous page'} disabled={busy||pageIndex===0} onClick={()=>turnPage(-1)}>← Previous</button><span>{position}</span><button type="button" className="button primary" aria-label={bottom?'Next page (bottom)':'Next page'} disabled={busy||pageIndex>plan.pages.length} onClick={()=>turnPage(1)}>Next →</button></div>;
 return <section className="panel ss-builder" aria-label="Site-specific plan builder">
  <div className="ss-reader-heading"><div><h2>Create Site Specific</h2><p>Fill in the page below. Blank entries stay in the form and are left out of the PDF.</p></div><details className="ss-output-menu"><summary>PDF &amp; publish</summary><div className="ss-output-options"><div className="ss-actions"><button type="button" className="button secondary" disabled={!canOutput} onClick={()=>void output('preview')}>Preview PDF</button><button type="button" className="button secondary" disabled={!canOutput} onClick={()=>void output('download')}>Download PDF</button></div><label className="field"><span>Published PDF access</span><select disabled={busy} value={plan.visibility} onChange={e=>field('visibility',e.target.value)}><option value="public">Public safety document</option><option value="restricted">Staff/client sign-in required</option></select></label><p>Including a certificate selects restricted access. You can change the access above if this complete plan must be shared publicly.</p><button type="button" className="button primary" disabled={!canOutput} onClick={()=>void output('publish')}>Publish to Job Board</button></div></details></div>
  <div className="ss-save-line"><span>{!plan.updatedAt?'Your entries save with this job.':workspaceSaved?'All plan changes saved':'Saving plan changes…'}{plan.published&&` · Published revision ${plan.published.revision}`}</span><button type="button" className="ss-text-button" disabled={busy} onClick={()=>{change(p=>p);notice('Plan saved to the job.');}}>Save plan</button></div>
  {message&&<p className={`ss-message${error?' error':''}`} role="status">{message}{pdfLink&&<> <a href={pdfLink} target="_blank" rel="noopener">Open PDF</a></>}</p>}
  <div ref={controls} className="ss-reader-controls">{navigation()}{view==='Pages'&&<label className="ss-include-page"><input type="checkbox" aria-label="Include this page" checked={current.included} disabled={busy} onChange={e=>{const included=e.target.checked;pageChange(p=>({...p,included}));}} /><span>Include this page</span>{!current.included&&<small>Excluded from the PDF</small>}</label>}{view==='Details'&&<p className="ss-page-hint">Start with the cover. Click a heading or field to edit it.</p>}</div>
  <div className="ss-paper-stage"><fieldset className="ss-paper" data-page-id={view==='Pages'?current.id:view==='Details'?'cover':view==='Attachments'?'attachments':'library'} disabled={busy}>
   <header className="ss-letterhead"><img src="jgc-logo-transparent.png" alt="John Gordon Construction" /><span>Job {plan.jobNumber} · Rev {plan.revision}</span><strong>JOHN GORDON CONSTRUCTION</strong></header>
   {view==='Details'&&<div className="ss-cover"><div className="ss-cover-title"><span>SITE SPECIFIC</span><h3>Health and Safety Plan</h3></div><label className="field ss-cover-project"><span>Project</span><DocumentText aria-label="Project" value={plan.project} maxLength={240} placeholder="Project name" onChange={e=>field('project',e.target.value)} /></label><label className="field"><span>Site address</span><DocumentText aria-label="Site address" value={plan.address} maxLength={700} placeholder="Site address" onChange={e=>field('address',e.target.value)} /></label><div className="ss-cover-details">{([['jobNumber','Job number'],['client','Client / owner'],['preparedBy','Prepared by'],['planDate','Plan date'],['revision','Revision']] as const).map(([key,label])=><label className="field" key={key}><span>{label}</span><input readOnly={key==='jobNumber'} type={key==='planDate'?'date':'text'} maxLength={240} value={plan[key]} onChange={e=>field(key,e.target.value)} /></label>)}</div></div>}
   {view==='Pages'&&<><div className="ss-document-title"><span>{pageIndex}.</span><DocumentText aria-label="Page title" value={current.title} maxLength={200} onChange={e=>{const title=e.target.value;pageChange(p=>({...p,title}));}} /></div><div key={current.id} className="ss-document-content"><SafetyBlocksEditor blocks={current.blocks||[]} onChange={blocks=>pageChange(p=>({...p,blocks}))}/><DocumentFields fields={current.fields} onChange={fields=>pageChange(p=>({...p,fields}))}/>
{current.id==='emergency'&&<div className="ss-hospital-map"><h4>Nearest hospital map</h4><p>Upload a map or route screenshot for the hospital entered above. Add the hospital address and directions, and confirm the route for this site.</p><label className="field"><span>Hospital map photo</span><input ref={mapInput} type="file" accept=".jpg,.jpeg,.png,.webp" onChange={e=>setMapFile(e.target.files?.[0]||null)} /></label>{mapFile&&<button type="button" className="button secondary" onClick={()=>void uploadMap()}>Upload hospital map</button>}{plan.hospitalMap&&<><p>{plan.hospitalMap.fileName}</p><label className="ss-map-choice"><input type="checkbox" checked={plan.hospitalMap.included} onChange={e=>{const included=e.target.checked;change(p=>({...p,hospitalMap:p.hospitalMap?{...p.hospitalMap,included}:undefined}));}} /><span>Include hospital map in PDF</span></label>{mapUrl&&<img src={mapUrl} alt="Nearest hospital map preview" onError={()=>setMapIssue('This map image could not be displayed. Replace it with a JPG, PNG or WebP image.')} />}{mapIssue&&<p role="alert">{mapIssue} <button type="button" className="button secondary" onClick={()=>setMapReload(n=>n+1)}>Retry map preview</button></p>}<p>The map is included in the emergency section when that page is switched on. Its original file stays separate from the PDF.</p></>}</div>}
    {(current.id==='logistics'||!!current.illustrations?.length)&&<SafetyIllustrations job={job} items={current.illustrations||[]} onChange={illustrations=>pageChange(p=>({...p,illustrations}))} onBusy={setBusy} notice={notice}/>}<div className="ss-add-to-page"><span>Add to this page</span><button type="button" onClick={addText}>+ Text</button><button type="button" onClick={addTable}>+ Table</button>{current.id!=='logistics'&&!current.illustrations?.length&&<details className="ss-inline-upload"><summary>+ Map or photo</summary><SafetyIllustrations job={job} items={current.illustrations||[]} onChange={illustrations=>pageChange(p=>({...p,illustrations}))} onBusy={setBusy} notice={notice}/></details>}<button type="button" onClick={savePage}>Save page to library</button></div></div></>}
{view==='Saved pages'&&<><h3>Saved sections</h3><button type="button" className="button secondary" onClick={()=>{setView('Pages');scrollToPage();}}>Back to plan</button><p>Each saved task, procedure or risk page is kept as a separate version, newest first. Reusing it creates an editable copy in this job’s plan.</p><label className="field"><span>Find saved pages</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Title, type or job number" /></label>{library.length?library.map(p=><details className="ss-library" key={p.id}><summary>{p.title}<small>{p.kind} · Job {p.jobNumber} · {new Date(p.savedAt).toLocaleDateString('en-CA',{timeZone:'America/Toronto'})}</small></summary><p>Saved by {p.savedBy}</p>{p.blocks?.map(b=><p key={b.id}><strong>{b.title}</strong> · {b.rows.length} {b.type==='steps'?'steps':'rows'}</p>)}{p.fields.map(f=><div key={f.id}><strong>{f.label}</strong><p className="ss-preserve">{f.value||'Not entered'}</p></div>)}<button type="button" className="button secondary" onClick={()=>{const copy={...structuredClone(p),id:safetyId(),included:true,illustrations:p.jobNumber===job.jobNumber?structuredClone(p.illustrations):[]};change(x=>({...x,pages:[...x.pages,copy]}));setPageId(copy.id);setView('Pages');scrollToPage();notice('Saved page copied into this plan. Edit it for this site. Maps and photos from another job are kept with that job; add this site’s images.');}}>Use in this plan</button></details>):<p>No saved pages yet. Fill in a plan page, then choose Save page to library at the bottom of that page.</p>}</>}
   {view==='Attachments'&&<><h3>Supporting documents</h3><p>Select Portal certificates, this job’s JSAs, the complete JGC policy and other documents. Every selected file is appended in full to the exported PDF.</p><button type="button" className="button secondary" onClick={()=>void sources()}>Load Portal documents</button><label className="field"><span>Find supporting documents</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Employee, policy, JSA or file name" /></label>{plan.attachments.filter(a=>`${a.title} ${a.category} ${a.kind}`.toLowerCase().includes(search.toLowerCase())).map(a=><label className="ss-attachment" key={a.id}><input type="checkbox" checked={a.included} onChange={e=>{const checked=e.target.checked;change(p=>({...p,visibility:checked&&a.kind==='certificate'?'restricted':p.visibility,attachments:p.attachments.map(x=>x.id===a.id?{...x,included:checked}:x)}));}} /><span><strong>{a.title}</strong><small>{a.kind==='certificate'?'Portal certificate':a.category==='jgc-policy'?'Complete JGC policy':a.category==='jsa'?'Job safety analysis': 'Job document'}{a.expiryDate&&` · ${a.expiryDate<sitePlanDate()?'Expired':'Expires'} ${a.expiryDate}`}</small></span></label>)}<div className="ss-upload"><label className="field"><span>Additional PDFs, forms or photos</span><input ref={fileInput} type="file" accept=".pdf,.jpg,.jpeg,.png,.webp" multiple onChange={e=>setFiles(Array.from(e.target.files||[]))} /></label><p>Originals are saved privately and kept separately from the combined PDF. Each file can be up to 20 MB.</p>{files.length>0&&<button type="button" className="button secondary" onClick={()=>void upload()}>Upload {files.length} supporting {files.length===1?'file':'files'}</button>}</div></>}
   <footer className="ss-paper-footer"><span>JGC · Job {plan.jobNumber} · Revision {plan.revision}</span><span>{position}</span></footer>
  </fieldset></div>
  <div className="ss-reader-bottom">{navigation(true)}<details className="ss-plan-options"><summary>More plan options</summary><fieldset className="ss-options-fields" disabled={busy}><div className="ss-grid"><div><label className="field"><span>New page type</span><select value={kind} onChange={e=>setKind(e.target.value as SafetyPage['kind'])}><option value="custom">Blank page</option><option value="task">Task</option><option value="procedure">Procedure</option><option value="risk">Risk assessment</option></select></label><button type="button" className="button secondary" onClick={addPage}>Add page</button></div><div><label className="field"><span>Procedure template</span><select value={procedureId} onChange={e=>setProcedureId(e.target.value)}>{standardProcedureChoices.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label><button type="button" className="button secondary" onClick={addProcedure}>Add procedure</button></div></div><div className="ss-actions">{view==='Pages'&&<><button type="button" className="button secondary" disabled={pageIndex===1} onClick={()=>move(current.id,-1)}>Move this page earlier</button><button type="button" className="button secondary" disabled={pageIndex===plan.pages.length} onClick={()=>move(current.id,1)}>Move this page later</button></>}<button type="button" className="button secondary" onClick={()=>{setView('Saved pages');setSearch('');scrollToPage();}}>Saved pages</button><button type="button" className="button secondary" onClick={addStructure}>Add structured sections</button><button type="button" className="button secondary" onClick={addStandardContent}>Add standard JGC content</button></div><p>The last two options add missing tables or wording to older plans. Existing entries and files are kept.</p></fieldset></details></div>
 </section>;
}
