import { useEffect, useRef, useState } from 'react';
import type { Job } from '../lib/estimator-data';
import { safetyId, type SafetyBlock, type SafetyIllustration } from '../lib/site-specific';
import { readSafetyAttachment, uploadSafetyAttachment } from '../src/site-specific-api';

export function SafetyBlocksEditor({blocks,onChange}:{blocks:SafetyBlock[];onChange:(blocks:SafetyBlock[])=>void}) {
 function change(id:string,update:(b:SafetyBlock)=>SafetyBlock){onChange(blocks.map(b=>b.id===id?update(b):b));}
 function move(block:SafetyBlock,index:number,delta:number){const rows=[...block.rows],next=index+delta;if(next<0||next>=rows.length)return;[rows[index],rows[next]]=[rows[next],rows[index]];change(block.id,b=>({...b,rows} as SafetyBlock));}
 return <div className="ss-blocks">{blocks.map(block=><section className="ss-block" key={block.id} aria-label={block.title}>
  <h4>{block.title}</h4>
  {block.type==='table'&&<>{block.rows.map((row,index)=><fieldset className="ss-input-row" key={row.id}><legend>Row {index+1}</legend><div className="ss-row-grid" style={{gridTemplateColumns:`repeat(${Math.min(block.columns.length,3)}, minmax(0,1fr))`}}>{block.columns.map(col=><label className="field" key={col.id}><span>{col.label}</span><textarea rows={col.weight&&col.weight>2?4:2} maxLength={20000} aria-label={`${block.title} row ${index+1} ${col.label}`} value={row.cells[col.id]||''} onChange={e=>{const value=e.target.value;change(block.id,b=>b.type==='table'?{...b,rows:b.rows.map(r=>r.id===row.id?{...r,cells:{...r.cells,[col.id]:value}}:r)}:b);}} /></label>)}</div><RowActions label={`${block.title} row ${index+1}`} index={index} count={block.rows.length} move={delta=>move(block,index,delta)} remove={()=>change(block.id,b=>({...b,rows:b.rows.filter(r=>r.id!==row.id)} as SafetyBlock))} /></fieldset>)}<button type="button" className="button secondary" onClick={()=>change(block.id,b=>b.type==='table'?{...b,rows:[...b.rows,{id:safetyId(),cells:Object.fromEntries(b.columns.map(c=>[c.id,'']))}]}:b)}>Add row to {block.title}</button></>}
  {block.type==='questions'&&block.rows.map(row=><div className="ss-question" key={row.id}><label className="field"><span>{row.label}</span><select aria-label={row.label} value={row.value} onChange={e=>{const value=e.target.value;change(block.id,b=>b.type==='questions'?{...b,rows:b.rows.map(r=>r.id===row.id?{...r,value}:r)}:b);}}><option value="">Not assessed</option>{row.options.map(v=><option key={v}>{v}</option>)}</select></label><label className="field"><span>Site notes</span><input aria-label={`${row.label} notes`} maxLength={2000} value={row.notes} onChange={e=>{const notes=e.target.value;change(block.id,b=>b.type==='questions'?{...b,rows:b.rows.map(r=>r.id===row.id?{...r,notes}:r)}:b);}} /></label></div>)}
  {block.type==='checklist'&&<><p>Choose each requirement and add its task, type, location or other details.</p><div className="ss-check-grid">{block.rows.map((row,index)=><fieldset className="ss-input-row" key={row.id}><legend>{row.label||`Equipment ${index+1}`}</legend><label className="field"><span>Item</span><input aria-label={`Equipment ${index+1} name`} maxLength={160} value={row.label} onChange={e=>{const label=e.target.value;change(block.id,b=>b.type==='checklist'?{...b,rows:b.rows.map(r=>r.id===row.id?{...r,label}:r)}:b);}} /></label><label className="field"><span>Requirement</span><select aria-label={`${row.label} requirement`} value={row.value} onChange={e=>{const value=e.target.value;change(block.id,b=>b.type==='checklist'?{...b,rows:b.rows.map(r=>r.id===row.id?{...r,value}:r)}:b);}}><option value="">Not assessed</option>{['Required','Task specific','Not required'].map(v=><option key={v}>{v}</option>)}</select></label><label className="field"><span>Task / equipment details</span><textarea rows={2} aria-label={`${row.label} details`} maxLength={4000} value={row.notes} onChange={e=>{const notes=e.target.value;change(block.id,b=>b.type==='checklist'?{...b,rows:b.rows.map(r=>r.id===row.id?{...r,notes}:r)}:b);}} /></label><button type="button" className="button secondary" aria-label={`Remove equipment ${index+1}`} onClick={()=>change(block.id,b=>b.type==='checklist'?{...b,rows:b.rows.filter(r=>r.id!==row.id)}:b)}>Remove</button></fieldset>)}</div><button type="button" className="button secondary" onClick={()=>change(block.id,b=>b.type==='checklist'?{...b,rows:[...b.rows,{id:safetyId(),label:'Additional equipment',value:'',notes:''}]}:b)}>Add equipment requirement</button></>}
  {block.type==='steps'&&<>{block.rows.map((row,index)=><fieldset className="ss-input-row" key={row.id}><legend>Step {index+1}</legend><label className="field"><span>Step heading</span><input aria-label={`${block.title} step ${index+1} heading`} maxLength={200} value={row.title} onChange={e=>{const title=e.target.value;change(block.id,b=>b.type==='steps'?{...b,rows:b.rows.map(r=>r.id===row.id?{...r,title}:r)}:b);}} /></label><label className="field"><span>Instructions (one point per line)</span><textarea rows={5} aria-label={`${block.title} step ${index+1} instructions`} maxLength={20000} value={row.body} onChange={e=>{const body=e.target.value;change(block.id,b=>b.type==='steps'?{...b,rows:b.rows.map(r=>r.id===row.id?{...r,body}:r)}:b);}} /></label><RowActions label={`${block.title} step ${index+1}`} index={index} count={block.rows.length} move={delta=>move(block,index,delta)} remove={()=>change(block.id,b=>({...b,rows:b.rows.filter(r=>r.id!==row.id)} as SafetyBlock))} /></fieldset>)}<button type="button" className="button secondary" onClick={()=>change(block.id,b=>b.type==='steps'?{...b,rows:[...b.rows,{id:safetyId(),title:'',body:''}]}:b)}>Add step to {block.title}</button></>}
 </section>)}</div>;
}
function RowActions({label,index,count,move,remove}:{label:string;index:number;count:number;move:(delta:number)=>void;remove:()=>void}) {
 return <div className="ss-row-actions"><button type="button" disabled={index===0} aria-label={`Move ${label} up`} onClick={()=>move(-1)}>Move up</button><button type="button" disabled={index===count-1} aria-label={`Move ${label} down`} onClick={()=>move(1)}>Move down</button><button type="button" aria-label={`Remove ${label}`} onClick={remove}>Remove</button></div>;
}

function IllustrationPreview({job,item}:{job:Job;item:SafetyIllustration}) {
 const [url,setUrl]=useState(''),[error,setError]=useState(''),[retry,setRetry]=useState(0);
 useEffect(()=>{let active=true,url='';setError('');setUrl('');void readSafetyAttachment(job,item).then(blob=>{if(active){url=URL.createObjectURL(blob);setUrl(url);}}).catch(e=>{if(active)setError(e instanceof Error?e.message:'Image unavailable.');});return()=>{active=false;if(url)URL.revokeObjectURL(url);};},[job.id,item.id,retry]);
 return <>{url&&<img src={url} alt={`${item.title} preview`} onError={()=>setError('This image cannot be displayed. Upload a JPG, PNG or WebP image.')} />}{error&&<p role="alert">{error} <button type="button" onClick={()=>setRetry(n=>n+1)}>Retry preview</button></p>}</>;
}
export function SafetyIllustrations({job,items,onChange,onBusy,notice}:{job:Job;items:SafetyIllustration[];onChange:(items:SafetyIllustration[])=>void;onBusy:(busy:boolean)=>void;notice:(text:string,bad?:boolean)=>void}) {
 const input=useRef<HTMLInputElement>(null),pending=useRef<File|null>(null),[failed,setFailed]=useState(false);
 async function upload(file:File){pending.current=file;setFailed(false);onBusy(true);try{
  if(!['image/png','image/jpeg','image/webp'].includes(file.type))throw new Error('Choose a JPG, PNG or WebP plan image.');
  if(file.size>20*1024*1024)throw new Error('The plan image must be 20 MB or smaller.');
  const decoded=await createImageBitmap(file);const pixels=decoded.width*decoded.height;decoded.close();if(pixels>40000000)throw new Error('Reduce this image to 40 megapixels or smaller.');
  const item=await uploadSafetyAttachment(job,file);onChange([...items,{...item,caption:''}]);pending.current=null;if(input.current)input.current.value='';notice('Plan image saved privately. It will have its own full-size page in this section of the PDF.');
 }catch(e){setFailed(true);notice(e instanceof Error?e.message:'Plan image upload failed.',true);}finally{onBusy(false);}}
 return <section className="ss-block ss-plan-images" aria-label="Section maps and photos"><h4>Section maps and photos</h4><p>Add site plans, marked-up drawings, access routes or other photos. Each included image gets a full page with its caption in this section.</p><label className="field"><span>Section map or photo</span><input ref={input} type="file" accept=".jpg,.jpeg,.png,.webp" onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file);}} /></label>{failed&&pending.current&&<button type="button" className="button secondary" onClick={()=>{if(pending.current)void upload(pending.current);}}>Retry plan image upload</button>}{items.map((item,index)=><div className="ss-plan-image" key={item.id}><label className="field"><span>Image title</span><input aria-label={`Image ${index+1} title`} maxLength={200} value={item.title} onChange={e=>onChange(items.map(i=>i.id===item.id?{...i,title:e.target.value}:i))} /></label><label className="field"><span>Caption / legend</span><textarea aria-label={`Image ${index+1} caption`} rows={3} maxLength={4000} value={item.caption||''} onChange={e=>onChange(items.map(i=>i.id===item.id?{...i,caption:e.target.value}:i))} /></label><label className="ss-map-choice"><input type="checkbox" checked={item.included} onChange={e=>onChange(items.map(i=>i.id===item.id?{...i,included:e.target.checked}:i))} />Include {item.fileName} in PDF</label><IllustrationPreview job={job} item={item} /><button type="button" className="button secondary" onClick={()=>onChange(items.filter(i=>i.id!==item.id))}>Remove {item.fileName} from this section</button></div>)}</section>;
}
