const {test,expect}=require('@playwright/test'),fs=require('node:fs'),path=require('node:path'),ts=require('../estimating-app/node_modules/typescript');
const {PDFDocument,StandardFonts}=require('../estimating-app/node_modules/pdf-lib');
const {zlibSync,zipSync,strToU8}=require('../estimating-app/node_modules/fflate');
const cache={};function load(name){if(cache[name])return cache[name];const m={exports:{}};Function('exports','module','require',ts.transpileModule(fs.readFileSync(path.resolve(__dirname,'../estimating-app/lib/'+name+'.ts'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(m.exports,m,n=>n.startsWith('.')?load(n.replace(/^\.\//,'')):require('../estimating-app/node_modules/'+n));return cache[name]=m.exports;}
function streamPdf(data,filter='/Filter /FlateDecode',extra=''){return new Uint8Array(Buffer.concat([Buffer.from(`%PDF-1.7\n1 0 obj\n<< /Length ${data.length} ${filter} ${extra} >>\nstream\n`),data,Buffer.from('\nendstream\nendobj\n%%EOF')]));}
test('real multi-page PDF object streams remain readable within the budget',async()=>{const doc=await PDFDocument.create(),font=await doc.embedFont(StandardFonts.Helvetica);for(let n=0;n<195;n++)doc.addPage().drawText('JGC POLICY PAGE '+(n+1),{font});const budget=load('pdf-input-budget').preflightPdf(await doc.save());expect(budget.objects).toBeGreaterThan(195);expect(budget.decodedBytes).toBeLessThan(80*1024*1024);});
test('PDF compressed stream expansion is stopped before PDF parser allocation',()=>{const bytes=streamPdf(zlibSync(new Uint8Array(17*1024*1024).fill(32)));expect(bytes.length).toBeLessThan(50_000);expect(()=>load('pdf-input-budget').preflightPdf(bytes)).toThrow('too complex');});
test('PDF filter names hidden behind comments or hex name escapes cannot bypass expansion budget',()=>{const compressed=zlibSync(new Uint8Array(17*1024*1024).fill(32));for(const filter of ['/Filter % comment\n /FlateDecode','/Fi#6cter /FlateDecode','/Filter [/FlateDecode]'])expect(()=>load('pdf-input-budget').preflightPdf(streamPdf(compressed,filter))).toThrow('too complex');});
test('aggregate decoded PDF budget applies across separate attachments',()=>{const p=load('pdf-input-budget'),budget={decodedBytes:0,objects:0},bytes=streamPdf(zlibSync(new Uint8Array(15*1024*1024).fill(32)));for(let n=0;n<5;n++)p.preflightPdf(bytes,budget);expect(()=>p.preflightPdf(bytes,budget)).toThrow('too complex');});
test('PDF image dimensions and unknown decoder chains fail before decoding',()=>{const p=load('pdf-input-budget');expect(()=>p.preflightPdf(streamPdf(Buffer.from([1,2,3]),'', '/Subtype /Image /Width 100000 /Height 100000'))).toThrow('image is too large');expect(()=>p.preflightPdf(streamPdf(Buffer.from([1,2,3]),'/Filter [/ASCII85Decode /FlateDecode]'))).toThrow('too complex');});
test('hostile image headers are refused before allocating decoded pixels',()=>{const b=load('document-budget'),png=new Uint8Array(24);png[0]=0x89;png[1]=0x50;new DataView(png.buffer).setUint32(16,100000);new DataView(png.buffer).setUint32(20,100000);const size=b.imageDimensions(png,'image/png');expect(()=>b.imageBudget(size.width,size.height)).toThrow('too large');});
test('workbook row and cell budgets stop XML object expansion',()=>{const w=load('material-price-workbook'),rows='<row><c r="A1" t="inlineStr"><is><t>item</t></is></c></row>'.repeat(25_001),file=zipSync({'[Content_Types].xml':strToU8('<Types/>'),'xl/worksheets/sheet1.xml':strToU8('<worksheet><sheetData>'+rows+'</sheetData></worksheet>')});expect(()=>w.parseMaterialPriceWorkbook(file)).toThrow('too large');});
test('timeout stops document work and exposes no partial result',async()=>{let stopped=false;await expect(load('document-budget').documentDeadline(new Promise(()=>{}),10,()=>{stopped=true;})).rejects.toThrow('took too long');expect(stopped).toBe(true);});
