const {test,expect}=require('@playwright/test');
const fs=require('node:fs'),path=require('node:path'),ts=require('../estimating-app/node_modules/typescript');
const {PDFDocument,StandardFonts,rgb,degrees,PDFName}=require('../estimating-app/node_modules/pdf-lib');
const cache={};function load(name){if(cache[name])return cache[name];const m={exports:{}};Function('exports','module','require',ts.transpileModule(fs.readFileSync(path.resolve(__dirname,'../estimating-app/lib/'+name+'.ts'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(m.exports,m,n=>n.startsWith('.')?load(n.replace(/^\.\//,'')):require('../estimating-app/node_modules/'+n));return cache[name]=m.exports;}
async function sample(count=2){const pdf=await PDFDocument.create(),font=await pdf.embedFont(StandardFonts.Helvetica);for(let n=1;n<=count;n++){const p=pdf.addPage([612,792]);p.drawText('JGC TEST DRAWING PAGE '+n,{x:70,y:700,size:18,font});p.drawLine({start:{x:70,y:600},end:{x:370,y:600},thickness:2,color:rgb(0,0,0)});if(n===2){p.setCropBox(30,40,540,700);p.setRotation(degrees(90));}}return Buffer.from(await pdf.save());}
function state(){const s=load('estimator-data').createDefaultState();s.clients=[];s.quotes=[];s.priceBook=[];s.jobs=[{id:'job',jobNumber:'26999',quoteId:'',clientId:'',project:'Drawing review',status:'Active',portalJobId:'portal-job',acceptedRevenue:0,originalCostBudget:0,approvedRevenueChanges:0,approvedCostChanges:0,estimateToComplete:0,acceptedAt:'2026-10-01',costs:[],notes:''}];return s;}
async function setup(page,store){await page.route('**/api/**',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({state:state(),jobs:[],actuals:[],rows:[],saved:true})}));await page.route('https://drawings.example.test/**',async r=>{const req=r.request(),u=new URL(req.url());if(u.pathname.startsWith('/storage/')){if(req.method()==='POST'){store.uploaded=true;return r.fulfill({status:200,contentType:'application/json',body:'{"Key":"ok"}'});}return r.fulfill({status:200,contentType:'application/pdf',body:store.bytes});}if(u.pathname.endsWith('/job_drawings')){if(req.method()==='GET')return r.fulfill({status:200,contentType:'application/json',body:JSON.stringify([store.row])});if(req.method()==='PATCH'){const v=req.postDataJSON();if(u.searchParams.get('revision')!=='eq.'+store.row.revision)return r.fulfill({status:200,contentType:'application/json',body:'null'});store.row={...store.row,...v,updated_at:new Date().toISOString()};store.saves++;return r.fulfill({status:200,contentType:'application/json',body:JSON.stringify(store.row)});}if(req.method()==='POST'){const v=req.postDataJSON();store.row={...store.row,...v,object_path:v.id+'/original.pdf'};return r.fulfill({status:201,contentType:'application/json',body:JSON.stringify(store.row)});}}return r.fulfill({status:404,body:'{}'});});await page.goto('/estimating/index.html?dev=1&view=jobs&job=26999');await expect(page.locator('.job-detail-page')).toContainText('26999');await page.evaluate(()=>{window.__drawingBaselineWidth=document.documentElement.scrollWidth;window.createJgcSupabaseClient=()=>window.supabase.createClient('https://drawings.example.test','public-test-key',{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});});await page.getByRole('tab',{name:'Drawings',exact:true}).click();await expect(page.getByLabel('Select drawing').locator('option')).toHaveCount(2);await page.getByLabel('Select drawing').selectOption(store.row.id);await expect(page.locator('.drawing-overlay')).toBeVisible();expect(await page.locator('.drawing-sheet canvas').evaluate(c=>c.width)).toBeGreaterThan(0);}
async function store(){return{bytes:await sample(),saves:0,row:{id:'aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa',job_id:'job',title:'Architectural drawing',file_name:'original.pdf',object_path:'aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa/original.pdf',revision:1,content:load('drawing-model').emptyDrawing(),created_at:'2026-10-01',updated_at:'2026-10-01'}};}
async function drag(page,x=70,y=90,dx=130,dy=0){if(await page.getByRole('button',{name:'Set scale',exact:true}).count()&&await page.getByRole('button',{name:'Set scale',exact:true}).getAttribute('aria-pressed')==='true'){await distance(page,x,y,dx,dy);return;}await page.locator('.drawing-overlay').evaluate(svg=>scrollTo(0,scrollY+svg.getBoundingClientRect().top-240));const b=await page.locator('.drawing-overlay').boundingBox();await page.mouse.move(b.x+x,b.y+y);await page.mouse.down();await page.mouse.move(b.x+x+dx,b.y+y+dy,{steps:5});await page.mouse.up();}
async function distance(page,x=70,y=150,dx=130,dy=0){await page.locator('.drawing-overlay').evaluate(svg=>scrollTo(0,scrollY+svg.getBoundingClientRect().top-240));const b=await page.locator('.drawing-overlay').boundingBox();await page.mouse.click(b.x+x,b.y+y);await page.mouse.move(b.x+x+dx,b.y+y+dy);await page.mouse.click(b.x+x+dx,b.y+y+dy);}
async function text(page,value='As-built: conduit relocated'){await page.getByRole('button',{name:'Edit',exact:true}).click();await page.getByRole('button',{name:'Text',exact:true}).click();await page.locator('.drawing-overlay').evaluate(svg=>scrollTo(0,scrollY+svg.getBoundingClientRect().top-240));const b=await page.locator('.drawing-overlay').boundingBox();await page.mouse.click(b.x+100,b.y+120);await page.getByLabel('Edit drawing comment',{exact:true}).fill(value);}
async function pdfTexts(bytes){const lib=await import(require('node:url').pathToFileURL(path.resolve(__dirname,'../estimating-app/node_modules/pdfjs-dist/legacy/build/pdf.mjs')).href),task=lib.getDocument({data:new Uint8Array(bytes),disableWorker:true}),pdf=await task.promise,text=[];for(let n=1;n<=pdf.numPages;n++){const p=await pdf.getPage(n),content=await p.getTextContent();text.push(content.items.map(i=>i.str).join(' '));}await task.destroy();return text;}

test('replacing scale preserves legacy measurement values and rejects invalid calibrations',()=>{
 const m=load('drawing-model'),previous=m.calibrate([{x:0,y:0},{x:100,y:0}],10,'ft-in'),next=m.calibrate([{x:0,y:0},{x:100,y:0}],6096,'mm');next.displayUnit='ft-in';
 const mark={id:'legacy',kind:'distance',page:1,points:[{x:0,y:0},{x:100,y:0}],color:'#d62828',text:'',author:'Test',createdAt:'2026-10-02T12:00:00Z',layer:'Review'},other={...mark,id:'other',page:2};
 const content={version:1,marks:[mark,other],scales:{'1':previous,'2':previous}},replaced=m.replacePageScale(content,1,next);
 expect(replaced.scales['1'].reference).toEqual(next.reference);expect(m.measurement(replaced.marks[0],next)).toBe('10 ft 0 in');expect(m.measurement({...mark,calibration:{unit:'mm',unitsPerPoint:60.96}},next)).toBe('20 ft 0 in');
 expect(replaced.marks[1]).toBe(other);expect(content.marks[0].calibration).toBeUndefined();expect(m.validateContent(JSON.parse(JSON.stringify(replaced)))).toEqual(replaced);
 for(const unitsPerPoint of [0,-1,Infinity])expect(()=>m.validateContent({...replaced,marks:[{...replaced.marks[0],calibration:{unit:'ft',unitsPerPoint}}]})).toThrow('calibration');
});
test('batch page reorder preserves source order, handles end drops and ignores selected targets',()=>{
 const {reorderDrawingPages:move}=load('drawing-model'),order=[1,2,3,4,5,6,7];
 expect(move(order,[5,1,3,4],null)).toEqual([2,6,7,1,3,4,5]);expect(move(order,[3,4,5],1)).toEqual([3,4,5,1,2,6,7]);expect(move(order,[1,3],6,true)).toEqual([2,4,5,6,1,3,7]);
 expect(move(order,[2,3],3)).toEqual(order);expect(move(order,order,null)).toEqual(order);expect(order).toEqual([1,2,3,4,5,6,7]);
});

test('scale replacement shows one reference and preserves measurements through shared save and export',async({page},info)=>{
 const s=await store();await setup(page,s);await page.getByRole('button',{name:'Measure',exact:true}).click();await distance(page,70,90,130);await page.getByLabel('Known length',{exact:true}).fill('10');await page.getByRole('button',{name:'Apply page scale'}).click();await distance(page,70,150,130);await expect.poll(()=>s.row.content.marks.length).toBe(1);
 await page.getByRole('button',{name:'Replace scale',exact:true}).click();await expect(page.locator('.drawing-scale-reference')).toHaveCount(0);await distance(page,70,250,130);await expect(page.locator('.drawing-scale-reference')).toHaveCount(1);await expect(page.locator('.drawing-scale-reference')).toContainText('enter the known length');await page.getByLabel('Known length',{exact:true}).fill('20');await page.getByRole('button',{name:'Apply page scale'}).click();
 await expect(page.locator('.drawing-scale-reference')).toHaveCount(1);await expect(page.locator('.drawing-scale-reference')).toContainText('20 ft 0 in');await expect(page.locator('.drawing-dimension-label')).toHaveText(['10 ft 0 in']);await distance(page,70,330,130);await expect.poll(()=>s.row.content.marks.length).toBe(2);await expect(page.locator('.drawing-dimension-label')).toHaveText(['10 ft 0 in','20 ft 0 in']);
 const saved=JSON.stringify(s.row.content);await page.getByRole('button',{name:'Replace scale',exact:true}).click();await distance(page,100,200,130);await page.getByRole('button',{name:'Cancel scale replacement',exact:true}).click();expect(JSON.stringify(s.row.content)).toBe(saved);await expect(page.locator('.drawing-scale-reference')).toHaveCount(1);
 await page.getByRole('button',{name:'Refresh drawings',exact:true}).click();await expect(page.locator('.drawing-scale-reference')).toHaveCount(1);await expect(page.locator('.drawing-dimension-label')).toHaveText(['10 ft 0 in','20 ft 0 in']);
 const pending=page.waitForEvent('download');await page.getByRole('button',{name:'Download marked PDF',exact:true}).click();await(await pending).saveAs(info.outputPath('different-detail-scales.pdf'));const exported=await pdfTexts(fs.readFileSync(info.outputPath('different-detail-scales.pdf')));expect(exported[0]).toContain('10 ft 0 in');expect(exported[0]).toContain('20 ft 0 in');await page.locator('.drawing-workspace').screenshot({path:info.outputPath('replaced-scale.png')});
});

for(const theme of ['light','dark'])for(const width of [390,1440])test(`organizer fills the screen and closes safely ${theme} ${width}`,async({page},info)=>{
 await page.setViewportSize({width,height:1000});await page.addInitScript(t=>localStorage.setItem('jgcPortalTheme',t),theme);const s=await store();s.bytes=await sample(7);await setup(page,s);await page.getByRole('button',{name:'Organize pages',exact:true}).click();
 const dialog=page.getByRole('dialog',{name:'Organize pages',exact:true});await expect(dialog).toBeVisible();const box=await dialog.boundingBox();expect(box.x).toBe(0);expect(box.y).toBe(0);expect(box.width).toBe(width);expect(box.height).toBe(1000);await expect(dialog.getByRole('listitem')).toHaveCount(7);
 await dialog.getByLabel('Select multiple', {exact:true}).check();await dialog.getByRole('button',{name:'Page 3',exact:true}).click();await expect(dialog.getByRole('button',{name:'Page 1',exact:true})).toHaveAttribute('aria-pressed','true');await expect(dialog.getByRole('button',{name:'Page 3',exact:true})).toHaveAttribute('aria-pressed','true');
 await dialog.screenshot({path:info.outputPath(`organizer-${theme}-${width}.png`)});expect(await dialog.evaluate(d=>d.scrollWidth)).toBeLessThanOrEqual(width);await page.keyboard.press('Escape');await expect(dialog).toHaveCount(0);await expect(page.getByRole('button',{name:'Organize pages',exact:true})).toBeFocused();
});

test('organizer Ctrl and Shift selections move together, export in order and persist without detaching markups',async({page},info)=>{
 await page.setViewportSize({width:1440,height:1000});const s=await store();s.bytes=await sample(7);await setup(page,s);await text(page,'Markup remains with source page one');await expect.poll(()=>s.row.content.marks.length).toBe(1);await page.getByRole('button',{name:'Organize pages',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Organize pages',exact:true});
 await dialog.getByRole('button',{name:'Page 3',exact:true}).click({modifiers:['Control']});await expect(dialog.locator('.drawing-page-cards>div.selected')).toHaveCount(2);
 await dialog.getByRole('button',{name:'Page 5',exact:true}).click({modifiers:['Shift']});await expect(dialog.locator('.drawing-page-cards>div.selected')).toHaveCount(3);await expect(dialog.getByRole('button',{name:'Page 1',exact:true})).toHaveAttribute('aria-pressed','false');await dialog.getByRole('button',{name:'Page 1',exact:true}).click({modifiers:['Control']});
 await dialog.getByRole('listitem',{name:'Source page 3, position 3 of 7'}).dragTo(dialog.locator('.drawing-organizer-end'));
 await expect.poll(()=>s.row.content.pageOrder?.join(',')).toBe('2,6,7,1,3,4,5');expect(s.row.content.marks[0].page).toBe(1);
 const pending=page.waitForEvent('download');await dialog.getByRole('button',{name:'Download selected pages',exact:true}).click();await(await pending).saveAs(info.outputPath('selected-pages.pdf'));const texts=await pdfTexts(fs.readFileSync(info.outputPath('selected-pages.pdf')));expect(texts).toHaveLength(4);for(const [i,n] of [1,3,4,5].entries())expect(texts[i]).toContain('JGC TEST DRAWING PAGE '+n);expect(texts[0]).toContain('Markup remains');
 await dialog.getByRole('button',{name:'Close organizer',exact:true}).click();await expect(page.getByLabel('Page number',{exact:true})).toHaveValue('4');await expect(page.locator('.drawing-mark text')).toContainText('Markup remains');await page.getByRole('button',{name:'Refresh drawings',exact:true}).click();expect(s.row.content.pageOrder).toEqual([2,6,7,1,3,4,5]);
});

test('Download this page exports only the current reordered sheet with comments, crop and rotation intact',async({page},info)=>{
 const s=await store(),original=Buffer.from(s.bytes);s.row.content.pageOrder=[2,1];await setup(page,s);await text(page,'Only this second source sheet is reviewed');await expect.poll(()=>s.row.content.marks.length).toBe(1);const pending=page.waitForEvent('download');await page.getByRole('button',{name:'Download this page',exact:true}).click();const file=await pending;expect(file.suggestedFilename()).toContain('Page 1');await file.saveAs(info.outputPath('one-reviewed-page.pdf'));
 const bytes=fs.readFileSync(info.outputPath('one-reviewed-page.pdf')),exported=await PDFDocument.load(bytes),source=await PDFDocument.load(original);expect(exported.getPageCount()).toBe(1);expect(exported.getPage(0).getCropBox()).toEqual(source.getPage(1).getCropBox());expect(exported.getPage(0).getRotation()).toEqual(source.getPage(1).getRotation());expect(exported.getPage(0).node.Annots().size()).toBe(1);
 const texts=await pdfTexts(bytes);expect(texts[0]).toContain('JGC TEST DRAWING PAGE 2');expect(texts[0]).not.toContain('JGC TEST DRAWING PAGE 1');expect(texts[0]).toContain('Only this second');expect(original.equals(s.bytes)).toBe(true);
 const model=load('drawing-pdf');await expect(model.markedDrawingPdf(original,s.row.content,[99])).rejects.toThrow('valid drawing pages');await expect(model.markedDrawingPdf(original,s.row.content,[])).rejects.toThrow('valid drawing pages');
});
test('known distance, area, perimeter and invalid scale calculations',()=>{const m=load('drawing-model'),p=[{x:0,y:0},{x:100,y:0}],s=m.calibrate(p,10,'ft-in');expect(s.unitsPerPoint).toBe(.1);expect(m.measurement({kind:'distance',points:p},s)).toBe('10 ft 0 in');expect(m.measurement({kind:'area',points:[{x:0,y:0},{x:100,y:0},{x:100,y:100},{x:0,y:100}]},s)).toBe('100.00 sq ft');expect(m.measurement({kind:'perimeter',points:[...p,{x:100,y:100}]},s)).toBe('34 ft 1.6875 in');for(const n of [0,-5,NaN,Infinity])expect(()=>m.calibrate(p,n,'ft')).toThrow();expect(()=>m.calibrate([{x:0,y:0},{x:0,y:0}],5,'ft')).toThrow();});
test('shared annotations reopen on a second device and preserve original',async({page,browser},info)=>{const s=await store();await setup(page,s);await page.getByLabel('Markup layer').selectOption('As-built');await text(page);await expect.poll(()=>s.row.content.marks.length).toBe(1);await expect(page.getByRole('status').filter({hasText:'All drawing changes saved'})).toBeVisible();const context=await browser.newContext(),phone=await context.newPage();await phone.setViewportSize({width:390,height:844});await setup(phone,s);await expect(phone.locator('.drawing-mark text')).toContainText('conduit relocated');expect(s.row.content.marks[0].layer).toBe('As-built');const download=page.waitForEvent('download');await page.getByRole('button',{name:'Download original'}).click();const originalFile=await download;await originalFile.saveAs(info.outputPath('downloaded-original.pdf'));expect(fs.readFileSync(info.outputPath('downloaded-original.pdf')).equals(s.bytes)).toBe(true);const original=await PDFDocument.load(s.bytes);expect(original.getPageCount()).toBe(2);await phone.evaluate(()=>scrollTo(0,0));await phone.screenshot({fullPage:true,path:info.outputPath('phone.png')});await context.close();});
test('calibration enables measurement and survives zoom, page changes and rotation',async({page})=>{const s=await store();await setup(page,s);await page.getByRole('button',{name:'Measure',exact:true}).click();await expect(page.getByRole('button',{name:'Distance',exact:true})).toBeDisabled();await page.getByRole('button',{name:'Set scale',exact:true}).click();await drag(page);await page.getByLabel('Known length',{exact:true}).fill('10');await page.getByRole('button',{name:'Apply page scale'}).click();await expect(page.getByRole('button',{name:'Distance',exact:true})).toBeEnabled();await distance(page,70,150,130);await expect(page.locator('.drawing-mark text')).toContainText('10 ft 0 in');await expect.poll(()=>s.row.content.marks.length).toBe(1);const points=JSON.stringify(s.row.content.marks[0].points);await page.getByRole('button',{name:'Rotate view'}).click();await page.getByRole('button',{name:'Fit width'}).click();await expect(page.locator('.drawing-mark text')).toContainText('10 ft 0 in');expect(JSON.stringify(s.row.content.marks[0].points)).toBe(points);await page.getByRole('button',{name:'Page 2',exact:true}).click();await expect(page.getByRole('button',{name:'Distance',exact:true})).toBeDisabled();await page.getByRole('button',{name:'Page 1',exact:true}).click();await expect(page.getByRole('button',{name:'Distance',exact:true})).toBeEnabled();});
test('undo redo, page-specific marks and PDF export on cropped rotated originals',async({page},info)=>{const s=await store();await setup(page,s);await text(page,'Page one review');await page.getByRole('button',{name:'Undo',exact:true}).click();await page.getByRole('button',{name:'Undo',exact:true}).click();await expect(page.locator('.drawing-mark text')).toHaveCount(0);await page.getByRole('button',{name:'Redo',exact:true}).click();await page.getByRole('button',{name:'Redo',exact:true}).click();await expect(page.locator('.drawing-mark text')).toContainText('Page one review');await expect.poll(()=>s.row.content.marks.length).toBe(1);await page.getByRole('button',{name:'Page 2',exact:true}).click();await expect(page.locator('.drawing-mark text')).toHaveCount(0);await text(page,'Page two as-built');await expect.poll(()=>s.row.content.marks.length).toBe(2);const download=page.waitForEvent('download');await page.getByRole('button',{name:'Download marked PDF'}).click();const file=await download;await file.saveAs(info.outputPath('marked.pdf'));const exported=await PDFDocument.load(fs.readFileSync(info.outputPath('marked.pdf'))),original=await PDFDocument.load(s.bytes);expect(exported.getPageCount()).toBe(2);expect(exported.getPage(0).node.Annots().size()).toBe(1);expect(exported.getPage(1).node.Annots().size()).toBe(1);expect(exported.getPage(1).getCropBox()).toEqual(original.getPage(1).getCropBox());expect(exported.getPage(1).getRotation()).toEqual(original.getPage(1).getRotation());fs.writeFileSync(info.outputPath('original.pdf'),s.bytes);fs.writeFileSync(info.outputPath('markups.json'),JSON.stringify(s.row.content));await page.locator('.drawing-sheet').screenshot({path:info.outputPath('rotated-screen.png')});});
test('concurrent edits stop autosave and offer recovery without overwriting newer data',async({page})=>{const s=await store();await setup(page,s);s.row.revision=2;await text(page,'Unsaved local note');await expect(page.getByRole('alert')).toContainText('another device');expect(s.row.content.marks.length).toBe(0);await expect(page.getByRole('button',{name:'Recover unsaved markups'})).toBeVisible();await expect(page.getByRole('button',{name:'Text',exact:true})).toBeDisabled();});
for(const theme of ['light','dark'])for(const width of [390,1440])test(`drawing workspace ${theme} ${width}`,async({page},info)=>{await page.setViewportSize({width,height:1000});await page.addInitScript(t=>localStorage.setItem('jgcPortalTheme',t),theme);const s=await store();await setup(page,s);const dimensions=await page.evaluate(()=>({baseline:window.__drawingBaselineWidth,scroll:document.documentElement.scrollWidth,width:innerWidth,offenders:[...document.querySelectorAll('body *')].filter(e=>!e.closest('.drawing-stage')&&e.getBoundingClientRect().right>innerWidth).map(e=>({class:e.className,width:e.getBoundingClientRect().width,right:e.getBoundingClientRect().right})).slice(0,12)}));expect(dimensions.scroll,JSON.stringify(dimensions)).toBeLessThanOrEqual(dimensions.width);await expect(page.locator('html')).toHaveAttribute('data-jgc-theme',theme);await page.evaluate(()=>scrollTo(0,0));await page.screenshot({fullPage:true,path:info.outputPath(`drawing-${theme}-${width}.png`)});});
test('upload accepts PDF and keeps source immutable',async({page})=>{const s=await store();await setup(page,s);await page.locator('.drawing-heading input[type=file]').setInputFiles({name:'New drawing.pdf',mimeType:'application/pdf',buffer:s.bytes});await expect.poll(()=>s.uploaded).toBe(true);await expect(page.getByLabel('Drawing title')).toHaveValue('New drawing');});

test('highlight and comment edits are saved and included in marked export',async({page},info)=>{const s=await store();await setup(page,s);await page.getByRole('button',{name:'Edit',exact:true}).click();await page.getByRole('button',{name:'Highlight',exact:true}).click();await drag(page,70,90,130,20);await page.getByLabel('Edit selected comment').fill('Verify existing opening');await expect.poll(()=>s.row.content.marks[0]?.text).toBe('Verify existing opening');await text(page,'Updated text');await page.getByLabel('Edit drawing comment').fill('Corrected note');await expect(page.locator('.drawing-mark text')).toContainText('Corrected note');const pending=page.waitForEvent('download');await page.getByRole('button',{name:'Download marked PDF'}).click();const d=await pending;await d.saveAs(info.outputPath('highlight.pdf'));expect(s.row.content.marks[0].kind).toBe('highlight');});
test('invalid and oversized files are rejected before upload',async({page})=>{const s=await store();await setup(page,s);await page.locator('.drawing-heading input[type=file]').setInputFiles({name:'broken.pdf',mimeType:'application/pdf',buffer:Buffer.from('not a pdf')});await expect(page.getByRole('alert')).toBeVisible();expect(s.uploaded).toBeUndefined();});
test('drawing save status uses the Estimate Desk indicator and refresh reads latest record',async({page})=>{const s=await store();await setup(page,s);await text(page,'Save indicator check');await expect.poll(()=>s.saves).toBeGreaterThan(0);await expect(page.locator('.save-indicator')).toContainText('All changes saved');s.row={...s.row,title:'Updated from another device',revision:s.row.revision+1};await page.getByRole('button',{name:'Refresh drawings'}).click();await expect(page.getByLabel('Drawing title')).toHaveValue('Updated from another device');});
test('interrupted markup recovery restores only against its original server revision',async({page})=>{const s=await store();await setup(page,s);const content={version:1,marks:[{id:'recover',page:1,kind:'text',points:[{x:80,y:650}],color:'#d62828',text:'Recovered site note',author:'Test Admin',createdAt:'2026-10-01T12:00:00Z',layer:'As-built',rotation:0}],scales:{}};await page.evaluate(({id,content})=>localStorage.setItem('jgc-drawing-recovery-'+id,JSON.stringify({content,title:'Recovered drawing',baseRevision:1})),{id:s.row.id,content});page.once('dialog',d=>d.accept());await setup(page,s);await expect(page.locator('.drawing-mark text')).toContainText('Recovered site note');await expect.poll(()=>s.row.content.marks[0]?.text).toBe('Recovered site note');expect(await page.evaluate(id=>localStorage.getItem('jgc-drawing-recovery-'+id),s.row.id)).toBeNull();});

test('area and perimeter finish multi-point outlines and save correct measurements',async({page})=>{const s=await store();await setup(page,s);await page.getByRole('button',{name:'Measure',exact:true}).click();await page.getByRole('button',{name:'Set scale',exact:true}).click();await drag(page,70,90,100);await page.getByLabel('Known length',{exact:true}).fill('10');await page.getByRole('button',{name:'Apply page scale'}).click();for(const tool of ['Area','Perimeter']){await page.getByRole('button',{name:tool,exact:true}).click();await page.locator('.drawing-overlay').evaluate(svg=>scrollTo(0,scrollY+svg.getBoundingClientRect().top-240));const b=await page.locator('.drawing-overlay').boundingBox();for(const [x,y] of [[70,100],[170,100],[170,200],[70,200]])await page.mouse.click(b.x+x,b.y+y);await page.getByRole('button',{name:'Finish '+tool.toLowerCase(),exact:true}).click();}await expect(page.locator('.drawing-mark text')).toContainText(['100.00 sq ft','40 ft 0 in']);await expect.poll(()=>s.row.content.marks.length).toBe(2);});
test('six scale units, imperial fractions and legacy feet remain compatible',()=>{
 const m=load('drawing-model'),points=[{x:0,y:0},{x:100,y:0}];
 for(const [unit,expected] of [['ft','12.50 ft'],['in','12.50 in'],['ft-in','12 ft 6 in'],['m','12.500 m'],['cm','12.50 cm'],['mm','12.50 mm']])expect(m.measurement({kind:'distance',points},m.calibrate(points,12.5,unit))).toBe(expected);
 expect(m.measurement({kind:'distance',points},{unit:'ft',unitsPerPoint:.125,reference:points,knownLength:12.5})).toBe('12 ft 6 in');
 expect(()=>m.drawingPageOrder({pageOrder:[2,2]},2)).toThrow();
});
test('bottom scroll advances and top scroll returns without skipping pages',async({page})=>{
 const s=await store();await setup(page,s);
 const stage=page.getByLabel('PDF drawing view',{exact:true});await stage.scrollIntoViewIfNeeded();await stage.evaluate(el=>el.scrollTop=el.scrollHeight);
 const b=await stage.boundingBox();await page.mouse.move(b.x+b.width/2,b.y+b.height/2);await page.mouse.wheel(0,220);
 await expect(page.getByLabel('Page number',{exact:true})).toHaveValue('2');
 await page.waitForTimeout(900);await stage.evaluate(el=>el.scrollTop=0);await page.mouse.wheel(0,-220);
 await expect(page.getByLabel('Page number',{exact:true})).toHaveValue('1');await page.waitForTimeout(900);await page.mouse.wheel(0,-220);await expect(page.getByLabel('Page number',{exact:true})).toHaveValue('1');
});
test('review stamps are editable, autosave and export on rotated sheets',async({page},info)=>{
 const s=await store();await setup(page,s);await page.getByRole('button',{name:'Page 2',exact:true}).click();
 await page.getByRole('button',{name:'Stamps',exact:true}).click();await page.getByLabel('Stamp review status',{exact:true}).selectOption('Reviewed as noted');await page.getByLabel('Stamp reviewer',{exact:true}).fill('Zeth Hummel');await page.getByLabel('Stamp date',{exact:true}).fill('2026-10-02');
 await page.locator('.drawing-overlay').evaluate(svg=>scrollTo(0,scrollY+svg.getBoundingClientRect().top-240));const b=await page.locator('.drawing-overlay').boundingBox();await page.mouse.click(b.x+60,b.y+65);
 await expect(page.locator('.drawing-overlay .drawing-stamp')).toHaveCount(1);await page.getByLabel('Selected stamp review status',{exact:true}).selectOption('Revise and resubmit');
 await expect.poll(()=>s.row.content.marks[0]?.stamp?.status).toBe('Revise and resubmit');expect(s.row.content.marks[0].page).toBe(2);
 await page.locator('.drawing-sheet').screenshot({path:info.outputPath('stamp-view.png')});
 const pending=page.waitForEvent('download');await page.getByRole('button',{name:'Download marked PDF'}).click();const download=await pending;await download.saveAs(info.outputPath('stamp.pdf'));
 const exported=await PDFDocument.load(fs.readFileSync(info.outputPath('stamp.pdf')));expect(exported.getPage(1).getRotation().angle).toBe(90);expect(exported.getPage(1).node.Annots().size()).toBe(1);fs.writeFileSync(info.outputPath('stamp-content.json'),JSON.stringify(s.row.content));
});
test('arrow comment points at the clicked location and exports complete text',async({page},info)=>{
 const s=await store();await setup(page,s);await page.getByRole('button',{name:'Comments',exact:true}).click();await drag(page,70,90,120,60);
 await expect(page.getByLabel('Edit drawing comment')).toBeFocused();await page.getByLabel('Edit drawing comment').fill('Provide flashing at this opening. Confirm the existing dimension before installation.');
 await expect(page.locator('.drawing-callout text')).toContainText('Provide flashing');
 await expect.poll(()=>s.row.content.marks[0]?.kind).toBe('callout');expect(s.row.content.marks[0].points).toHaveLength(2);
 const pending=page.waitForEvent('download');await page.getByRole('button',{name:'Download marked PDF'}).click();await(await pending).saveAs(info.outputPath('callout.pdf'));await page.locator('.drawing-sheet').screenshot({path:info.outputPath('callout-view.png')});
});
test('snapping uses real vector lines and remains correct after rotation',async({page})=>{
 const s=await store();await setup(page,s);await page.getByRole('button',{name:'Measure',exact:true}).click();await page.getByRole('button',{name:'Snap to lines',exact:true}).click();
 await expect(page.locator('.drawing-snap-hint')).toContainText('Snapping to drawing line');
 const zoom=await page.locator('.drawing-viewbar').evaluate(el=>parseInt([...el.querySelectorAll('span')].find(s=>s.textContent.endsWith('%')).textContent)/100);
 await drag(page,70*zoom+3,(792-600)*zoom+3,300*zoom-5,0);await page.getByLabel('Known length',{exact:true}).fill('10');await page.getByRole('button',{name:'Apply page scale'}).click();
 await expect.poll(()=>s.row.content.scales['1']?.reference?.length).toBe(2);const points=s.row.content.scales['1'].reference;expect(points[0].x).toBeCloseTo(70,0);expect(points[0].y).toBeCloseTo(600,0);expect(points[1].x).toBeCloseTo(370,0);expect(points[1].y).toBeCloseTo(600,0);
 await page.getByRole('button',{name:'Rotate view',exact:true}).click();await page.getByRole('button',{name:'Fit width',exact:true}).click();await expect(page.locator('.drawing-snap-hint')).toContainText('Snapping to drawing line');
});
test('page organization survives reload, export and combine without detaching markups',async({page},info)=>{
 const s=await store(),original=Buffer.from(s.bytes);await setup(page,s);await text(page,'Original page one');
 await expect.poll(()=>s.saves).toBeGreaterThan(0);await page.getByRole('button',{name:'Organize pages',exact:true}).click();const target=page.getByRole('listitem',{name:'Source page 2, position 2 of 2'});const box=await target.boundingBox();await page.getByRole('listitem',{name:'Source page 1, position 1 of 2'}).dragTo(target,{targetPosition:{x:box.width-5,y:box.height/2}});
 await expect.poll(()=>s.row.content.pageOrder?.join(',')).toBe('2,1');expect(s.row.content.marks[0].page).toBe(1);
 await page.getByRole('button',{name:'Close organizer',exact:true}).click();await page.getByRole('button',{name:'Refresh drawings',exact:true}).click();await expect(page.getByLabel('Page number',{exact:true})).toHaveValue('1');await expect(page.locator('.drawing-mark text')).toHaveCount(0);
 await page.getByRole('button',{name:'Next page',exact:true}).click();await expect(page.locator('.drawing-mark text')).toContainText('Original page one');
 const pending=page.waitForEvent('download');await page.getByRole('button',{name:'Download marked PDF'}).click();await(await pending).saveAs(info.outputPath('reordered.pdf'));
 const exported=await PDFDocument.load(fs.readFileSync(info.outputPath('reordered.pdf')));expect(exported.getPage(0).getRotation().angle).toBe(90);expect(exported.getPage(1).node.Annots().size()).toBe(1);
 await page.getByRole('button',{name:'Organize pages',exact:true}).click();await page.getByLabel('PDFs to combine',{exact:true}).setInputFiles({name:'More sheets.pdf',mimeType:'application/pdf',buffer:original});await page.getByRole('button',{name:'Create combined PDF',exact:true}).click();await page.getByRole('button',{name:'Close organizer',exact:true}).click();
 await expect(page.getByLabel('Drawing title',{exact:true})).toHaveValue(/Combined/);await expect(page.locator('.drawing-viewbar label')).toContainText('of 4');await expect.poll(()=>s.row.content.marks[0]?.page).toBe(2);expect(original.equals(s.bytes)).toBe(true);
 const result=await load('drawing-pdf').combinedDrawingPdf(original,{version:1,marks:[{...s.row.content.marks[0],page:1}],scales:{'1':{unit:'ft',unitsPerPoint:1,knownLength:1,reference:[]}},pageOrder:[2,1]},[original]);
 expect((await PDFDocument.load(result.bytes)).getPageCount()).toBe(4);expect(result.content.marks[0].page).toBe(2);expect(result.content.scales['2'].unit).toBe('ft');
});
test('full screen has an exit button and Escape restores the Portal viewer',async({page})=>{
 const s=await store();await setup(page,s);await page.getByRole('button',{name:'Full screen',exact:true}).click();await expect(page.getByRole('button',{name:'Exit full screen',exact:true})).toBeVisible();
 const bounds=await page.locator('.drawing-viewer').boundingBox();expect(bounds.x).toBe(0);expect(bounds.y).toBe(0);
 await page.getByRole('button',{name:'Exit full screen',exact:true}).click();await expect(page.getByRole('button',{name:'Full screen',exact:true})).toBeVisible();
 await page.evaluate(()=>{Object.defineProperty(HTMLElement.prototype,'requestFullscreen',{configurable:true,value:undefined});});await page.getByRole('button',{name:'Full screen',exact:true}).click();await page.keyboard.press('Escape');await expect(page.getByRole('button',{name:'Full screen',exact:true})).toBeVisible();
});
for(const width of [1440])test(`edge panel tabs reopen without losing page or markups at ${width}px`,async({page},info)=>{
 await page.setViewportSize({width,height:1000});const s=await store();await setup(page,s);await text(page,'Keep this review note');await expect.poll(()=>s.row.content.marks.length).toBe(1);
 await page.getByRole('button',{name:'Page 2',exact:true}).click();const stage=page.getByLabel('PDF drawing view',{exact:true}),before=await stage.boundingBox(),revision=s.row.revision;
 await page.getByRole('button',{name:'Hide pages',exact:true}).click();await expect(page.getByLabel('Page thumbnails',{exact:true})).toHaveCount(0);
 const closedPages=page.getByRole('button',{name:'Show pages',exact:true});await expect(closedPages).toHaveAttribute('aria-expanded','false');expect((await stage.boundingBox()).width).toBeGreaterThan(before.width);
 await page.getByRole('button',{name:'Hide markup panel',exact:true}).click();await expect(page.getByLabel('Drawing comments',{exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'Show markup panel',exact:true})).toBeVisible();
 await expect(page.getByLabel('Page number',{exact:true})).toHaveValue('2');expect(s.row.revision).toBe(revision);
 await page.locator('.drawing-workspace').screenshot({path:info.outputPath(`closed-panels-${width}.png`)});
 await closedPages.focus();await page.keyboard.press('Enter');await expect(page.getByRole('button',{name:'Page 2',exact:true})).toHaveAttribute('aria-current','page');
 await page.getByRole('button',{name:'Show markup panel',exact:true}).focus();await page.keyboard.press('Space');await expect(page.getByLabel('Drawing comments',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Page 1',exact:true}).click();await expect(page.locator('.drawing-mark text')).toContainText('Keep this review note');
 await page.getByRole('button',{name:'Full screen',exact:true}).click();await page.getByRole('button',{name:'Hide pages',exact:true}).click();await page.getByRole('button',{name:'Hide markup panel',exact:true}).click();
 await expect(page.getByRole('button',{name:'Show pages',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Show markup panel',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Show pages',exact:true}).click();await page.getByRole('button',{name:'Show markup panel',exact:true}).click();await expect(page.locator('.drawing-mark text')).toContainText('Keep this review note');
 await page.screenshot({path:info.outputPath(`fullscreen-panels-${width}.png`)});await page.getByRole('button',{name:'Exit full screen',exact:true}).click();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(width);
});
test('Ctrl wheel zoom follows the pointer without changing pages or browser scale',async({page})=>{
 await page.setViewportSize({width:1440,height:1000});const s=await store();await setup(page,s);await text(page,'Zoom keeps markups');await expect.poll(()=>s.row.content.marks.length).toBe(1);
 const saved=JSON.stringify(s.row.content),stage=page.getByLabel('PDF drawing view',{exact:true});await page.getByRole('button',{name:'Hide pages',exact:true}).click();await page.getByRole('button',{name:'Hide markup panel',exact:true}).click();await page.getByRole('button',{name:'Fit width',exact:true}).click();await stage.scrollIntoViewIfNeeded();
 const zoom=()=>page.locator('.drawing-viewbar').evaluate(el=>parseInt([...el.querySelectorAll('span')].find(s=>s.textContent.endsWith('%')).textContent));
 const b=await stage.boundingBox(),pointer={x:b.x+b.width*.6,y:b.y+Math.min(200,b.height*.4)};
 const atPointer=()=>page.locator('.drawing-sheet').evaluate((el,p)=>{const r=el.getBoundingClientRect();return{x:(p.x-r.left)/r.width,y:(p.y-r.top)/r.height};},pointer);
 const start=await zoom(),anchor=await atPointer(),browser=await page.evaluate(()=>({width:innerWidth,scale:visualViewport.scale}));
 await page.mouse.move(pointer.x,pointer.y);await page.keyboard.down('Control');await page.mouse.wheel(0,-160);await expect.poll(zoom).toBeGreaterThan(start);
 await expect.poll(async()=>Math.abs((await atPointer()).x-anchor.x)).toBeLessThan(.004);await expect.poll(async()=>Math.abs((await atPointer()).y-anchor.y)).toBeLessThan(.004);
 const higher=await zoom();await page.mouse.wheel(0,160);await expect.poll(zoom).toBeLessThan(higher);await page.keyboard.up('Control');
 await expect(page.getByLabel('Page number',{exact:true})).toHaveValue('1');expect(await page.evaluate(()=>({width:innerWidth,scale:visualViewport.scale}))).toEqual(browser);expect(JSON.stringify(s.row.content)).toBe(saved);
 await stage.evaluate(el=>el.scrollTop=el.scrollHeight);await page.keyboard.down('Control');await page.mouse.wheel(0,100);await page.keyboard.up('Control');await expect(page.getByLabel('Page number',{exact:true})).toHaveValue('1');
 await page.waitForTimeout(900);await stage.evaluate(el=>el.scrollTop=el.scrollHeight);await page.mouse.wheel(0,220);await expect(page.getByLabel('Page number',{exact:true})).toHaveValue('2');
});
test('click click distance and draggable offset preserve endpoints and calibrated length',async({page},info)=>{
 const s=await store();await setup(page,s);await page.getByRole('button',{name:'Measure',exact:true}).click();await drag(page,70,90,130);await page.getByLabel('Known length',{exact:true}).fill('10');await page.getByRole('button',{name:'Apply page scale'}).click();
 await page.locator('.drawing-overlay').evaluate(svg=>scrollTo(0,scrollY+svg.getBoundingClientRect().top-240));let b=await page.locator('.drawing-overlay').boundingBox();await page.mouse.click(b.x+70,b.y+150);await page.mouse.move(b.x+200,b.y+150);
 expect(s.row.content.marks.length).toBe(0);await expect(page.locator('.drawing-dimension')).toHaveCount(1);await page.mouse.click(b.x+200,b.y+150);await expect.poll(()=>s.row.content.marks.length).toBe(1);
 const original=JSON.stringify(s.row.content.marks[0].points),label=load('drawing-model').measurement(s.row.content.marks[0],s.row.content.scales['1']);expect(label).toBe('10 ft 0 in');
 await page.mouse.move(b.x+135,b.y+150);await page.mouse.down();await page.mouse.move(b.x+135,b.y+205,{steps:6});await page.mouse.up();
 await expect.poll(()=>Math.abs(s.row.content.marks[0]?.dimensionOffset??0)).toBeGreaterThan(20);expect(JSON.stringify(s.row.content.marks[0].points)).toBe(original);expect(load('drawing-model').measurement(s.row.content.marks[0],s.row.content.scales['1'])).toBe(label);
 const pending=page.waitForEvent('download');await page.getByRole('button',{name:'Download marked PDF'}).click();await(await pending).saveAs(info.outputPath('offset-dimension.pdf'));await page.locator('.drawing-sheet').screenshot({path:info.outputPath('offset-view.png')});
 await page.getByRole('button',{name:'Refresh drawings',exact:true}).click();await expect(page.locator('.drawing-dimension-label')).toContainText(label);await expect.poll(()=>s.row.content.marks[0].dimensionOffset).not.toBe(0);
});

test('larger PDFs upload in resumable chunks with retry and progress, never upsert',async({page})=>{
 test.setTimeout(45000);const s=await store();await setup(page,s);
 const doc=await PDFDocument.load(s.bytes);doc.context.register(doc.context.stream(new Uint8Array(26*1024*1024)));const bytes=Buffer.from(await doc.save({useObjectStreams:false}));expect(bytes.length).toBeGreaterThan(25*1024*1024);
 let offset=0,failed=false,heads=0,metadata='',chunks=[];
 await page.evaluate(()=>{const factory=window.createJgcSupabaseClient;window.createJgcSupabaseClient=()=>{const c=factory();c.auth.getSession=async()=>({data:{session:{access_token:'test-access'}},error:null});return c;};window.__drawingUploadChunks=[];const send=XMLHttpRequest.prototype.send;XMLHttpRequest.prototype.send=function(body){if(body instanceof Blob)window.__drawingUploadChunks.push(body.size);return send.call(this,body);};});
 await page.route('https://drawings.example.test/storage/v1/upload/resumable**',async route=>{
  const request=route.request(),headers=request.headers(),method=request.method();expect(headers['x-upsert']??'false').toBe('false');if(['POST','HEAD','PATCH'].includes(method))expect(headers.authorization).toBe('Bearer test-access');
  const common={'Tus-Resumable':'1.0.0','Upload-Offset':String(offset),'Upload-Length':String(bytes.length),'Access-Control-Allow-Origin':'*','Access-Control-Expose-Headers':'Location, Upload-Offset, Upload-Length, Tus-Resumable'};
  if(method==='POST'){metadata=headers['upload-metadata'];return route.fulfill({status:201,headers:{...common,Location:'https://drawings.example.test/storage/v1/upload/resumable/test-upload'}});}
  if(method==='HEAD'){heads++;return route.fulfill({status:200,headers:common});}
  if(method==='PATCH'){if(offset>0&&!failed){failed=true;return route.fulfill({status:503,headers:common});}expect(Number(headers['upload-offset'])).toBe(offset);const chunk=request.postDataBuffer();/* Playwright WebKit omits Blob bodies; observe actual XHR.send Blob size instead. */const size=chunk?.length??await page.evaluate(()=>window.__drawingUploadChunks.at(-1));expect(size).toBeGreaterThan(0);chunks.push(size);offset+=size;await new Promise(resolve=>setTimeout(resolve,100));return route.fulfill({status:204,headers:{...common,'Upload-Offset':String(offset)}});}
  return route.fulfill({status:204,headers:common});
 });
 await page.locator('.drawing-heading input[type=file]').setInputFiles({name:'Large drawing.pdf',mimeType:'application/pdf',buffer:bytes});await expect(page.getByRole('status').filter({hasText:'Uploading drawing'})).toBeVisible();
 await expect(page.getByLabel('Drawing title',{exact:true})).toHaveValue('Large drawing',{timeout:30000});expect(offset).toBe(bytes.length);expect(heads).toBeGreaterThan(0);expect(failed).toBe(true);expect(Math.max(...chunks)).toBe(6*1024*1024);expect(metadata).toContain('bucketName');expect(s.row.file_name).toBe('Large drawing.pdf');
});
test('upload rejects files beyond the current 50 MB cap before contacting storage',async()=>{
 const api=load('../src/drawings-api');await expect(api.addDrawing('job',{size:51*1024*1024})).rejects.toThrow('50 MB');
});

test('metric calibration converts distances and areas without changing the saved reference',()=>{
 const m=load('drawing-model'),points=[{x:0,y:0},{x:100,y:0}],scale=m.calibrate(points,3048,'mm');
 const distance={kind:'distance',points},area={kind:'area',points:[...points,{x:100,y:100},{x:0,y:100}]};
 for(const [unit,length,surface] of [['ft','10.00 ft','100.00 sq ft'],['ft-in','10 ft 0 in','100.00 sq ft'],['in','120.00 in','14400.00 sq in'],['yd','3.33 yd','11.11 sq yd'],['m','3.048 m','9.29 sq m'],['cm','304.80 cm','92903.04 sq cm'],['mm','3048.00 mm','9290304.00 sq mm']]){
  expect(m.measurement(distance,{...scale,displayUnit:unit})).toBe(length);expect(m.measurement(area,{...scale,displayUnit:unit})).toBe(surface);
 }
 expect(scale.unit).toBe('mm');expect(scale.knownLength).toBe(3048);expect(scale.reference).toEqual(points);
 expect(m.scaleReferenceLabel({...scale,displayUnit:'ft-in'})).toBe('Scale reference - 3048.00 mm');
});

test('two-click blue reference persists independently of display units and exports',async({page},info)=>{
 const s=await store();await setup(page,s);await page.getByRole('button',{name:'Measure',exact:true}).click();await page.getByLabel('Scale units').selectOption('mm');
 await page.locator('.drawing-overlay').evaluate(svg=>scrollTo(0,scrollY+svg.getBoundingClientRect().top-240));const b=await page.locator('.drawing-overlay').boundingBox();
 await page.mouse.click(b.x+70,b.y+90);await page.mouse.move(b.x+200,b.y+90);await expect(page.getByRole('button',{name:'Apply page scale'})).toBeDisabled();
 await page.mouse.click(b.x+200,b.y+90);await expect(page.locator('.drawing-scale-reference')).toContainText('enter the known length');await page.getByLabel('Known length',{exact:true}).fill('3048');await page.getByRole('button',{name:'Apply page scale'}).click();
 await expect(page.locator('.drawing-scale-reference')).toContainText('Scale reference - 3048.00 mm');await distance(page,70,150,130);await page.getByLabel('Measurement output').selectOption('ft-in');
 await expect(page.locator('.drawing-dimension-label')).toContainText('10 ft 0 in');await expect.poll(()=>s.row.content.scales['1']?.displayUnit).toBe('ft-in');const reference=JSON.stringify(s.row.content.scales['1'].reference);
 for(const unit of ['in','cm','yd','ft-in'])await page.getByLabel('Measurement output').selectOption(unit);
 expect(JSON.stringify(s.row.content.scales['1'].reference)).toBe(reference);expect(s.row.content.scales['1'].knownLength).toBe(3048);
 await page.getByRole('button',{name:'Refresh drawings'}).click();await expect(page.locator('.drawing-scale-reference')).toContainText('3048.00 mm');await expect(page.locator('.drawing-dimension-label')).toContainText('10 ft 0 in');await expect(page.getByLabel('Measurement output')).toHaveValue('ft-in');
 const pending=page.waitForEvent('download');await page.getByRole('button',{name:'Download marked PDF'}).click();await(await pending).saveAs(info.outputPath('blue-reference.pdf'));await page.locator('.drawing-sheet').screenshot({path:info.outputPath('blue-reference.png')});fs.writeFileSync(info.outputPath('blue-reference-content.json'),JSON.stringify(s.row.content));
});

test('selected measurements have a delete X, with undo and shared persistence',async({page})=>{
 const s=await store();await setup(page,s);await page.getByRole('button',{name:'Measure',exact:true}).click();await drag(page);await page.getByLabel('Known length',{exact:true}).fill('10');await page.getByRole('button',{name:'Apply page scale'}).click();await distance(page);
 await expect.poll(()=>s.row.content.marks.length).toBe(1);await page.getByRole('button',{name:'Delete measurement',exact:true}).click();await expect.poll(()=>s.row.content.marks.length).toBe(0);await expect(page.locator('.drawing-scale-reference')).toHaveCount(1);
 await page.getByRole('button',{name:'Undo',exact:true}).click();await expect.poll(()=>s.row.content.marks.length).toBe(1);await page.getByRole('button',{name:'Select',exact:true}).click();await page.getByRole('button',{name:'distance: 10 ft 0 in',exact:true}).click();await page.keyboard.press('Delete');await expect.poll(()=>s.row.content.marks.length).toBe(0);
});

test('placed stamps return to Select, move, resize and accept review choices on the drawing',async({page},info)=>{
 const s=await store();await setup(page,s);await page.getByRole('button',{name:'Stamps',exact:true}).click();await page.getByLabel('Stamp reviewer',{exact:true}).fill('Zeth Hummel');await page.getByLabel('Stamp date',{exact:true}).fill('2026-10-02');
 await page.locator('.drawing-overlay').evaluate(svg=>scrollTo(0,scrollY+svg.getBoundingClientRect().top-240));const b=await page.locator('.drawing-overlay').boundingBox();await page.mouse.click(b.x+90,b.y+90);
 await expect(page.getByRole('button',{name:'Select',exact:true})).toHaveAttribute('aria-pressed','true');await page.mouse.click(b.x+450,b.y+110);await expect(page.locator('.drawing-stamp')).toHaveCount(1);
 const initial=await page.locator('.drawing-stamp').boundingBox();await page.mouse.move(initial.x+initial.width*.5,initial.y+initial.height*.08);await page.mouse.down();await page.mouse.move(initial.x+initial.width*.5+45,initial.y+initial.height*.08+35,{steps:5});await page.mouse.up();
 await expect.poll(()=>s.row.content.marks[0]?.points[0]?.x).toBeGreaterThan(70);const moved=await page.locator('.drawing-stamp').boundingBox();expect(moved.x).toBeGreaterThan(initial.x+40);expect(moved.y).toBeGreaterThan(initial.y+30);
 const before=s.row.content.marks[0].stamp.width,handle=await page.getByRole('button',{name:'Resize stamp'}).boundingBox();await page.mouse.move(handle.x+handle.width/2,handle.y+handle.height/2);await page.mouse.down();await page.mouse.move(handle.x+handle.width/2+50,handle.y+handle.height/2+30,{steps:6});await page.mouse.up();await expect.poll(()=>s.row.content.marks[0]?.stamp?.width).toBeGreaterThan(before);
 await page.locator('.drawing-stamp').getByRole('radio',{name:'Reviewed as noted',exact:true}).click();await expect.poll(()=>s.row.content.marks[0]?.stamp?.status).toBe('Reviewed as noted');expect(s.row.content.marks.length).toBe(1);const saved=JSON.stringify(s.row.content.marks[0]);
 await page.getByRole('button',{name:'Refresh drawings'}).click();expect(JSON.stringify(s.row.content.marks[0])).toBe(saved);await expect(page.locator('.drawing-stamp').getByRole('radio',{name:'Reviewed as noted',exact:true})).toHaveAttribute('aria-checked','true');
 const pending=page.waitForEvent('download');await page.getByRole('button',{name:'Download marked PDF'}).click();await(await pending).saveAs(info.outputPath('moved-stamp.pdf'));await page.locator('.drawing-sheet').screenshot({path:info.outputPath('moved-stamp.png')});fs.writeFileSync(info.outputPath('moved-stamp-content.json'),JSON.stringify(s.row.content));
});

for(const theme of ['light','dark'])for(const width of [390,1440])test(`selected stamp delete X saves and can be undone ${theme} ${width}`,async({page},info)=>{
 await page.setViewportSize({width,height:1000});await page.addInitScript(t=>localStorage.setItem('jgcPortalTheme',t),theme);
 const s=await store();await setup(page,s);await page.getByRole('button',{name:'Stamps',exact:true}).click();await page.getByLabel('Stamp reviewer',{exact:true}).fill('Test reviewer');await page.getByLabel('Stamp date',{exact:true}).fill('2026-10-02');
 await page.locator('.drawing-overlay').evaluate(svg=>scrollTo(0,scrollY+svg.getBoundingClientRect().top-240));const b=await page.locator('.drawing-overlay').boundingBox();await page.mouse.click(b.x+45,b.y+65);
 const remove=page.getByRole('button',{name:'Delete stamp',exact:true});await expect(remove).toBeVisible();await expect.poll(()=>s.row.content.marks.length).toBe(1);
 const saved=JSON.stringify(s.row.content.marks[0]);await page.locator('.drawing-workspace').screenshot({path:info.outputPath(`stamp-delete-${theme}-${width}.png`)});
 await remove.click();await expect(page.locator('.drawing-stamp')).toHaveCount(0);await expect.poll(()=>s.row.content.marks.length).toBe(0);
 await page.getByRole('button',{name:'Undo',exact:true}).click();await expect.poll(()=>s.row.content.marks.length).toBe(1);expect(JSON.stringify(s.row.content.marks[0])).toBe(saved);
 await page.locator('.drawing-stamp').click({position:{x:20,y:15}});await expect(remove).toBeVisible();await remove.click();await expect.poll(()=>s.row.content.marks.length).toBe(0);
 await page.getByRole('button',{name:'Refresh drawings'}).click();await expect(page.locator('.drawing-stamp')).toHaveCount(0);expect(s.row.content.marks).toHaveLength(0);
 const pending=page.waitForEvent('download');await page.getByRole('button',{name:'Download marked PDF'}).click();await(await pending).saveAs(info.outputPath('removed-stamp.pdf'));const exported=await PDFDocument.load(fs.readFileSync(info.outputPath('removed-stamp.pdf')));expect(exported.getPages().every(p=>!p.node.Annots()||p.node.Annots().size()===0)).toBe(true);
});

test('inline comments reopen for typing with the markup panel closed',async({page},info)=>{
 const s=await store();await setup(page,s);await text(page,'Original note');await page.getByRole('button',{name:'Hide markup panel'}).click();await page.getByRole('button',{name:'Select',exact:true}).click();
 await page.locator('.drawing-overlay').evaluate(svg=>scrollTo(0,scrollY+svg.getBoundingClientRect().top-240));const b=await page.locator('.drawing-overlay').boundingBox();await page.mouse.click(b.x+350,b.y+220);await expect(page.getByLabel('Edit drawing comment')).toHaveCount(0);await page.locator('.drawing-text-comment').click();await expect(page.getByLabel('Edit drawing comment')).toBeFocused();await page.getByLabel('Edit drawing comment').fill('Revised directly on the drawing');
 await expect.poll(()=>s.row.content.marks[0]?.text).toBe('Revised directly on the drawing');await expect(page.getByLabel('Drawing comments')).toHaveCount(0);await page.getByRole('button',{name:'Refresh drawings'}).click();await expect(page.locator('.drawing-mark text')).toContainText('Revised directly');
 await expect(page.getByLabel('Drawing title',{exact:true})).toBeEnabled();await page.locator('.drawing-text-comment').click();await page.getByLabel('Edit drawing comment').fill('Second edit');await expect.poll(()=>s.row.content.marks[0]?.text).toBe('Second edit');await page.locator('.drawing-sheet').screenshot({path:info.outputPath('inline-comment.png')});
});

test('removed drawings disappear from the shared list and can be restored intact',async({page,browser})=>{
 const s=await store(),original=Buffer.from(s.bytes);await setup(page,s);await text(page,'Keep the original and this note');await expect.poll(()=>s.row.content.marks.length).toBe(1);const content=JSON.stringify(s.row.content);
 page.once('dialog',d=>d.dismiss());await page.getByRole('button',{name:'Remove drawing',exact:true}).click();expect(s.row.content.archived).toBeUndefined();await expect(page.getByLabel('Select drawing').locator('option')).toHaveCount(2);
 page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Remove drawing',exact:true}).click();await expect.poll(()=>s.row.content.archived).toBe(true);await expect(page.getByLabel('Select drawing').locator('option')).toHaveCount(1);await expect(page.locator('.drawing-viewer')).toHaveCount(0);
 await page.getByLabel('Show removed drawings').check();await page.getByLabel('Select drawing').selectOption(s.row.id);await expect(page.getByRole('button',{name:'Restore drawing',exact:true})).toBeVisible();await expect(page.locator('.drawing-mark text')).toContainText('Keep the original');
 await page.getByRole('button',{name:'Restore drawing',exact:true}).click();await expect.poll(()=>s.row.content.archived).toBe(false);await page.getByLabel('Show removed drawings').uncheck();await expect(page.getByLabel('Select drawing').locator('option')).toHaveCount(2);
 const {archived,...restored}=s.row.content;expect(JSON.stringify(restored)).toBe(content);expect(s.bytes.equals(original)).toBe(true);
 const context=await browser.newContext(),phone=await context.newPage();await phone.setViewportSize({width:390,height:844});await setup(phone,s);await expect(phone.locator('.drawing-mark text')).toContainText('Keep the original');await context.close();
});

test('dense vector PDFs retain late thin extension lines and snap in transformed coordinates',async()=>{
 const snap=load('drawing-snap'),OPS={save:1,restore:2,transform:3,constructPath:4};
 const fnArray=[],argsArray=[];for(let i=0;i<31000;i++){fnArray.push(OPS.constructPath);argsArray.push([0,[new Float32Array([0,1000+i,0,1,1000+i,10])]]);}
 fnArray.push(OPS.save,OPS.transform,OPS.constructPath,OPS.restore);argsArray.push([], [0,1,-1,0,-10,50], [0,[new Float32Array([0,20,0,1,20,40])]], []);
 const segments=await snap.drawingSegments({getOperatorList:async()=>({fnArray,argsArray})},OPS);expect(segments).toHaveLength(31001);
 const point={x:-30,y:71},result=snap.snapPoint(point,segments,2);expect(result.snapped).toBe(true);expect(result.point).toEqual({x:-30,y:70});expect(snap.snapPoint(point,segments.slice(0,30000),2).snapped).toBe(false);
 expect(snap.snapPoint({x:-52,y:72},segments,3).point).toEqual({x:-50,y:70});
});

test('PDF comment icons stay outside boxed text and inside crop edges for every rotation',async({},info)=>{
 const pdf=await PDFDocument.create(),content=load('drawing-model').emptyDrawing(),angles=[0,90,180,270];
 for(const [i,rotation] of angles.entries()){const p=pdf.addPage([612,792]);p.setRotation(degrees(rotation));content.marks.push({id:'note-'+i,page:i+1,kind:'text',points:[{x:220,y:500}],color:'#d62828',text:'Rotated comment stays readable',author:'Test admin',createdAt:'2026-10-02T12:00:00Z',layer:'Review',rotation});}
 const bytes=await load('drawing-pdf').markedDrawingPdf(await pdf.save(),content),exported=await PDFDocument.load(bytes);
 for(const [i,rotation] of angles.entries()){
  const annotation=exported.getPage(i).node.Annots().lookup(0),rect=annotation.lookup(PDFName.of('Rect')).asArray().map(n=>n.asNumber()),angle=rotation*Math.PI/180;
  const corners=[[rect[0],rect[1]],[rect[0],rect[3]],[rect[2],rect[1]],[rect[2],rect[3]]],across=corners.map(([x,y])=>(x-220)*Math.cos(angle)+(y-500)*Math.sin(angle)),along=corners.map(([x,y])=>-(x-220)*Math.sin(angle)+(y-500)*Math.cos(angle));
  expect(Math.min(...across)>185||Math.max(...across)<0||Math.min(...along)>=24||Math.max(...along)<=-62).toBe(true);
  expect(rect[0]).toBeGreaterThanOrEqual(24);expect(rect[1]).toBeGreaterThanOrEqual(24);expect(rect[2]).toBeLessThanOrEqual(612-24);expect(rect[3]).toBeLessThanOrEqual(792-24);
  expect(annotation.lookup(PDFName.of('Contents')).decodeText()).toBe('Rotated comment stays readable');
 }
 fs.writeFileSync(info.outputPath('boxed-comments-rotations.pdf'),bytes);
});

test.describe('phone touch controls',()=>{test.use({hasTouch:true});
for(const width of [320,390])for(const theme of ['light','dark'])test(`phone drawing workspace ${width} ${theme}`,async({page},info)=>{
 await page.setViewportSize({width,height:844});await page.addInitScript(t=>localStorage.setItem('jgcPortalTheme',t),theme);const s=await store();await setup(page,s);
 const stage=page.getByLabel('PDF drawing view',{exact:true});await expect(page.getByLabel('Page thumbnails',{exact:true})).toHaveCount(0);await expect(page.getByLabel('Drawing comments',{exact:true})).toHaveCount(0);
 await expect.poll(async()=>{const canvas=await page.locator('.drawing-sheet').boundingBox(),view=await stage.boundingBox();return canvas.width<=view.width;}).toBe(true);
 const before=await stage.boundingBox();expect(before.width).toBeGreaterThan(width-80);
 for(const bar of ['.drawing-modes','.drawing-toolbar','.drawing-viewbar']){const box=await page.locator(bar).boundingBox();expect(box.height).toBeLessThan(80);expect(box.width).toBeLessThanOrEqual(width);}
 await page.getByRole('button',{name:'Pages',exact:true}).click();await expect(page.getByLabel('Page thumbnails',{exact:true})).toBeVisible();await page.getByRole('button',{name:'Page 2',exact:true}).click();await expect(page.getByLabel('Page number',{exact:true})).toHaveValue('2');await page.getByRole('button',{name:'Close pages',exact:true}).click();
 await page.getByRole('button',{name:'Markups',exact:true}).click();await expect(page.getByLabel('Drawing comments',{exact:true})).toBeVisible();expect((await stage.boundingBox()).width).toBe(before.width);await page.getByRole('button',{name:'Pages',exact:true}).click();await expect(page.getByLabel('Drawing comments',{exact:true})).toHaveCount(0);await page.getByRole('button',{name:'Page 1',exact:true}).click();await page.getByRole('button',{name:'Close pages',exact:true}).click();
 await page.getByRole('button',{name:'Full screen',exact:true}).click();await expect(page.locator('.drawing-viewer')).toHaveClass(/is-fullscreen/);expect((await stage.boundingBox()).height).toBeGreaterThan(400);await page.screenshot({path:info.outputPath(`phone-full-${width}-${theme}.png`)});
 await page.getByRole('button',{name:'Zoom in',exact:true}).click();await page.getByRole('button',{name:'Fit width',exact:true}).click();await expect.poll(async()=>{const canvas=await page.locator('.drawing-sheet').boundingBox(),view=await stage.boundingBox();return canvas.width<=view.width;}).toBe(true);
 await page.getByRole('button',{name:'Exit full screen',exact:true}).click();expect(await page.locator('.job-drawings').evaluate(e=>e.scrollWidth)).toBeLessThanOrEqual(width);
 const original=Buffer.from(s.bytes);await page.getByRole('button',{name:'Edit',exact:true}).click();await page.getByRole('button',{name:'Text',exact:true}).click();await page.getByRole('button',{name:'Close markups',exact:true}).click();await page.locator('.drawing-overlay').evaluate(svg=>scrollTo(0,scrollY+svg.getBoundingClientRect().top-150));const b=await page.locator('.drawing-overlay').boundingBox();await page.touchscreen.tap(b.x+80,b.y+100);await page.getByLabel('Edit drawing comment',{exact:true}).fill('Phone site note');await expect.poll(()=>s.row.content.marks[0]?.text).toBe('Phone site note');expect(original.equals(s.bytes)).toBe(true);
 const pending=page.waitForEvent('download');await page.getByRole('button',{name:'Download this page',exact:true}).click();await(await pending).saveAs(info.outputPath('phone-page.pdf'));expect((await PDFDocument.load(fs.readFileSync(info.outputPath('phone-page.pdf')))).getPageCount()).toBe(1);
 await page.getByRole('button',{name:'View',exact:true}).click();await page.locator('.drawing-viewer').screenshot({path:info.outputPath(`phone-view-${width}-${theme}.png`)});
});

test('landscape phone keeps a usable canvas and reachable full-screen exit',async({page},info)=>{
 await page.setViewportSize({width:844,height:390});const s=await store();await setup(page,s);await page.getByRole('button',{name:'Full screen',exact:true}).click();const stage=page.getByLabel('PDF drawing view',{exact:true});expect((await stage.boundingBox()).height).toBeGreaterThan(140);await expect(page.getByLabel('Page thumbnails',{exact:true})).toHaveCount(0);
 const exit=page.getByRole('button',{name:'Exit full screen',exact:true});const box=await exit.boundingBox();expect(box.x+box.width).toBeLessThanOrEqual(844);await page.screenshot({path:info.outputPath('phone-landscape.png')});await exit.tap();await expect(page.locator('.drawing-viewer')).not.toHaveClass(/is-fullscreen/);
});
});

async function drawingTouch(page,browserName,type,points){
 if(browserName==='chromium'){
  page.__gestureCdp??=await page.context().newCDPSession(page);
  await page.__gestureCdp.send('Input.dispatchTouchEvent',{type,touchPoints:points.map((p,i)=>({x:p.x,y:p.y,id:i+1,radiusX:4,radiusY:4}))});
 }else await page.locator('.drawing-stage').evaluate((stage,{type,points})=>{
  const target=stage.querySelector('.drawing-overlay'),touches=points.map((p,i)=>({identifier:i+1,target,clientX:p.x,clientY:p.y,pageX:p.x+scrollX,pageY:p.y+scrollY}));
  if(touches.length)stage.__lastTouches=touches;
  const event=new Event(type.toLowerCase(),{bubbles:true,cancelable:true});Object.assign(event,{touches,targetTouches:touches,changedTouches:touches.length?touches:stage.__lastTouches||[]});target.dispatchEvent(event);
 },{type,points});
}
async function swipeDrawing(page,browserName,dx,dy=0){const stage=page.getByLabel('PDF drawing view',{exact:true});await stage.scrollIntoViewIfNeeded();const b=await stage.boundingBox(),first={x:b.x+b.width/2,y:b.y+Math.min(130,b.height/2)};await drawingTouch(page,browserName,'touchStart',[first]);for(let i=1;i<=5;i++)await drawingTouch(page,browserName,'touchMove',[{x:first.x+dx*i/5,y:first.y+dy*i/5}]);await drawingTouch(page,browserName,'touchEnd',[]);}
test.describe('drawing gestures',()=>{test.use({hasTouch:true,viewport:{width:390,height:844}});
 test('left/right swipes advance one page and respect first/last boundaries',async({page,browserName})=>{
  const s=await store();await setup(page,s);await swipeDrawing(page,browserName,-110);await expect(page.getByLabel('Page number',{exact:true})).toHaveValue('2');await page.waitForTimeout(900);await page.getByRole('button',{name:'Fit width',exact:true}).click();await swipeDrawing(page,browserName,-110);await expect(page.getByLabel('Page number',{exact:true})).toHaveValue('2');await swipeDrawing(page,browserName,110);await expect(page.getByLabel('Page number',{exact:true})).toHaveValue('1');await page.waitForTimeout(900);await swipeDrawing(page,browserName,110);await expect(page.getByLabel('Page number',{exact:true})).toHaveValue('1');expect(s.saves).toBe(0);
 });
 test('pinch zoom anchors fingers, preserves browser scale and pans before page changes',async({page,browserName},info)=>{
  const s=await store();await setup(page,s);const stage=page.getByLabel('PDF drawing view',{exact:true});await stage.scrollIntoViewIfNeeded();const b=await stage.boundingBox(),middle={x:b.x+b.width/2,y:b.y+130};
  const zoom=()=>page.locator('.drawing-viewbar').evaluate(el=>parseInt([...el.querySelectorAll('span')].find(x=>x.textContent.endsWith('%')).textContent));const start=await zoom(),browserScale=await page.evaluate(()=>visualViewport.scale);
  const at=()=>page.locator('.drawing-sheet').evaluate((el,p)=>{const b=el.getBoundingClientRect();return{x:(p.x-b.x)/b.width,y:(p.y-b.y)/b.height};},middle);const anchor=await at();
  await drawingTouch(page,browserName,'touchStart',[{x:middle.x-25,y:middle.y},{x:middle.x+25,y:middle.y}]);for(let n=1;n<=5;n++){await drawingTouch(page,browserName,'touchMove',[{x:middle.x-25-5*n,y:middle.y},{x:middle.x+25+5*n,y:middle.y}]);await page.waitForTimeout(35);}await expect.poll(zoom).toBeGreaterThan(start*1.8);await expect.poll(async()=>Math.abs((await at()).x-anchor.x)).toBeLessThan(.025);await expect.poll(async()=>Math.abs((await at()).y-anchor.y)).toBeLessThan(.025);
  await drawingTouch(page,browserName,'touchEnd',[]);expect(await page.evaluate(()=>visualViewport.scale)).toBe(browserScale);await expect(page.getByLabel('Page number',{exact:true})).toHaveValue('1');
  await stage.evaluate(el=>el.scrollLeft=(el.scrollWidth-el.clientWidth)/2);const left=await stage.evaluate(el=>el.scrollLeft);await swipeDrawing(page,browserName,-65);expect(await stage.evaluate(el=>el.scrollLeft)).toBeGreaterThan(left);await expect(page.getByLabel('Page number',{exact:true})).toHaveValue('1');await stage.evaluate(el=>el.scrollLeft=el.scrollWidth);await swipeDrawing(page,browserName,-100);await expect(page.getByLabel('Page number',{exact:true})).toHaveValue('2');expect(s.saves).toBe(0);await page.locator('.drawing-viewer').screenshot({path:info.outputPath('gesture-view.png')});
 });
 test('pinch inward and cancellation do not switch pages or change saved markups',async({page,browserName})=>{
  const s=await store();await setup(page,s);await page.getByRole('button',{name:'Zoom in',exact:true}).click();await page.getByRole('button',{name:'Zoom in',exact:true}).click();const stage=page.getByLabel('PDF drawing view',{exact:true});await stage.scrollIntoViewIfNeeded();const b=await stage.boundingBox(),x=b.x+b.width/2,y=b.y+100,zoom=()=>page.locator('.drawing-viewbar').evaluate(el=>parseInt([...el.querySelectorAll('span')].find(x=>x.textContent.endsWith('%')).textContent));const initial=await zoom();
  await drawingTouch(page,browserName,'touchStart',[{x:x-60,y},{x:x+60,y}]);await drawingTouch(page,browserName,'touchMove',[{x:x-35,y},{x:x+35,y}]);await expect.poll(zoom).toBeLessThan(initial);await drawingTouch(page,browserName,'touchCancel',[]);await expect(page.getByLabel('Page number',{exact:true})).toHaveValue('1');expect(s.saves).toBe(0);expect(s.row.content.marks).toEqual([]);
 });
 test('markup tools do not treat drawing gestures as page swipes',async({page,browserName})=>{
  const s=await store();await setup(page,s);await page.getByRole('button',{name:'Edit',exact:true}).click();await page.getByRole('button',{name:'Pen',exact:true}).click();await page.getByRole('button',{name:'Close markups',exact:true}).click();await swipeDrawing(page,browserName,-100);await expect(page.getByLabel('Page number',{exact:true})).toHaveValue('1');if(browserName==='chromium')await expect.poll(()=>s.row.content.marks[0]?.kind).toBe('pen');
 });
});

for(const size of [{width:390,height:844},{width:844,height:390}])test(`compact phone full screen ${size.width}`,async({page},info)=>{
 await page.setViewportSize(size);const s=await store();await setup(page,s);await page.getByRole('button',{name:'Full screen',exact:true}).click();const stage=page.getByLabel('PDF drawing view',{exact:true});await expect.poll(async()=>(await stage.boundingBox()).height).toBeGreaterThan(size.height-180);await expect(page.getByRole('toolbar',{name:'Drawing modes'})).toBeHidden();await expect(page.getByRole('toolbar',{name:'Drawing tools'})).toBeHidden();await expect(page.getByRole('button',{name:'Next page',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Zoom in',exact:true})).toBeVisible();await page.screenshot({path:info.outputPath('compact-full-screen.png')});await page.getByRole('button',{name:'Tools',exact:true}).click();await expect(page.getByRole('button',{name:'Measure',exact:true})).toBeVisible();await page.getByRole('button',{name:'Tools',exact:true}).click();await expect(page.getByRole('toolbar',{name:'Drawing tools'})).toBeHidden();await page.getByRole('button',{name:'Exit full screen',exact:true}).click();await expect(page.locator('.drawing-viewer')).not.toHaveClass(/is-fullscreen/);await expect(page.getByRole('toolbar',{name:'Drawing modes'})).toBeVisible();
});

test('organizer desktop drag scrolls with wheel and at both edges without losing selected pages',async({page})=>{
 await page.setViewportSize({width:1100,height:850});const s=await store();s.bytes=await sample(24);await setup(page,s);await page.getByRole('button',{name:'Organize pages',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Organize pages',exact:true}),scroll=dialog.locator('.drawing-organizer-scroll');await dialog.getByRole('button',{name:'Page 2',exact:true}).click({modifiers:['Control']});const card=dialog.locator('[data-source-page="1"]'),b=await card.boundingBox(),box=await scroll.boundingBox();await page.mouse.move(b.x+b.width/2,b.y+35);await page.mouse.down();await page.mouse.move(b.x+b.width/2+15,b.y+50,{steps:5});await page.mouse.move(box.x+box.width/2,box.y+box.height/2,{steps:5});const before=await scroll.evaluate(el=>el.scrollTop);await page.mouse.wheel(0,180);await expect.poll(()=>scroll.evaluate(el=>el.scrollTop)).toBeGreaterThan(before);await expect(dialog.locator('.drawing-page-cards>div.selected')).toHaveCount(2);await page.mouse.move(box.x+box.width/2,box.y+box.height-10,{steps:5});const middle=await scroll.evaluate(el=>el.scrollTop);await expect.poll(()=>scroll.evaluate(el=>el.scrollTop)).toBeGreaterThan(middle+50);await page.mouse.move(box.x+box.width/2,box.y+8,{steps:5});const lower=await scroll.evaluate(el=>el.scrollTop);await expect.poll(()=>scroll.evaluate(el=>el.scrollTop)).toBeLessThan(lower);await page.keyboard.press('Escape');await page.mouse.up();expect(s.saves).toBe(0);
});

test.describe('organizer phone scrolling',()=>{test.use({hasTouch:true,viewport:{width:390,height:844}});
 test('a held selection and second finger scroll reliably, then moves at a scrolled destination',async({page,browserName},info)=>{
  const s=await store();s.bytes=await sample(24);s.row.content.scales['1']=load('drawing-model').calibrate([{x:0,y:0},{x:100,y:0}],10,'ft-in');const scale=JSON.stringify(s.row.content.scales);await setup(page,s);await page.getByRole('button',{name:'Organize pages',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Organize pages',exact:true}),scroll=dialog.locator('.drawing-organizer-scroll');await dialog.getByLabel('Select multiple',{exact:true}).check();await dialog.getByRole('button',{name:'Page 2',exact:true}).tap();const b=await scroll.boundingBox(),first={x:b.x+65,y:b.y+40},second={x:b.x+b.width-60,y:b.y+Math.min(b.height-25,200)};
  if(browserName==='chromium'){const cdp=await page.context().newCDPSession(page),touch=async(type,pts)=>cdp.send('Input.dispatchTouchEvent',{type,touchPoints:pts.map((p,i)=>({...p,id:i+1}))});await touch('touchStart',[first]);await touch('touchStart',[first,second]);for(let n=1;n<=6;n++)await touch('touchMove',[first,{x:second.x,y:second.y-n*20}]);await touch('touchEnd',[]);}else await scroll.evaluate((el,{first,second})=>{const dispatch=(type,points)=>{const event=new Event(type,{bubbles:true,cancelable:true});Object.assign(event,{touches:points.map((p,i)=>({...p,identifier:i+1,clientX:p.x,clientY:p.y})),changedTouches:[]});el.dispatchEvent(event);};dispatch('touchstart',[first]);dispatch('touchstart',[first,second]);dispatch('touchmove',[first,{x:second.x,y:second.y-120}]);dispatch('touchend',[]);},{first,second});
  await expect.poll(()=>scroll.evaluate(el=>el.scrollTop)).toBeGreaterThan(60);await expect(dialog.locator('.drawing-page-cards>div.selected')).toHaveCount(2);expect(s.saves).toBe(0);await dialog.getByRole('button',{name:'Move selected pages',exact:true}).tap();await dialog.getByRole('button',{name:'Move selected pages after page 20',exact:true}).scrollIntoViewIfNeeded();await dialog.getByRole('button',{name:'Move selected pages after page 20',exact:true}).tap();await expect.poll(()=>s.row.content.pageOrder?.join(',')).toBe([...Array.from({length:18},(_,i)=>i+3),1,2,21,22,23,24].join(','));expect(JSON.stringify(s.row.content.scales)).toBe(scale);await dialog.screenshot({path:info.outputPath('scrolled-organizer.png')});
 });
});

for(const width of [390,1440])test(`page jump field accepts clearing and multi-digit typing ${width}`,async({page})=>{
 await page.setViewportSize({width,height:1000});const s=await store();s.bytes=await sample(24);await setup(page,s);if(width===390){await page.getByRole('button',{name:'Full screen',exact:true}).click();await expect(page.locator('.drawing-viewer')).toHaveClass(/is-fullscreen/);}const input=page.getByLabel('Page number',{exact:true});await input.fill('');await expect(input).toHaveValue('');await input.pressSequentially('12');await expect(input).toHaveValue('12');await input.press('Enter');await expect(input).toHaveValue('12');if(width===390)await page.getByRole('button',{name:'Pages',exact:true}).click();await expect(page.getByRole('button',{name:'Page 12',exact:true})).toHaveAttribute('aria-current','page');await input.fill('');await input.pressSequentially('8');await input.blur();await expect(page.getByRole('button',{name:'Page 8',exact:true})).toHaveAttribute('aria-current','page');await input.fill('999');await input.blur();await expect(input).toHaveValue('8');await input.fill('');await input.blur();await expect(input).toHaveValue('8');if(width===1440){await input.fill('3');await input.press('Escape');await expect(input).toHaveValue('8');}expect(s.saves).toBe(0);
});

// Release 1008: booby-trapped drawing PDFs (scan finding "Structurally extreme drawing PDFs can persistently
// exhaust administrator browsers").
test('drawing size limits allow real sheets and refuse extreme page counts and sizes',()=>{
 const m=load('drawing-model');
 expect(m.drawingPageCountProblem(1000)).toBe('');expect(m.drawingPageCountProblem(1001)).toBe('This PDF has 1,001 pages. Drawings are limited to 1,000 pages.');
 expect(m.drawingPageSizeProblem(3024,2160,1)).toBe('');expect(m.drawingPageSizeProblem(14400,2592,1)).toBe('');
 expect(m.drawingPageSizeProblem(14401,800,4)).toBe("Page 4 is larger than 200 inches, so it can't be shown safely.");expect(m.drawingPageSizeProblem(0,800,1)).not.toBe('');
 expect(m.thumbnailScale(612,792)*612).toBeCloseTo(110);expect(m.thumbnailScale(20,14000)*14000).toBeCloseTo(440);
});
test('snapping stops at its line limit on extreme pages',async()=>{
 const snap=load('drawing-snap'),OPS={save:1,restore:2,transform:3,constructPath:4},fnArray=[],argsArray=[];
 for(let i=0;i<5000;i++){fnArray.push(OPS.constructPath);argsArray.push([0,[new Float32Array([0,0,i,1,10,i])]]);}
 expect(await snap.drawingSegments({getOperatorList:async()=>({fnArray,argsArray})},OPS,1200)).toHaveLength(1200);
 expect(snap.DRAWING_SNAP_MAX_SEGMENTS).toBeGreaterThanOrEqual(500000);
});
test('oversized pages and too many pages are refused before upload',async({page})=>{
 const s=await store();await setup(page,s);const input=page.locator('.drawing-heading input[type=file]');
 const huge=await PDFDocument.create();huge.addPage([612,792]);huge.addPage([15000,800]);
 await input.setInputFiles({name:'Huge sheet.pdf',mimeType:'application/pdf',buffer:Buffer.from(await huge.save())});
 await expect(page.getByRole('alert')).toContainText('Page 2 is larger than 200 inches');expect(s.uploaded).toBeUndefined();
 const many=await PDFDocument.create();for(let i=0;i<1001;i++)many.addPage([612,792]);
 await input.setInputFiles({name:'Many pages.pdf',mimeType:'application/pdf',buffer:Buffer.from(await many.save())});
 await expect(page.getByRole('alert')).toContainText('Drawings are limited to 1,000 pages.');expect(s.uploaded).toBeUndefined();
});
for(const theme of ['light','dark'])for(const width of [390,1440])test(`a saved drawing with an oversized page shows a notice instead of drawing it, and thin pages keep small thumbnails ${theme} ${width}`,async({page},info)=>{
 await page.setViewportSize({width,height:1000});await page.addInitScript(t=>localStorage.setItem('jgcPortalTheme',t),theme);
 const pdf=await PDFDocument.create(),font=await pdf.embedFont(StandardFonts.Helvetica),first=pdf.addPage([612,792]);
 first.drawText('NORMAL PAGE',{x:70,y:700,size:18,font});first.drawLine({start:{x:70,y:600},end:{x:370,y:600},thickness:2,color:rgb(0,0,0)});
 pdf.addPage([16000,800]);pdf.addPage([20,14000]);
 const s=await store();s.bytes=Buffer.from(await pdf.save());await setup(page,s);const pageNumber=page.getByLabel('Page number',{exact:true}),sheet=page.locator('.drawing-sheet canvas');
 await pageNumber.fill('2');await pageNumber.press('Enter');
 await expect(page.locator('.drawing-page-problem')).toHaveText("Page 2 is larger than 200 inches, so it can't be shown safely.");
 await expect.poll(()=>sheet.evaluate(c=>c.width)).toBe(0);expect(await sheet.evaluate(c=>c.getBoundingClientRect().height)).toBeLessThan(5);await page.locator('.drawing-workspace').screenshot({path:info.outputPath(`oversized-page-${theme}-${width}.png`)});
 await pageNumber.fill('3');await pageNumber.press('Enter');await expect(page.locator('.drawing-page-problem')).toHaveCount(0);await expect.poll(()=>sheet.evaluate(c=>c.width)).toBeGreaterThan(0);
 if(width>900)for(const label of ['Page 2','Page 3'])expect(await page.getByRole('button',{name:label,exact:true}).locator('canvas').evaluate(c=>c.height)).toBeLessThanOrEqual(440);
 await pageNumber.fill('1');await pageNumber.press('Enter');await expect(page.locator('.drawing-page-problem')).toHaveCount(0);await expect.poll(()=>sheet.evaluate(c=>c.width)).toBeGreaterThan(0);
});