const {test,expect}=require('@playwright/test');
const fs=require('node:fs'),path=require('node:path'),{pathToFileURL}=require('node:url'),ts=require('../estimating-app/node_modules/typescript');
const cache={};
function load(name){if(cache[name])return cache[name];const m={exports:{}};Function('exports','module','require',ts.transpileModule(fs.readFileSync(path.resolve(__dirname,'../estimating-app/lib/'+name+'.ts'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(m.exports,m,n=>n.startsWith('.')?load(n.replace(/^\.\//,'')):require('../estimating-app/node_modules/'+n));cache[name]=m.exports;return m.exports;}
const w=load('job-warranty'),merge=load('estimator-state-sync').mergeConcurrentEstimatorState;
function fixture(warranty){const state=load('estimator-data').createDefaultState();state.clients=[{id:'client',name:'Example Client',contact:'',email:'',phone:'',contacts:[],sites:[],notes:''}];state.quotes=[];state.priceBook=[];state.jobs=[{id:'job',jobNumber:'26999',quoteId:'',clientId:'client',project:'Washroom and Control Room',status:'Active',portalJobId:'portal-job',portalActive:true,portalCustomer:'Example Client',portalSiteName:'Main Office',portalAddress:'123 Example Street, Cornwall',projectManager:'Test Admin',startDate:'2026-10-05',targetEndDate:'2026-11-27',acceptedRevenue:0,originalCostBudget:0,approvedRevenueChanges:0,approvedCostChanges:0,estimateToComplete:0,acceptedAt:'2026-10-01T12:00:00Z',costs:[],notes:'',...(warranty?{warranty}:{})}];return state;}
const seed=()=>w.createWarranty({...w.warrantyDefaults(fixture().jobs[0],fixture()),completionDate:'2026-08-25',issueDate:'2026-08-28'},'Test Admin');
async function setup(page,warranty){let state=fixture(warranty);const saves=[];await page.route('**/api/**',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({actuals:[],jobs:[],rows:[]})}));await page.route('**/api/state',async r=>{if(r.request().method()==='PUT'){state=r.request().postDataJSON().state;saves.push(structuredClone(state));return r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({saved:true,updatedAt:new Date().toISOString()})});}return r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({state,updatedAt:'2026-10-01T12:00:00Z'})});});await page.goto('/estimating/index.html?dev=1&view=jobs&job=26999');await expect(page.locator('.job-detail-page')).toContainText('26999');await page.getByRole('tab',{name:'Warranty',exact:true}).click();await expect(page.locator('.job-warranty')).toBeVisible();return saves;}
async function saveAndDownload(page,testInfo,filename){await expect(page.getByRole('button',{name:'Download PDF',exact:false})).toBeEnabled();await page.getByRole('button',{name:'Download PDF',exact:false}).click();const dialog=page.getByRole('dialog',{name:'Download warranty PDF'});await expect(dialog).toBeVisible();if(filename)await dialog.getByLabel('Warranty PDF filename').fill(filename);const event=page.waitForEvent('download');await dialog.getByRole('button',{name:'⇩ Download warranty PDF',exact:true}).click();const download=await event;await download.saveAs(testInfo.outputPath(download.suggestedFilename()));return {dialog,download};}
async function pdfTexts(pdfPath){const pdfjs=await import(pathToFileURL(path.resolve(__dirname,'../estimating-app/node_modules/pdfjs-dist/legacy/build/pdf.mjs')).href);const pdf=await pdfjs.getDocument({data:new Uint8Array(fs.readFileSync(pdfPath)),disableWorker:true}).promise;const texts=[];for(let i=1;i<=pdf.numPages;i++){const page=await pdf.getPage(i),content=await page.getTextContent();texts.push(content.items.map(v=>v.str).join(' '));}return texts;}

test('warranty date and filename handling preserve ordinals, reject impossible dates and sanitize Windows paths',()=>{
 expect(w.warrantyDate('2026-08-25')).toBe('August 25th, 2026');expect(w.warrantyDate('2026-10-11')).toBe('October 11th, 2026');expect(w.warrantyDate('2028-02-29')).toBe('February 29th, 2028');expect(w.warrantyDateValid('2026-02-29')).toBe(false);expect(w.warrantyDateValid('2026-04-31')).toBe(false);expect(w.warrantyFilename('Client / Division','Door: upgrades')).toBe('Client - Division - Door- upgrades - JGC Warranty.pdf');expect(w.cleanWarrantyFilename('file.PDF')).toBe('file.pdf');
});
test('locking, reopening and autosaving a revision preserve every issued warranty and reject stale edits or removed history',()=>{
 const draft=seed(),locked=w.lockWarranty(draft,'First admin','Example.pdf'),next=w.reopenWarranty(locked,'Second admin');next.fields.owner='Updated Owner';
 const state=value=>fixture(value);expect(w.warrantyPersistenceError(state(draft),state(locked))).toBe('');expect(w.warrantyPersistenceError(state(locked),state(next))).toBe('');expect(locked.revisions[0].fields.owner).toBe('Example Client');expect(next.revision).toBe(1);
 const second=w.lockWarranty(next,'Second admin','Rev 1.pdf');expect(w.warrantyPersistenceError(state(next),state(second))).toBe('');expect(second.revisions).toHaveLength(2);expect(second.revisions[0]).toEqual(locked.revisions[0]);
 expect(w.warrantyPersistenceError(state(locked),state({...locked,fields:{...locked.fields,owner:'Overwrite locked'}}))).not.toBe('');expect(w.warrantyPersistenceError(state(second),state({...w.reopenWarranty(second,'Admin'),revisions:[]}))).toContain('history');
 expect(w.warrantyPersistenceError(state(locked),state(draft))).toContain('history');expect(()=>w.lockWarranty(locked,'Admin','bad.pdf')).toThrow('locked');expect(()=>w.reopenWarranty(draft,'Admin')).toThrow('editable');
});
test('competing warranty edits are atomic conflicts; unrelated job changes still merge and legacy jobs retain their data',()=>{
 const base=fixture(seed()),local=structuredClone(base),remote=structuredClone(base);local.jobs[0].warranty.fields.owner='First admin';remote.jobs[0].warranty.fields.location='Other site';expect(merge(base,local,remote).state).toBeNull();expect(merge(base,local,remote).conflicts).toContain('jobs[job].warranty');remote.jobs[0].warranty=base.jobs[0].warranty;remote.jobs[0].notes='Unrelated notes';const result=merge(base,local,remote);expect(result.state.jobs[0].notes).toBe('Unrelated notes');expect(w.warrantyPersistenceError(remote,result.state)).toBe('');expect(load('estimator-data').normalizeAppState(base).jobs[0].warranty).toEqual(base.jobs[0].warranty);expect(load('estimator-data').normalizeAppState(fixture()).jobs[0].warranty).toBeUndefined();
});
test('all warranty text, signature and long field values survive PDF export within page bounds',async({},testInfo)=>{
 const logoBytes=fs.readFileSync(path.resolve(__dirname,'../estimating-app/public/jgc-warranty-logo-v1.png')),signatureBytes=fs.readFileSync(path.resolve(__dirname,'../estimating-app/public/jgc-warranty-signature-v1.png'));
 for(const long of [false,true]){
  const warranty=seed();if(long)warranty.fields={...warranty.fields,owner:'Owner Division '.repeat(17).trim(),building:'Building '.repeat(19).trim(),location:'123 Very Long Street - '.repeat(20).trim(),project:'Control Room '.repeat(19).trim(),ownerOfficial:'Authorized Owner Representative '.repeat(5).trim(),ownerDate:'2026-09-01'};
  const bytes=await load('job-warranty-pdf').buildWarrantyPdf({warranty,logoBytes,signatureBytes}),file=testInfo.outputPath(long?'long-warranty.pdf':'template-warranty.pdf');fs.writeFileSync(file,bytes);const pdf=await require('../estimating-app/node_modules/pdf-lib').PDFDocument.load(bytes);expect(pdf.getPageCount()).toBe(2);const texts=await pdfTexts(file),flat=texts.join(' ').replace(/\s+/g,' ');
  for(const term of [w.warrantyTemplateV1.coverage,...w.warrantyTemplateV1.conditions,w.warrantyTemplateV1.acceptance])expect(flat).toContain(term);
  expect(texts[0]).toContain('FIELD WARRANTY');expect(texts[1]).toContain('Warranty Conditions - Continued');expect(flat).toContain('Jeff Vandrish');expect(flat).toContain('August 28th, 2026');expect(flat).not.toContain('Lancaster');
 }
});
test('new warranty prefills job details, autosaves inline edits and blocks incomplete PDF downloads',async({page})=>{
 const saves=await setup(page);await expect(page.getByRole('textbox',{name:'Owner',exact:true})).toHaveValue('Example Client');await expect(page.getByRole('textbox',{name:'Location',exact:true})).toHaveValue('123 Example Street, Cornwall');await page.getByRole('button',{name:'Download PDF',exact:false}).click();await expect(page.getByRole('dialog')).toHaveCount(0);await expect(page.getByLabel('Date of completion',{exact:true})).toHaveAttribute('aria-invalid','true');await page.getByLabel('Date of completion',{exact:true}).fill('2026-09-30');await page.getByRole('textbox',{name:'Building',exact:true}).fill('B30149');await expect.poll(()=>saves.at(-1)?.jobs[0].warranty?.fields.building).toBe('B30149');await page.reload();await page.getByRole('tab',{name:'Warranty',exact:true}).click();await expect(page.getByRole('textbox',{name:'Building',exact:true})).toHaveValue('B30149');await expect(page.getByLabel('Date of completion',{exact:true})).toHaveValue('2026-09-30');
});
test('named download, Done prompt, locking, reopening and historical downloads preserve the exact issued version',async({page},testInfo)=>{
 const saves=await setup(page,seed());const {dialog,download}=await saveAndDownload(page,testInfo,'Custom warranty');expect(download.suggestedFilename()).toBe('Custom warranty.pdf');await dialog.getByRole('button',{name:'Done',exact:true}).click();await page.getByRole('dialog',{name:'Lock warranty Revision 0?'}).getByRole('button',{name:'Yes — lock this version'}).click();await expect(page.locator('.warranty-status')).toContainText('Rev 0 · Locked');await expect.poll(()=>saves.at(-1)?.jobs[0].warranty?.status).toBe('Locked');await expect(page.getByRole('textbox',{name:'Owner',exact:true})).toHaveAttribute('readonly','');const prior=structuredClone(saves.at(-1).jobs[0].warranty.revisions[0]);
 await page.getByRole('button',{name:'Reopen warranty'}).click();await page.getByRole('dialog',{name:'Reopen as Revision 1?'}).getByRole('button',{name:'Create Revision 1'}).click();await page.getByRole('textbox',{name:'Owner',exact:true}).fill('Updated Owner');await expect.poll(()=>saves.at(-1)?.jobs[0].warranty?.fields.owner).toBe('Updated Owner');expect(saves.at(-1).jobs[0].warranty.revisions[0]).toEqual(prior);await page.reload();await page.getByRole('tab',{name:'Warranty',exact:true}).click();await expect(page.locator('.warranty-status')).toContainText('Rev 1 · Draft');await page.getByRole('button',{name:'History (1)',exact:true}).click();await page.getByRole('button',{name:'View revision 0'}).click();const preview=page.getByRole('dialog',{name:'Warranty Revision 0'});await expect(preview.getByRole('textbox',{name:'Owner',exact:true})).toHaveValue('Example Client');await expect(preview.getByRole('textbox',{name:'Owner',exact:true})).toHaveAttribute('readonly','');await preview.getByRole('button',{name:'Download this revision'}).click();const historical=page.getByRole('dialog',{name:'Download warranty PDF'});await expect(historical.getByLabel('Warranty PDF filename')).toHaveValue('Custom warranty.pdf');const event=page.waitForEvent('download');await historical.getByRole('button',{name:'⇩ Download warranty PDF',exact:true}).click();const historyPdf=await event;await historyPdf.saveAs(testInfo.outputPath('historical.pdf'));const text=(await pdfTexts(testInfo.outputPath('historical.pdf'))).join(' ');expect(text).toContain('Example Client');expect(text).not.toContain('Updated Owner');await historical.getByRole('button',{name:'Done'}).click();await expect(page.getByRole('dialog')).toHaveCount(0);expect(saves.at(-1).jobs[0].warranty.revisions).toEqual([prior]);
});
test('closing downloads without a PDF keeps editing; choosing No after download never locks the warranty',async({page},testInfo)=>{
 const saves=await setup(page,seed());await page.getByRole('button',{name:'Download PDF',exact:false}).click();let dialog=page.getByRole('dialog',{name:'Download warranty PDF'});await expect(dialog.getByLabel('Warranty PDF filename')).toHaveValue('Example Client - Washroom and Control Room - JGC Warranty.pdf');await dialog.getByRole('button',{name:'Done'}).click();await expect(page.getByRole('dialog')).toHaveCount(0);expect(saves.every(s=>s.jobs[0].warranty.status==='Draft')).toBe(true);({dialog}=await saveAndDownload(page,testInfo));await dialog.getByRole('button',{name:'Done'}).click();await page.getByRole('button',{name:'No — keep editing'}).click();await expect(page.locator('.warranty-status')).toContainText('Draft');await expect(page.getByRole('textbox',{name:'Owner',exact:true})).not.toHaveAttribute('readonly','');
});
for(const theme of ['light','dark'])for(const width of [1440,390])test(`warranty ${theme} ${width}: readable inline form, contained dialogs and PDF`,async({page},testInfo)=>{
 await page.setViewportSize({width,height:1000});await page.addInitScript(t=>localStorage.setItem('jgcPortalTheme',t),theme);await setup(page,seed());expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await expect(page.getByRole('tab',{name:'Warranty'})).toBeVisible();const tabs=await page.getByRole('tab').allTextContents();expect(tabs.indexOf('Warranty')).toBe(tabs.indexOf('Drawings')+1);await page.locator('.warranty-preview').screenshot({path:testInfo.outputPath(`warranty-${theme}-${width}.png`)});await page.getByRole('button',{name:'Download PDF',exact:false}).click();const dialog=page.getByRole('dialog',{name:'Download warranty PDF'});await expect(dialog).toBeVisible();const bounds=await dialog.boundingBox();expect(bounds.x).toBeGreaterThanOrEqual(0);expect(bounds.x+bounds.width).toBeLessThanOrEqual(width);await page.keyboard.press('Escape');await expect(dialog).toHaveCount(0);expect(await page.evaluate(()=>document.body.style.overflow)).not.toBe('hidden');await expect(page.getByRole('button',{name:'Download PDF',exact:false})).toBeFocused();
});
