const {test,expect}=require('@playwright/test');
const fs=require('node:fs'),path=require('node:path'),ts=require('../estimating-app/node_modules/typescript');
const {PDFDocument,StandardFonts,rgb,degrees}=require('../estimating-app/node_modules/pdf-lib');
const cache={};function load(name){if(cache[name])return cache[name];const m={exports:{}};Function('exports','module','require',ts.transpileModule(fs.readFileSync(path.resolve(__dirname,'../estimating-app/lib/'+name+'.ts'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(m.exports,m,n=>n.startsWith('.')?load(n.replace(/^\.\//,'')):require('../estimating-app/node_modules/'+n));return cache[name]=m.exports;}
async function sample(){const pdf=await PDFDocument.create(),font=await pdf.embedFont(StandardFonts.Helvetica);for(let n=1;n<=2;n++){const p=pdf.addPage([612,792]);p.drawText('JGC TEST DRAWING PAGE '+n,{x:70,y:700,size:18,font});p.drawLine({start:{x:70,y:600},end:{x:370,y:600},thickness:2,color:rgb(0,0,0)});if(n===2){p.setCropBox(30,40,540,700);p.setRotation(degrees(90));}}return Buffer.from(await pdf.save());}
function state(){const s=load('estimator-data').createDefaultState();s.clients=[];s.quotes=[];s.priceBook=[];s.jobs=[{id:'job',jobNumber:'26999',quoteId:'',clientId:'',project:'Drawing review',status:'Active',portalJobId:'portal-job',acceptedRevenue:0,originalCostBudget:0,approvedRevenueChanges:0,approvedCostChanges:0,estimateToComplete:0,acceptedAt:'2026-10-01',costs:[],notes:''}];return s;}
async function setup(page,store){await page.route('**/api/**',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({state:state(),jobs:[],actuals:[],rows:[],saved:true})}));await page.route('https://drawings.example.test/**',async r=>{const req=r.request(),u=new URL(req.url());if(u.pathname.startsWith('/storage/')){if(req.method()==='POST'){store.uploaded=true;return r.fulfill({status:200,contentType:'application/json',body:'{"Key":"ok"}'});}return r.fulfill({status:200,contentType:'application/pdf',body:store.bytes});}if(u.pathname.endsWith('/job_drawings')){if(req.method()==='GET')return r.fulfill({status:200,contentType:'application/json',body:JSON.stringify([store.row])});if(req.method()==='PATCH'){const v=req.postDataJSON();if(u.searchParams.get('revision')!=='eq.'+store.row.revision)return r.fulfill({status:200,contentType:'application/json',body:'null'});store.row={...store.row,...v,updated_at:new Date().toISOString()};store.saves++;return r.fulfill({status:200,contentType:'application/json',body:JSON.stringify(store.row)});}if(req.method()==='POST'){const v=req.postDataJSON();store.row={...store.row,...v,object_path:v.id+'/original.pdf'};return r.fulfill({status:201,contentType:'application/json',body:JSON.stringify(store.row)});}}return r.fulfill({status:404,body:'{}'});});await page.goto('/estimating/index.html?dev=1&view=jobs&job=26999');await expect(page.locator('.job-detail-page')).toContainText('26999');await page.evaluate(()=>{window.__drawingBaselineWidth=document.documentElement.scrollWidth;window.createJgcSupabaseClient=()=>window.supabase.createClient('https://drawings.example.test','public-test-key',{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});});await page.getByRole('tab',{name:'Drawings',exact:true}).click();await expect(page.getByLabel('Select drawing').locator('option')).toHaveCount(2);await page.getByLabel('Select drawing').selectOption(store.row.id);await expect(page.locator('.drawing-overlay')).toBeVisible();expect(await page.locator('.drawing-sheet canvas').evaluate(c=>c.width)).toBeGreaterThan(0);}
async function store(){return{bytes:await sample(),saves:0,row:{id:'aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa',job_id:'job',title:'Architectural drawing',file_name:'original.pdf',object_path:'aaaaaaaa-aaaa-4aaa-aaaa-aaaaaaaaaaaa/original.pdf',revision:1,content:load('drawing-model').emptyDrawing(),created_at:'2026-10-01',updated_at:'2026-10-01'}};}
async function drag(page,x=70,y=90,dx=130,dy=0){await page.locator('.drawing-overlay').evaluate(svg=>scrollTo(0,scrollY+svg.getBoundingClientRect().top-240));const b=await page.locator('.drawing-overlay').boundingBox();await page.mouse.move(b.x+x,b.y+y);await page.mouse.down();await page.mouse.move(b.x+x+dx,b.y+y+dy,{steps:5});await page.mouse.up();}
async function distance(page,x=70,y=150,dx=130,dy=0){await page.locator('.drawing-overlay').evaluate(svg=>scrollTo(0,scrollY+svg.getBoundingClientRect().top-240));const b=await page.locator('.drawing-overlay').boundingBox();await page.mouse.click(b.x+x,b.y+y);await page.mouse.move(b.x+x+dx,b.y+y+dy);await page.mouse.click(b.x+x+dx,b.y+y+dy);}
async function text(page,value='As-built: conduit relocated'){await page.getByRole('button',{name:'Edit',exact:true}).click();await page.getByRole('button',{name:'Text',exact:true}).click();await page.getByLabel('Markup text',{exact:true}).fill(value);await page.locator('.drawing-overlay').evaluate(svg=>scrollTo(0,scrollY+svg.getBoundingClientRect().top-240));const b=await page.locator('.drawing-overlay').boundingBox();await page.mouse.click(b.x+100,b.y+120);}
test('known distance, area, perimeter and invalid scale calculations',()=>{const m=load('drawing-model'),p=[{x:0,y:0},{x:100,y:0}],s=m.calibrate(p,10,'ft-in');expect(s.unitsPerPoint).toBe(.1);expect(m.measurement({kind:'distance',points:p},s)).toBe('10 ft 0 in');expect(m.measurement({kind:'area',points:[{x:0,y:0},{x:100,y:0},{x:100,y:100},{x:0,y:100}]},s)).toBe('100.00 sq ft');expect(m.measurement({kind:'perimeter',points:[...p,{x:100,y:100}]},s)).toBe('34 ft 1.6875 in');for(const n of [0,-5,NaN,Infinity])expect(()=>m.calibrate(p,n,'ft')).toThrow();expect(()=>m.calibrate([{x:0,y:0},{x:0,y:0}],5,'ft')).toThrow();});
test('shared annotations reopen on a second device and preserve original',async({page,browser},info)=>{const s=await store();await setup(page,s);await page.getByLabel('Markup layer').selectOption('As-built');await text(page);await expect.poll(()=>s.row.content.marks.length).toBe(1);await expect(page.getByRole('status').filter({hasText:'All drawing changes saved'})).toBeVisible();const context=await browser.newContext(),phone=await context.newPage();await phone.setViewportSize({width:390,height:844});await setup(phone,s);await expect(phone.locator('.drawing-overlay text')).toContainText('conduit relocated');expect(s.row.content.marks[0].layer).toBe('As-built');const download=page.waitForEvent('download');await page.getByRole('button',{name:'Download original'}).click();const originalFile=await download;await originalFile.saveAs(info.outputPath('downloaded-original.pdf'));expect(fs.readFileSync(info.outputPath('downloaded-original.pdf')).equals(s.bytes)).toBe(true);const original=await PDFDocument.load(s.bytes);expect(original.getPageCount()).toBe(2);await phone.evaluate(()=>scrollTo(0,0));await phone.screenshot({fullPage:true,path:info.outputPath('phone.png')});await context.close();});
test('calibration enables measurement and survives zoom, page changes and rotation',async({page})=>{const s=await store();await setup(page,s);await page.getByRole('button',{name:'Measure',exact:true}).click();await expect(page.getByRole('button',{name:'Distance',exact:true})).toBeDisabled();await page.getByRole('button',{name:'Set scale',exact:true}).click();await drag(page);await page.getByLabel('Known length').fill('10');await page.getByRole('button',{name:'Apply page scale'}).click();await expect(page.getByRole('button',{name:'Distance',exact:true})).toBeEnabled();await distance(page,70,150,130);await expect(page.locator('.drawing-overlay text')).toContainText('10 ft 0 in');await expect.poll(()=>s.row.content.marks.length).toBe(1);const points=JSON.stringify(s.row.content.marks[0].points);await page.getByRole('button',{name:'Rotate view'}).click();await page.getByRole('button',{name:'Fit width'}).click();await expect(page.locator('.drawing-overlay text')).toContainText('10 ft 0 in');expect(JSON.stringify(s.row.content.marks[0].points)).toBe(points);await page.getByRole('button',{name:'Page 2',exact:true}).click();await expect(page.getByRole('button',{name:'Distance',exact:true})).toBeDisabled();await page.getByRole('button',{name:'Page 1',exact:true}).click();await expect(page.getByRole('button',{name:'Distance',exact:true})).toBeEnabled();});
test('undo redo, page-specific marks and PDF export on cropped rotated originals',async({page},info)=>{const s=await store();await setup(page,s);await text(page,'Page one review');await page.getByRole('button',{name:'Undo',exact:true}).click();await expect(page.locator('.drawing-overlay text')).toHaveCount(0);await page.getByRole('button',{name:'Redo',exact:true}).click();await expect(page.locator('.drawing-overlay text')).toContainText('Page one review');await expect.poll(()=>s.row.content.marks.length).toBe(1);await page.getByRole('button',{name:'Page 2',exact:true}).click();await expect(page.locator('.drawing-overlay text')).toHaveCount(0);await text(page,'Page two as-built');await expect.poll(()=>s.row.content.marks.length).toBe(2);const download=page.waitForEvent('download');await page.getByRole('button',{name:'Download marked PDF'}).click();const file=await download;await file.saveAs(info.outputPath('marked.pdf'));const exported=await PDFDocument.load(fs.readFileSync(info.outputPath('marked.pdf'))),original=await PDFDocument.load(s.bytes);expect(exported.getPageCount()).toBe(2);expect(exported.getPage(0).node.Annots().size()).toBe(1);expect(exported.getPage(1).node.Annots().size()).toBe(1);expect(exported.getPage(1).getCropBox()).toEqual(original.getPage(1).getCropBox());expect(exported.getPage(1).getRotation()).toEqual(original.getPage(1).getRotation());fs.writeFileSync(info.outputPath('original.pdf'),s.bytes);fs.writeFileSync(info.outputPath('markups.json'),JSON.stringify(s.row.content));await page.locator('.drawing-sheet').screenshot({path:info.outputPath('rotated-screen.png')});});
test('concurrent edits stop autosave and offer recovery without overwriting newer data',async({page})=>{const s=await store();await setup(page,s);s.row.revision=2;await text(page,'Unsaved local note');await expect(page.getByRole('alert')).toContainText('another device');expect(s.row.content.marks.length).toBe(0);await expect(page.getByRole('button',{name:'Recover unsaved markups'})).toBeVisible();await expect(page.getByRole('button',{name:'Text',exact:true})).toBeDisabled();});
for(const theme of ['light','dark'])for(const width of [390,1440])test(`drawing workspace ${theme} ${width}`,async({page},info)=>{await page.setViewportSize({width,height:1000});await page.addInitScript(t=>localStorage.setItem('jgcPortalTheme',t),theme);const s=await store();await setup(page,s);const dimensions=await page.evaluate(()=>({baseline:window.__drawingBaselineWidth,scroll:document.documentElement.scrollWidth,width:innerWidth,offenders:[...document.querySelectorAll('body *')].filter(e=>!e.closest('.drawing-stage')&&e.getBoundingClientRect().right>innerWidth).map(e=>({class:e.className,width:e.getBoundingClientRect().width,right:e.getBoundingClientRect().right})).slice(0,12)}));expect(dimensions.scroll,JSON.stringify(dimensions)).toBeLessThanOrEqual(dimensions.width);await expect(page.locator('html')).toHaveAttribute('data-jgc-theme',theme);await page.evaluate(()=>scrollTo(0,0));await page.screenshot({fullPage:true,path:info.outputPath(`drawing-${theme}-${width}.png`)});});
test('upload accepts PDF and keeps source immutable',async({page})=>{const s=await store();await setup(page,s);await page.locator('.drawing-heading input[type=file]').setInputFiles({name:'New drawing.pdf',mimeType:'application/pdf',buffer:s.bytes});await expect.poll(()=>s.uploaded).toBe(true);await expect(page.getByLabel('Drawing title')).toHaveValue('New drawing');});

test('highlight and comment edits are saved and included in marked export',async({page},info)=>{const s=await store();await setup(page,s);await page.getByRole('button',{name:'Edit',exact:true}).click();await page.getByRole('button',{name:'Highlight',exact:true}).click();await drag(page,70,90,130,20);await page.getByLabel('Edit selected comment').fill('Verify existing opening');await expect.poll(()=>s.row.content.marks[0]?.text).toBe('Verify existing opening');await text(page,'Updated text');await page.getByLabel('Edit selected comment').fill('Corrected note');await expect(page.locator('.drawing-overlay text')).toContainText('Corrected note');const pending=page.waitForEvent('download');await page.getByRole('button',{name:'Download marked PDF'}).click();const d=await pending;await d.saveAs(info.outputPath('highlight.pdf'));expect(s.row.content.marks[0].kind).toBe('highlight');});
test('invalid and oversized files are rejected before upload',async({page})=>{const s=await store();await setup(page,s);await page.locator('.drawing-heading input[type=file]').setInputFiles({name:'broken.pdf',mimeType:'application/pdf',buffer:Buffer.from('not a pdf')});await expect(page.getByRole('alert')).toBeVisible();expect(s.uploaded).toBeUndefined();});
test('drawing save status uses the Estimate Desk indicator and refresh reads latest record',async({page})=>{const s=await store();await setup(page,s);await text(page,'Save indicator check');await expect.poll(()=>s.saves).toBeGreaterThan(0);await expect(page.locator('.save-indicator')).toContainText('All changes saved');s.row={...s.row,title:'Updated from another device',revision:s.row.revision+1};await page.getByRole('button',{name:'Refresh drawings'}).click();await expect(page.getByLabel('Drawing title')).toHaveValue('Updated from another device');});
test('interrupted markup recovery restores only against its original server revision',async({page})=>{const s=await store();await setup(page,s);const content={version:1,marks:[{id:'recover',page:1,kind:'text',points:[{x:80,y:650}],color:'#d62828',text:'Recovered site note',author:'Test Admin',createdAt:'2026-10-01T12:00:00Z',layer:'As-built',rotation:0}],scales:{}};await page.evaluate(({id,content})=>localStorage.setItem('jgc-drawing-recovery-'+id,JSON.stringify({content,title:'Recovered drawing',baseRevision:1})),{id:s.row.id,content});page.once('dialog',d=>d.accept());await setup(page,s);await expect(page.locator('.drawing-overlay text')).toContainText('Recovered site note');await expect.poll(()=>s.row.content.marks[0]?.text).toBe('Recovered site note');expect(await page.evaluate(id=>localStorage.getItem('jgc-drawing-recovery-'+id),s.row.id)).toBeNull();});

test('area and perimeter finish multi-point outlines and save correct measurements',async({page})=>{const s=await store();await setup(page,s);await page.getByRole('button',{name:'Measure',exact:true}).click();await page.getByRole('button',{name:'Set scale',exact:true}).click();await drag(page,70,90,100);await page.getByLabel('Known length').fill('10');await page.getByRole('button',{name:'Apply page scale'}).click();for(const tool of ['Area','Perimeter']){await page.getByRole('button',{name:tool,exact:true}).click();await page.locator('.drawing-overlay').evaluate(svg=>scrollTo(0,scrollY+svg.getBoundingClientRect().top-240));const b=await page.locator('.drawing-overlay').boundingBox();for(const [x,y] of [[70,100],[170,100],[170,200],[70,200]])await page.mouse.click(b.x+x,b.y+y);await page.getByRole('button',{name:'Finish '+tool.toLowerCase(),exact:true}).click();}await expect(page.locator('.drawing-overlay text')).toContainText(['100.00 sq ft','40 ft 0 in']);await expect.poll(()=>s.row.content.marks.length).toBe(2);});
test('six scale units, imperial fractions and legacy feet remain compatible',()=>{
 const m=load('drawing-model'),points=[{x:0,y:0},{x:100,y:0}];
 for(const [unit,expected] of [['ft','12.50 ft'],['in','12.50 in'],['ft-in','12 ft 6 in'],['m','12.500 m'],['cm','12.50 cm'],['mm','12.50 mm']])expect(m.measurement({kind:'distance',points},m.calibrate(points,12.5,unit))).toBe(expected);
 expect(m.measurement({kind:'distance',points},{unit:'ft',unitsPerPoint:.125,reference:points,knownLength:12.5})).toBe('12 ft 6 in');
 expect(()=>m.drawingPageOrder({pageOrder:[2,2]},2)).toThrow();
});
test('bottom scroll advances and top scroll returns without skipping pages',async({page})=>{
 const s=await store();await setup(page,s);
 const stage=page.getByLabel('PDF drawing view',{exact:true});await stage.scrollIntoViewIfNeeded();await stage.evaluate(el=>el.scrollTop=el.scrollHeight);
 const b=await stage.boundingBox();await page.mouse.move(b.x+b.width/2,b.y+b.height/2);await page.mouse.wheel(0,220);
 await expect(page.getByLabel('Page number',{exact:true})).toHaveValue('2');
 await page.waitForTimeout(900);await stage.evaluate(el=>el.scrollTop=0);await page.mouse.wheel(0,-220);
 await expect(page.getByLabel('Page number',{exact:true})).toHaveValue('1');await page.waitForTimeout(900);await page.mouse.wheel(0,-220);await expect(page.getByLabel('Page number',{exact:true})).toHaveValue('1');
});
test('review stamps are editable, autosave and export on rotated sheets',async({page},info)=>{
 const s=await store();await setup(page,s);await page.getByRole('button',{name:'Page 2',exact:true}).click();
 await page.getByRole('button',{name:'Stamps',exact:true}).click();await page.getByLabel('Stamp review status',{exact:true}).selectOption('Reviewed as noted');await page.getByLabel('Stamp reviewer',{exact:true}).fill('Zeth Hummel');await page.getByLabel('Stamp date',{exact:true}).fill('2026-10-02');
 await page.locator('.drawing-overlay').evaluate(svg=>scrollTo(0,scrollY+svg.getBoundingClientRect().top-240));const b=await page.locator('.drawing-overlay').boundingBox();await page.mouse.click(b.x+60,b.y+65);
 await expect(page.locator('.drawing-overlay .drawing-stamp')).toHaveCount(1);await page.getByLabel('Selected stamp review status',{exact:true}).selectOption('Revise and resubmit');
 await expect.poll(()=>s.row.content.marks[0]?.stamp?.status).toBe('Revise and resubmit');expect(s.row.content.marks[0].page).toBe(2);
 await page.locator('.drawing-sheet').screenshot({path:info.outputPath('stamp-view.png')});
 const pending=page.waitForEvent('download');await page.getByRole('button',{name:'Download marked PDF'}).click();const download=await pending;await download.saveAs(info.outputPath('stamp.pdf'));
 const exported=await PDFDocument.load(fs.readFileSync(info.outputPath('stamp.pdf')));expect(exported.getPage(1).getRotation().angle).toBe(90);expect(exported.getPage(1).node.Annots().size()).toBe(1);fs.writeFileSync(info.outputPath('stamp-content.json'),JSON.stringify(s.row.content));
});
test('arrow comment points at the clicked location and exports complete text',async({page},info)=>{
 const s=await store();await setup(page,s);await page.getByRole('button',{name:'Comments',exact:true}).click();await drag(page,70,90,120,60);
 await expect(page.getByLabel('Edit selected comment')).toBeFocused();await page.getByLabel('Edit selected comment').fill('Provide flashing at this opening. Confirm the existing dimension before installation.');
 await expect(page.locator('.drawing-callout text')).toContainText('Provide flashing');
 await expect.poll(()=>s.row.content.marks[0]?.kind).toBe('callout');expect(s.row.content.marks[0].points).toHaveLength(2);
 const pending=page.waitForEvent('download');await page.getByRole('button',{name:'Download marked PDF'}).click();await(await pending).saveAs(info.outputPath('callout.pdf'));await page.locator('.drawing-sheet').screenshot({path:info.outputPath('callout-view.png')});
});
test('snapping uses real vector lines and remains correct after rotation',async({page})=>{
 const s=await store();await setup(page,s);await page.getByRole('button',{name:'Measure',exact:true}).click();await page.getByRole('button',{name:'Snap to lines',exact:true}).click();
 await expect(page.locator('.drawing-snap-hint')).toContainText('Snapping to drawing line');
 const zoom=await page.locator('.drawing-viewbar').evaluate(el=>parseInt([...el.querySelectorAll('span')].find(s=>s.textContent.endsWith('%')).textContent)/100);
 await drag(page,70*zoom+3,(792-600)*zoom+3,300*zoom-5,0);await page.getByLabel('Known length').fill('10');await page.getByRole('button',{name:'Apply page scale'}).click();
 await expect.poll(()=>s.row.content.scales['1']?.reference?.length).toBe(2);const points=s.row.content.scales['1'].reference;expect(points[0].x).toBeCloseTo(70,0);expect(points[0].y).toBeCloseTo(600,0);expect(points[1].x).toBeCloseTo(370,0);expect(points[1].y).toBeCloseTo(600,0);
 await page.getByRole('button',{name:'Rotate view',exact:true}).click();await page.getByRole('button',{name:'Fit width',exact:true}).click();await expect(page.locator('.drawing-snap-hint')).toContainText('Snapping to drawing line');
});
test('page organization survives reload, export and combine without detaching markups',async({page},info)=>{
 const s=await store(),original=Buffer.from(s.bytes);await setup(page,s);await text(page,'Original page one');
 await expect.poll(()=>s.saves).toBeGreaterThan(0);await page.getByRole('button',{name:'Organize pages',exact:true}).click();await page.getByRole('button',{name:'Move page 1 later',exact:true}).click();
 await expect.poll(()=>s.row.content.pageOrder?.join(',')).toBe('2,1');expect(s.row.content.marks[0].page).toBe(1);
 await page.getByRole('button',{name:'Refresh drawings',exact:true}).click();await expect(page.getByLabel('Page number',{exact:true})).toHaveValue('1');await expect(page.locator('.drawing-overlay text')).toHaveCount(0);
 await page.getByRole('button',{name:'Next page',exact:true}).click();await expect(page.locator('.drawing-overlay text')).toContainText('Original page one');
 const pending=page.waitForEvent('download');await page.getByRole('button',{name:'Download marked PDF'}).click();await(await pending).saveAs(info.outputPath('reordered.pdf'));
 const exported=await PDFDocument.load(fs.readFileSync(info.outputPath('reordered.pdf')));expect(exported.getPage(0).getRotation().angle).toBe(90);expect(exported.getPage(1).node.Annots().size()).toBe(1);
 await page.getByLabel('PDFs to combine',{exact:true}).setInputFiles({name:'More sheets.pdf',mimeType:'application/pdf',buffer:original});await page.getByRole('button',{name:'Create combined PDF',exact:true}).click();
 await expect(page.getByLabel('Drawing title',{exact:true})).toHaveValue(/Combined/);await expect(page.getByLabel('Page number',{exact:true})).toHaveAttribute('max','4');await expect.poll(()=>s.row.content.marks[0]?.page).toBe(2);expect(original.equals(s.bytes)).toBe(true);
 const result=await load('drawing-pdf').combinedDrawingPdf(original,{version:1,marks:[{...s.row.content.marks[0],page:1}],scales:{'1':{unit:'ft',unitsPerPoint:1,knownLength:1,reference:[]}},pageOrder:[2,1]},[original]);
 expect((await PDFDocument.load(result.bytes)).getPageCount()).toBe(4);expect(result.content.marks[0].page).toBe(2);expect(result.content.scales['2'].unit).toBe('ft');
});
test('full screen has an exit button and Escape restores the Portal viewer',async({page})=>{
 const s=await store();await setup(page,s);await page.getByRole('button',{name:'Full screen',exact:true}).click();await expect(page.getByRole('button',{name:'Exit full screen',exact:true})).toBeVisible();
 const bounds=await page.locator('.drawing-viewer').boundingBox();expect(bounds.x).toBe(0);expect(bounds.y).toBe(0);
 await page.getByRole('button',{name:'Exit full screen',exact:true}).click();await expect(page.getByRole('button',{name:'Full screen',exact:true})).toBeVisible();
 await page.evaluate(()=>{Object.defineProperty(HTMLElement.prototype,'requestFullscreen',{configurable:true,value:undefined});});await page.getByRole('button',{name:'Full screen',exact:true}).click();await page.keyboard.press('Escape');await expect(page.getByRole('button',{name:'Full screen',exact:true})).toBeVisible();
});
for(const width of [390,1440])test(`edge panel tabs reopen without losing page or markups at ${width}px`,async({page},info)=>{
 await page.setViewportSize({width,height:1000});const s=await store();await setup(page,s);await text(page,'Keep this review note');await expect.poll(()=>s.row.content.marks.length).toBe(1);
 await page.getByRole('button',{name:'Page 2',exact:true}).click();const stage=page.getByLabel('PDF drawing view',{exact:true}),before=await stage.boundingBox(),revision=s.row.revision;
 await page.getByRole('button',{name:'Hide pages',exact:true}).click();await expect(page.getByLabel('Page thumbnails',{exact:true})).toHaveCount(0);
 const closedPages=page.getByRole('button',{name:'Show pages',exact:true});await expect(closedPages).toHaveAttribute('aria-expanded','false');expect((await stage.boundingBox()).width).toBeGreaterThan(before.width);
 await page.getByRole('button',{name:'Hide markup panel',exact:true}).click();await expect(page.getByLabel('Drawing comments',{exact:true})).toHaveCount(0);await expect(page.getByRole('button',{name:'Show markup panel',exact:true})).toBeVisible();
 await expect(page.getByLabel('Page number',{exact:true})).toHaveValue('2');expect(s.row.revision).toBe(revision);
 await page.locator('.drawing-workspace').screenshot({path:info.outputPath(`closed-panels-${width}.png`)});
 await closedPages.focus();await page.keyboard.press('Enter');await expect(page.getByRole('button',{name:'Page 2',exact:true})).toHaveAttribute('aria-current','page');
 await page.getByRole('button',{name:'Show markup panel',exact:true}).focus();await page.keyboard.press('Space');await expect(page.getByLabel('Drawing comments',{exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Page 1',exact:true}).click();await expect(page.locator('.drawing-overlay text')).toContainText('Keep this review note');
 await page.getByRole('button',{name:'Full screen',exact:true}).click();await page.getByRole('button',{name:'Hide pages',exact:true}).click();await page.getByRole('button',{name:'Hide markup panel',exact:true}).click();
 await expect(page.getByRole('button',{name:'Show pages',exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Show markup panel',exact:true})).toBeVisible();
 await page.getByRole('button',{name:'Show pages',exact:true}).click();await page.getByRole('button',{name:'Show markup panel',exact:true}).click();await expect(page.locator('.drawing-overlay text')).toContainText('Keep this review note');
 await page.screenshot({path:info.outputPath(`fullscreen-panels-${width}.png`)});await page.getByRole('button',{name:'Exit full screen',exact:true}).click();
 expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(width);
});
test('Ctrl wheel zoom follows the pointer without changing pages or browser scale',async({page})=>{
 await page.setViewportSize({width:1440,height:1000});const s=await store();await setup(page,s);await text(page,'Zoom keeps markups');await expect.poll(()=>s.row.content.marks.length).toBe(1);
 const saved=JSON.stringify(s.row.content),stage=page.getByLabel('PDF drawing view',{exact:true});await page.getByRole('button',{name:'Hide pages',exact:true}).click();await page.getByRole('button',{name:'Hide markup panel',exact:true}).click();await page.getByRole('button',{name:'Fit width',exact:true}).click();await stage.scrollIntoViewIfNeeded();
 const zoom=()=>page.locator('.drawing-viewbar').evaluate(el=>parseInt([...el.querySelectorAll('span')].find(s=>s.textContent.endsWith('%')).textContent));
 const b=await stage.boundingBox(),pointer={x:b.x+b.width*.6,y:b.y+Math.min(200,b.height*.4)};
 const atPointer=()=>page.locator('.drawing-sheet').evaluate((el,p)=>{const r=el.getBoundingClientRect();return{x:(p.x-r.left)/r.width,y:(p.y-r.top)/r.height};},pointer);
 const start=await zoom(),anchor=await atPointer(),browser=await page.evaluate(()=>({width:innerWidth,scale:visualViewport.scale}));
 await page.mouse.move(pointer.x,pointer.y);await page.keyboard.down('Control');await page.mouse.wheel(0,-160);await expect.poll(zoom).toBeGreaterThan(start);
 await expect.poll(async()=>Math.abs((await atPointer()).x-anchor.x)).toBeLessThan(.004);await expect.poll(async()=>Math.abs((await atPointer()).y-anchor.y)).toBeLessThan(.004);
 const higher=await zoom();await page.mouse.wheel(0,160);await expect.poll(zoom).toBeLessThan(higher);await page.keyboard.up('Control');
 await expect(page.getByLabel('Page number',{exact:true})).toHaveValue('1');expect(await page.evaluate(()=>({width:innerWidth,scale:visualViewport.scale}))).toEqual(browser);expect(JSON.stringify(s.row.content)).toBe(saved);
 await stage.evaluate(el=>el.scrollTop=el.scrollHeight);await page.keyboard.down('Control');await page.mouse.wheel(0,100);await page.keyboard.up('Control');await expect(page.getByLabel('Page number',{exact:true})).toHaveValue('1');
 await page.waitForTimeout(900);await stage.evaluate(el=>el.scrollTop=el.scrollHeight);await page.mouse.wheel(0,220);await expect(page.getByLabel('Page number',{exact:true})).toHaveValue('2');
});
test('click click distance and draggable offset preserve endpoints and calibrated length',async({page},info)=>{
 const s=await store();await setup(page,s);await page.getByRole('button',{name:'Measure',exact:true}).click();await drag(page,70,90,130);await page.getByLabel('Known length').fill('10');await page.getByRole('button',{name:'Apply page scale'}).click();
 await page.locator('.drawing-overlay').evaluate(svg=>scrollTo(0,scrollY+svg.getBoundingClientRect().top-240));let b=await page.locator('.drawing-overlay').boundingBox();await page.mouse.click(b.x+70,b.y+150);await page.mouse.move(b.x+200,b.y+150);
 expect(s.row.content.marks.length).toBe(0);await expect(page.locator('.drawing-dimension')).toHaveCount(1);await page.mouse.click(b.x+200,b.y+150);await expect.poll(()=>s.row.content.marks.length).toBe(1);
 const original=JSON.stringify(s.row.content.marks[0].points),label=load('drawing-model').measurement(s.row.content.marks[0],s.row.content.scales['1']);expect(label).toBe('10 ft 0 in');
 await page.mouse.move(b.x+135,b.y+150);await page.mouse.down();await page.mouse.move(b.x+135,b.y+205,{steps:6});await page.mouse.up();
 await expect.poll(()=>Math.abs(s.row.content.marks[0]?.dimensionOffset??0)).toBeGreaterThan(20);expect(JSON.stringify(s.row.content.marks[0].points)).toBe(original);expect(load('drawing-model').measurement(s.row.content.marks[0],s.row.content.scales['1'])).toBe(label);
 const pending=page.waitForEvent('download');await page.getByRole('button',{name:'Download marked PDF'}).click();await(await pending).saveAs(info.outputPath('offset-dimension.pdf'));await page.locator('.drawing-sheet').screenshot({path:info.outputPath('offset-view.png')});
 await page.getByRole('button',{name:'Refresh drawings',exact:true}).click();await expect(page.locator('.drawing-dimension-label')).toContainText(label);await expect.poll(()=>s.row.content.marks[0].dimensionOffset).not.toBe(0);
});

test('larger PDFs upload in resumable chunks with retry and progress, never upsert',async({page})=>{
 test.setTimeout(45000);const s=await store();await setup(page,s);
 const doc=await PDFDocument.load(s.bytes);doc.context.register(doc.context.stream(new Uint8Array(26*1024*1024)));const bytes=Buffer.from(await doc.save({useObjectStreams:false}));expect(bytes.length).toBeGreaterThan(25*1024*1024);
 let offset=0,failed=false,heads=0,metadata='',chunks=[];
 await page.evaluate(()=>{const factory=window.createJgcSupabaseClient;window.createJgcSupabaseClient=()=>{const c=factory();c.auth.getSession=async()=>({data:{session:{access_token:'test-access'}},error:null});return c;};window.__drawingUploadChunks=[];const send=XMLHttpRequest.prototype.send;XMLHttpRequest.prototype.send=function(body){if(body instanceof Blob)window.__drawingUploadChunks.push(body.size);return send.call(this,body);};});
 await page.route('https://drawings.example.test/storage/v1/upload/resumable**',async route=>{
  const request=route.request(),headers=request.headers(),method=request.method();expect(headers['x-upsert']??'false').toBe('false');
  const common={'Tus-Resumable':'1.0.0','Upload-Offset':String(offset),'Upload-Length':String(bytes.length),'Access-Control-Allow-Origin':'*','Access-Control-Expose-Headers':'Location, Upload-Offset, Upload-Length, Tus-Resumable'};
  if(method==='POST'){metadata=headers['upload-metadata'];return route.fulfill({status:201,headers:{...common,Location:'https://drawings.example.test/storage/v1/upload/resumable/test-upload'}});}
  if(method==='HEAD'){heads++;return route.fulfill({status:200,headers:common});}
  if(method==='PATCH'){if(offset>0&&!failed){failed=true;return route.fulfill({status:503,headers:common});}expect(Number(headers['upload-offset'])).toBe(offset);const chunk=request.postDataBuffer();/* Playwright WebKit omits Blob bodies; observe actual XHR.send Blob size instead. */const size=chunk?.length??await page.evaluate(()=>window.__drawingUploadChunks.at(-1));expect(size).toBeGreaterThan(0);chunks.push(size);offset+=size;await new Promise(resolve=>setTimeout(resolve,100));return route.fulfill({status:204,headers:{...common,'Upload-Offset':String(offset)}});}
  return route.fulfill({status:204,headers:common});
 });
 await page.locator('.drawing-heading input[type=file]').setInputFiles({name:'Large drawing.pdf',mimeType:'application/pdf',buffer:bytes});await expect(page.getByRole('status').filter({hasText:'Uploading drawing'})).toBeVisible();
 await expect(page.getByLabel('Drawing title',{exact:true})).toHaveValue('Large drawing',{timeout:30000});expect(offset).toBe(bytes.length);expect(heads).toBeGreaterThan(0);expect(failed).toBe(true);expect(Math.max(...chunks)).toBe(6*1024*1024);expect(metadata).toContain('bucketName');expect(s.row.file_name).toBe('Large drawing.pdf');
});
test('upload rejects files beyond the current 50 MB cap before contacting storage',async()=>{
 const api=load('../src/drawings-api');await expect(api.addDrawing('job',{size:51*1024*1024})).rejects.toThrow('50 MB');
});
