const { test, expect } = require('@playwright/test');
const { directoryState, serveDirectory, openDirectoryJob } = require('./fixtures/job-readability-fixture');
for (const width of [1280,390]) test(`customer reference edits and compact controls persist at ${width}`,async({page},testInfo)=>{
 const state=directoryState(); state.jobs[0].clientReference='OLD-PO'; state.jobs[0].projectManager='Zeth Hummel';
 const captures=await serveDirectory(page,state); await page.setViewportSize({width,height:1000}); await openDirectoryJob(page,'26901'); await page.getByRole('tab',{name:'Summary',exact:true}).click();
 await page.getByRole('button',{name:'Edit job details',exact:true}).click(); await page.getByLabel('Customer PO/WO #',{exact:true}).fill('CUSTOMER-WO-2026'); await page.getByLabel('Start date',{exact:true}).fill('2026-09-22'); await page.getByLabel('Target completion',{exact:true}).fill('2026-10-05'); await page.getByRole('button',{name:'Save job details',exact:true}).click();
 await expect(page.locator('.job-summary-facts')).toContainText('CUSTOMER-WO-2026'); await expect(page.locator('.job-header-dates')).toContainText('2026');
 await expect.poll(()=>captures.writes.at(-1)?.jobs.find(j=>j.jobNumber==='26901')?.clientReference).toBe('CUSTOMER-WO-2026');
 expect(captures.writes.at(-1).jobs[0].acceptedQuoteSnapshot).toBe(state.jobs[0].acceptedQuoteSnapshot);
 await page.getByRole('button',{name:'← All jobs',exact:true}).click(); const row=page.locator('.jobs-table tbody tr').filter({hasText:'26901'}); await expect(row).toContainText('CUSTOMER-WO-2026'); await expect(row.locator('abbr')).toHaveText('ZH'); await expect(row.locator('.job-status-dot')).toHaveAttribute('aria-label','Active'); await row.locator('summary').click(); await expect(row.getByRole('button',{name:/Close — Discuss Invoice/})).toBeVisible(); await expect(row.getByRole('button',{name:/Cancel Project/})).toBeVisible();
 await row.locator('summary').click(); await page.locator('.job-directory-page').screenshot({path:testInfo.outputPath('compact-jobs.png')}); await row.locator('button.back-button').click(); await page.getByRole('tab',{name:'Summary',exact:true}).click(); await page.getByRole('button',{name:'Edit job details',exact:true}).click(); await page.getByLabel('Customer PO/WO #',{exact:true}).fill(''); await page.getByRole('button',{name:'Save job details',exact:true}).click(); await expect.poll(()=>captures.writes.at(-1)?.jobs.find(j=>j.jobNumber==='26901')?.clientReference).toBe('');
});
test('official job deep link opens inactive Estimator job',async({page})=>{await serveDirectory(page,directoryState());await page.goto('/estimating/index.html?dev=1&view=jobs&job=25904');await expect(page.locator('.job-detail-page')).toContainText('JOB 25904');});
test('failed metadata save does not change customer reference',async({page})=>{const state=directoryState();state.jobs[0].clientReference='KEEP'; const captures=await serveDirectory(page,state,{failJobInfo:true});await openDirectoryJob(page,'26901');await page.getByRole('tab',{name:'Summary',exact:true}).click();await page.getByRole('button',{name:'Edit job details',exact:true}).click();await page.getByLabel('Customer PO/WO #',{exact:true}).fill('DO-NOT-SAVE');await page.getByRole('button',{name:'Save job details',exact:true}).click();await expect(page.locator('.job-documents-status.error')).toContainText('rejected');expect(captures.writes.some(s=>s.jobs[0].clientReference==='DO-NOT-SAVE')).toBe(false);});

test('Change Status can close for invoice discussion without losing job history',async({page})=>{
 const state=directoryState();const captures=await serveDirectory(page,state);const row=page.locator('.jobs-table tbody tr').filter({hasText:'26901'});await row.locator('summary').click();page.once('dialog',d=>d.accept());await row.getByRole('button',{name:'Close — Discuss Invoice — job 26901',exact:true}).click();await expect.poll(()=>captures.jobInfo.length).toBe(1);expect(captures.jobInfo[0].body).toMatchObject({active:false,invoiceReview:true});await expect.poll(()=>captures.writes.at(-1)?.jobs[0].invoiceReviewAt).toBeTruthy();expect(captures.writes.at(-1).jobs[0].acceptedQuoteSnapshot).toBe(state.jobs[0].acceptedQuoteSnapshot);
});
test('updated customer PO survives a fresh load',async({page})=>{
 const state=directoryState();const captures=await serveDirectory(page,state);await openDirectoryJob(page,'26901');await page.getByRole('tab',{name:'Summary',exact:true}).click();await page.getByRole('button',{name:'Edit job details',exact:true}).click();await page.getByLabel('Customer PO/WO #',{exact:true}).fill('AFTER-CREATION-PO');await page.getByRole('button',{name:'Save job details',exact:true}).click();await expect.poll(()=>captures.writes.at(-1)?.jobs[0].clientReference).toBe('AFTER-CREATION-PO');await serveDirectory(page,captures.writes.at(-1));await expect(page.locator('.jobs-table tbody tr').filter({hasText:'26901'})).toContainText('AFTER-CREATION-PO');
});
