const {test,expect}=require('@playwright/test');
const fs=require('node:fs'),path=require('node:path'),ts=require('../estimating-app/node_modules/typescript');
const cache={};
function load(name){if(cache[name])return cache[name];const m={exports:{}};Function('exports','module','require',ts.transpileModule(fs.readFileSync(path.resolve(__dirname,'../estimating-app/lib/'+name+'.ts'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(m.exports,m,n=>n.startsWith('.')?load(n.replace(/^\.\//,'')):require('../estimating-app/node_modules/'+n));cache[name]=m.exports;return m.exports;}
const w=load('job-schedule'),merge=load('estimator-state-sync').mergeConcurrentEstimatorState;
const activity=(id,name,start,finish,overrides={})=>({...w.blankTask(start,'Preparation'),id,name,start,finish,owner:'JGC',...overrides});
function fixture(schedule){const state=load('estimator-data').createDefaultState();state.clients=[{id:'client',name:'Example Client',contact:'',email:'',phone:'',contacts:[],sites:[],notes:''}];state.quotes=[];state.priceBook=[];state.jobs=[{id:'job',jobNumber:'26999',quoteId:'',clientId:'client',project:'Washroom and Control Room',status:'Active',portalJobId:'portal-job',portalActive:true,portalCustomer:'Example Client',portalSiteName:'Main Office',portalAddress:'123 Example Street, Cornwall',projectManager:'Test Admin',startDate:'2026-10-05',targetEndDate:'2026-11-27',acceptedRevenue:0,originalCostBudget:0,approvedRevenueChanges:0,approvedCostChanges:0,estimateToComplete:0,acceptedAt:'2026-10-01T12:00:00Z',costs:[],notes:'',...(schedule?{schedule}:{})}];return state;}
const seed=()=>w.commitSchedule([
 activity('a','Shop drawings','2026-10-05','2026-10-09',{progress:40,notes:'Review the architectural detail before ordering.'}),
 activity('b','Concrete curing','2026-10-12','2026-10-18',{phase:'Rough-ins',calendar:'calendar'}),
 activity('c','Painting','2026-10-19','2026-10-23',{phase:'Finishes',owner:'Painting subcontractor'}),
],undefined,'Test Admin','Initial plan');
async function setup(page,schedule){let state=fixture(schedule);const saved=[];await page.route('**/api/**',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({actuals:[],jobs:[],rows:[]})}));await page.route('**/api/state',async r=>{if(r.request().method()==='PUT'){state=r.request().postDataJSON().state;saved.push(state);return r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({saved:true,updatedAt:new Date().toISOString()})});}return r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({state,updatedAt:'2026-10-01T12:00:00Z'})});});await page.goto('/estimating/index.html?dev=1&view=jobs&job=26999');await expect(page.locator('.job-detail-page')).toContainText('26999');await page.getByRole('tab',{name:'Schedule',exact:true}).click();await expect(page.locator('.job-schedule')).toBeVisible();return saved;}

test('working dates survive weekends, leap day and time changes; calendar durations count curing days',()=>{
 expect(w.finishFor('2026-10-02',5,'weekdays')).toBe('2026-10-08');
 expect(w.finishFor('2026-10-02',5,'calendar')).toBe('2026-10-06');
 expect(w.duration(activity('a','Work','2026-10-02','2026-10-08'))).toBe(5);
 expect(w.finishFor('2028-02-28',4,'calendar')).toBe('2028-03-02');
 expect(w.finishFor('2026-10-30',3,'weekdays')).toBe('2026-11-03');
 expect(Number.isNaN(w.dateNumber('2026-02-30'))).toBe(true);
});
test('explicit links cascade through chains, leave parallel work alone and reject cycles',()=>{
 const a=activity('a','Demolition','2026-10-05','2026-10-09'),b=activity('b','Patch','2026-10-05','2026-10-06',{predecessorId:'a',lag:2}),c=activity('c','Paint','2026-10-05','2026-10-09',{predecessorId:'b'}),d=activity('d','Parallel electrical','2026-10-05','2026-10-09');
 const tasks=w.reflowTasks([c,b,a,d]);expect(tasks[1].start).toBe('2026-10-12');expect(tasks[0].start).toBe('2026-10-14');expect(tasks[3]).toEqual(d);
 expect(w.validateTask({...a,predecessorId:'c'},tasks).predecessorId).toContain('circular');expect(()=>w.reflowTasks([{...a,predecessorId:'b'},b])).toThrow('circular');
});
test('revisions preserve issued dates and reject competing schedules, stale retry and removed history',()=>{
 const base=seed(),local=w.commitSchedule(base.tasks.map(t=>t.id==='a'?w.moveTask(t,'2026-10-12'):t),base,'First admin','Revised'),remote=w.commitSchedule(base.tasks.map(t=>t.id==='a'?w.moveTask(t,'2026-10-19'):t),base,'Second admin','Competing');
 const state=s=>({jobs:[{id:'job',schedule:s}],quotes:[]});
 expect(base.revisions[0].tasks[0].start).toBe('2026-10-05');expect(local.revisions).toHaveLength(2);
 expect(w.schedulePersistenceError(state(base),state(local))).toBe('');expect(merge(state(base),state(local),state(remote)).state).toBeNull();
 expect(w.schedulePersistenceError(state(remote),state(local))).toContain('another browser');expect(w.schedulePersistenceError(state(base),state({...local,revisions:[local.revisions[1]]}))).toContain('unchanged');
 const other={...state(base),quotes:[{id:'q',name:'Remote quote'}]};expect(merge(state(base),state(local),other).state.jobs[0].schedule).toEqual(local);
});
test('optional empty state never creates a schedule on opening or cancelling',async({page})=>{
 const saves=await setup(page);await expect(page.locator('.schedule-empty')).toContainText('Jobs never need a schedule');await page.getByRole('button',{name:'Create schedule',exact:true}).click();await page.getByRole('button',{name:'Cancel editing'}).click();await expect(page.locator('.schedule-empty')).toBeVisible();expect(saves).toHaveLength(0);
});
test('required information, date/duration editing, saving, reload and read-only activity notes',async({page})=>{
 const saves=await setup(page);await page.getByRole('button',{name:'Create schedule',exact:true}).click();await page.getByRole('button',{name:'Add first activity',exact:false}).click();const dialog=page.getByRole('dialog',{name:'Schedule activity editor'});await dialog.getByRole('button',{name:'Apply to draft'}).click();await expect(dialog).toContainText('An activity name is required');await dialog.getByLabel('Activity name *').fill('Concrete cure');await dialog.getByLabel('Start date *').fill('2026-10-02');await dialog.getByLabel('Count days as').selectOption('calendar');await dialog.getByLabel('Duration (days)').fill('7');await expect(dialog.getByLabel('Finish date *')).toHaveValue('2026-10-08');await dialog.getByRole('button',{name:'Apply to draft'}).click();await page.getByRole('tab',{name:'Summary',exact:true}).click();await page.getByRole('tab',{name:'Schedule',exact:true}).click();await expect(page.locator('.schedule-task-name')).toContainText('Concrete cure');await page.getByRole('button',{name:'Save schedule',exact:true}).click();await expect.poll(()=>saves.at(-1)?.jobs[0]?.schedule?.revision).toBe(1);expect(saves.at(-1).jobs[0].startDate).toBe('2026-10-05');await page.reload();await page.getByRole('tab',{name:'Schedule',exact:true}).click();await expect(page.locator('.schedule-task-name')).toContainText('7 calendar days');await page.locator('.schedule-task-name').click();await expect(page.getByRole('dialog',{name:'Activity details'})).toContainText('Concrete cure');await expect(page.getByRole('dialog').locator('input')).toHaveCount(0);await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).toHaveCount(0);
});
test('bar moves, resize, undo and cancel stay in a draft until saved',async({page})=>{
 const saves=await setup(page,seed());await page.getByRole('button',{name:'Edit schedule',exact:true}).click();const bar=page.getByRole('button',{name:/Shop drawings: .*drag to move/}),b=await bar.boundingBox();await page.mouse.move(b.x+25,b.y+12);await page.mouse.down();await page.mouse.move(b.x+25+7*18,b.y+12,{steps:5});await page.mouse.up();await expect(page.locator('.schedule-task-name').first()).toContainText('Oct 12');await page.getByRole('button',{name:'Undo',exact:true}).click();await expect(page.locator('.schedule-task-name').first()).toContainText('Oct 5');const handle=page.getByRole('button',{name:'Resize Shop drawings'}),h=await handle.boundingBox();await page.mouse.move(h.x+10,h.y+18);await page.mouse.down();await page.mouse.move(h.x+10+7*18,h.y+18,{steps:5});await page.mouse.up();await expect(page.locator('.schedule-task-name').first()).toContainText('10 working days');expect(saves).toHaveLength(0);page.once('dialog',d=>d.accept());await page.getByRole('button',{name:'Cancel editing'}).click();await expect(page.locator('.schedule-task-name').first()).toContainText('5 working days');
});
for(const theme of ['light','dark'])for(const viewport of [{width:1440,height:1000},{width:390,height:844}])test(`Gantt ${theme} ${viewport.width}: contained timeline, details and export`,async({page},testInfo)=>{
 await page.setViewportSize(viewport);await page.addInitScript(t=>{localStorage.setItem('jgcTheme',t);document.documentElement.setAttribute('data-jgc-theme',t);},theme);await setup(page,seed());await page.evaluate(t=>document.documentElement.setAttribute('data-jgc-theme',t),theme);await expect(page.locator('.schedule-scroll')).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.getByRole('button',{name:'Fit',exact:true}).click();await page.locator('.job-schedule').screenshot({path:testInfo.outputPath(`gantt-${theme}-${viewport.width}.png`)});await page.locator('.schedule-task-name').first().click();await expect(page.getByRole('dialog')).toContainText('Review the architectural detail');await page.getByRole('button',{name:'Close details'}).click();const pending=page.waitForEvent('download');await page.getByRole('button',{name:'Download schedule PDF',exact:true}).click();const pdf=await pending;expect(pdf.suggestedFilename()).toBe('26999 Job Schedule Rev 1.pdf');await pdf.saveAs(testInfo.outputPath('schedule.pdf'));expect(fs.statSync(testInfo.outputPath('schedule.pdf')).size).toBeGreaterThan(5000);
});
test('PDF tiles long dates and activity lists and keeps all task names and client information',async({},testInfo)=>{
 const tasks=Array.from({length:45},(_,i)=>activity('t'+i,'Unique activity '+i,'2026-10-05',w.addDays('2026-10-05',110),{calendar:'calendar',phase:i<20?'Preparation':'Finishes',owner:'Test contractor'}));const schedule=w.commitSchedule(tasks,undefined,'Test Admin','Long timeline');const state=fixture(schedule),bytes=await load('job-schedule-pdf').buildSchedulePdf({job:state.jobs[0],state,schedule,logoBytes:fs.readFileSync(path.resolve(__dirname,'../estimating/jgc-logo-transparent.png'))});const doc=await require('../estimating-app/node_modules/pdf-lib').PDFDocument.load(bytes);expect(doc.getPageCount()).toBeGreaterThanOrEqual(4);for(const p of doc.getPages())expect(p.getSize()).toEqual({width:1224,height:792});fs.writeFileSync(testInfo.outputPath('long-schedule.pdf'),bytes);
});
