const {test,expect}=require('@playwright/test');
const fs=require('node:fs'),path=require('node:path'),{pathToFileURL}=require('node:url'),ts=require('../estimating-app/node_modules/typescript');
const cache={};function load(name){if(cache[name])return cache[name];const m={exports:{}};Function('exports','module','require',ts.transpileModule(fs.readFileSync(path.resolve(__dirname,'../estimating-app/lib/'+name+'.ts'),'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText)(m.exports,m,n=>n.startsWith('.')?load(n.replace(/^\.\//,'')):require('../estimating-app/node_modules/'+n));cache[name]=m.exports;return m.exports;}
const model=load('site-specific'),merge=load('estimator-state-sync').mergeConcurrentEstimatorState;
function fixture(){const s=load('estimator-data').createDefaultState();s.clients=[{id:'client',name:'Synthetic client',contact:'',email:'',phone:'',contacts:[],sites:[],notes:''}];s.quotes=[];s.priceBook=[];s.jobs=[{id:'job',jobNumber:'26999',quoteId:'',clientId:'client',project:'Safety Plan QA Project',status:'Active',portalJobId:'portal-job',portalActive:true,portalCustomer:'Synthetic client',portalAddress:'123 Synthetic Street, Cornwall',projectManager:'QA Administrator',acceptedRevenue:0,originalCostBudget:0,approvedRevenueChanges:0,approvedCostChanges:0,estimateToComplete:0,acceptedAt:'2026-10-01T12:00:00Z',costs:[],notes:''}];return s;}
async function documents(){const {PDFDocument,StandardFonts,degrees}=require('../estimating-app/node_modules/pdf-lib');const policy=await PDFDocument.create(),font=await policy.embedFont(StandardFonts.Helvetica);for(let i=1;i<=184;i++)policy.addPage([612,792]).drawText('ORIGINAL POLICY PAGE '+i,{x:50,y:700,font,size:12});const cert=await PDFDocument.create(),f=await cert.embedFont(StandardFonts.Helvetica);cert.addPage([612,792]).drawText('SYNTHETIC TRAINING CERTIFICATE',{x:50,y:700,font:f,size:12});const reverse=cert.addPage([612,792]);reverse.setRotation(degrees(90));reverse.drawText('CERTIFICATE REVERSE PAGE',{x:50,y:700,font:f,size:12,rotate:degrees(90)});return {policy:Buffer.from(await policy.save()).toString('base64'),cert:Buffer.from(await cert.save()).toString('base64')};}
async function setup(page,{theme='light',width=1440,seed}={}) {let state=seed||fixture();const saves=[];await page.setViewportSize({width,height:980});await page.addInitScript(theme=>{localStorage.setItem('jgcPortalThemeGuest',theme);localStorage.setItem('jgcPortalTheme',theme);},theme);await page.route('**/*.supabase.co/**',r=>r.fulfill({status:403,json:{message:'Isolated fixture'}}));await page.route('**/api/**',r=>r.fulfill({status:200,json:{actuals:[],jobs:[],rows:[]}}));await page.route('**/api/state',async r=>{if(r.request().method()==='PUT'){state=r.request().postDataJSON().state;saves.push(structuredClone(state));return r.fulfill({status:200,json:{saved:true,updatedAt:new Date().toISOString()}});}return r.fulfill({status:200,json:{state,updatedAt:'2026-10-05T12:00:00Z'}});});await page.goto('/estimating/index.html?dev=1&view=jobs&job=26999');await expect(page.locator('.job-detail-page')).toBeVisible();await page.getByRole('tab',{name:'Safety',exact:true}).click();await page.getByRole('tab',{name:'Create Site Specific',exact:true}).click();await expect(page.getByRole('heading',{name:'Plan details',exact:true})).toBeVisible();await page.evaluate(t=>document.documentElement.setAttribute('data-jgc-theme',t),theme);return {saves,getState:()=>state};}
async function client(page,data,{deny=false,uploadFail=false}={}) {await page.evaluate(({data,deny,uploadFail})=>{window.__safetyCalls=[];window.__safetyFail=uploadFail;window.__safetyDenied=deny;const decode=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));const b={id:'qa-board',token:'qa-token',enabled:true,can_manage:true,documents:[{id:'qa-policy',category:'jgc-policy',title:'JGC full policy',mime_type:'application/pdf',status:'published'},{id:'qa-jsa',category:'jsa',title:'Standard job JSA',mime_type:'application/pdf',status:'published'}]};let id=0;
 window.createJgcSupabaseClient=()=>({supabaseUrl:'https://qa.supabase.co',auth:{getSession:async()=>({data:{session:{user:{id:'qa-admin'}}}})},from:table=>{let rowId='';const q={select:()=>q,eq:(key,value)=>{rowId=value;return q;},order:()=>q,range:async()=>({data:table==='certificates'?[{id:'qa-cert',worker_name:'Synthetic worker',certificate_name:'Training',file_path:'qa/cert.pdf',file_name:'cert.pdf',file_type:'application/pdf',expiry_date:'2027-10-05'}]:[]}),maybeSingle:async()=>({data:table==='profiles'?{role:window.__safetyDenied?'worker':'admin',account_status:'approved'}:{file_path:'qa/cert.pdf'}})};return q;},rpc:async(name,args)=>{window.__safetyCalls.push({name,args});if(name==='get_or_create_job_board')return {data:b};if(name==='get_job_board_jsa')return {data:{acknowledgements:[]}};if(name==='begin_job_board_upload'){id++;return {data:{id:'upload-'+id,object_path:'qa-board/upload-'+id+'/original.pdf'}};}return {data:{id:args.p_document_id,status:name==='finalize_job_board_upload'?'pending':'published'}};},storage:{from:bucket=>({download:async()=>({data:new Blob([decode(data.cert)],{type:'application/pdf'})}),upload:async(objectPath,blob,opts)=>{window.__safetyCalls.push({name:'storage-upload',bucket,objectPath,size:blob.size,opts});if(window.__safetyFail){window.__safetyFail=false;return {error:{message:'offline',statusCode:'503'}};}return {data:{path:objectPath}};}})},functions:{invoke:async(name,{body})=>({data:body.documentId==='qa-jsa'?{sourcePayload:{source_type:'inspection_records',record:{id:'synthetic-jsa',inspection_type:'JSA',inspection_date:'2026-10-05',project:'QA Project',form_data:{fields:[{label:'Date',value:'2026-10-05'},{label:'Project',value:'QA JSA Project'},{label:'What work will be done?',value:'SYNTHETIC JSA WORK'}],rows:[{cells:['SYNTHETIC JSA WORK','Synthetic hazard','Synthetic controls / PPE']}]}}}}:{pdfBase64:data.policy,mimeType:'application/pdf'}})}});}, {data,deny,uploadFail});}
async function saved(page){await page.getByRole('button',{name:'Save plan',exact:true}).click();await expect(page.getByRole('button',{name:'Download PDF',exact:true})).toBeEnabled({timeout:12000});}
async function texts(file){const pdfjs=await import(pathToFileURL(path.resolve(__dirname,'../estimating-app/node_modules/pdfjs-dist/legacy/build/pdf.mjs')).href),pdf=await pdfjs.getDocument({data:new Uint8Array(fs.readFileSync(file)),disableWorker:true,standardFontDataUrl:path.resolve(__dirname,'../estimating-app/node_modules/pdfjs-dist/standard_fonts').replaceAll('\\','/')+'/'}).promise,values=[];for(let i=1;i<=pdf.numPages;i++)values.push((await (await pdf.getPage(i)).getTextContent()).items.map(x=>x.str).join(' '));return {pages:pdf.numPages,text:values.join('\n'),values};}
test('plan dates and concurrent saves prevent invalid dates and silently mixing a single plan',()=>{const s=fixture(),p=model.createSitePlan(s.jobs[0],'QA');p.planDate='2026-02-31';expect(model.sitePlanErrors(p)).toContain('Valid plan date');p.planDate='2028-02-29';expect(model.sitePlanErrors(p)).not.toContain('Valid plan date');s.jobs[0].siteSpecific=p;const a=structuredClone(s),b=structuredClone(s);a.jobs[0].siteSpecific.pages[0].fields[0].value='A';b.jobs[0].siteSpecific.pages[0].fields[1].value='B';expect(merge(s,a,b).state).toBeNull();const c=structuredClone(s);c.jobs[0].notes='Other field';expect(merge(s,a,c).state.jobs[0].siteSpecific.pages[0].fields[0].value).toBe('A');});
for(const theme of ['light','dark'])for(const width of [390,1440])test(`plan fields, toggles, reusable page copies and layout ${theme} ${width}`,async({page},info)=>{test.setTimeout(60000);const store=await setup(page,{theme,width});await page.getByLabel('Prepared by',{exact:true}).fill('QA Author');await page.getByRole('button',{name:'Pages',exact:true}).click();await page.getByRole('textbox',{name:'Scope of work',exact:true}).fill('Site-specific QA scope');await page.getByRole('button',{name:'Save page to library',exact:true}).click();await page.getByRole('button',{name:'Saved pages',exact:true}).click();await page.locator('.ss-library summary').filter({hasText:'Project location and scope'}).click();await page.getByRole('button',{name:'Use in this plan',exact:true}).click();await expect(page.getByRole('textbox',{name:'Scope of work',exact:true})).toHaveValue('Site-specific QA scope');await page.getByLabel('Page title',{exact:true}).fill('Reusable QA scope copy');await page.locator('.ss-page-list summary').click();await page.getByRole('checkbox',{name:'Personal protective equipment',exact:true}).uncheck();await expect(page.locator('.ss-overview')).not.toContainText('Personal protective equipment');await expect.poll(()=>store.saves.at(-1)?.jobs[0].siteSpecific.pages.some(p=>p.title==='Reusable QA scope copy')).toBe(true);expect(store.getState().safetyLibrary[0].title).toBe('Project location and scope');await page.getByRole('button',{name:'Details',exact:true}).click();await expect(page.getByLabel('Prepared by',{exact:true})).toHaveValue('QA Author');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1)).toBe(true);await page.evaluate(()=>scrollTo(0,0));await page.screenshot({path:info.outputPath('builder-'+theme+'-'+width+'.png'),fullPage:true});await page.reload();await page.getByRole('tab',{name:'Safety',exact:true}).click();await page.getByRole('tab',{name:'Create Site Specific',exact:true}).click();await expect(page.getByLabel('Prepared by',{exact:true})).toHaveValue('QA Author');});
test('combined PDF preserves complete policy, certificate reverse and standard JSA; publish uses this job and selected visibility',async({page},info)=>{test.setTimeout(120000);await setup(page);await client(page,await documents());await page.getByRole('button',{name:'Attachments',exact:true}).click();await page.getByRole('button',{name:'Load Portal documents',exact:true}).click();await page.getByRole('checkbox',{name:/JGC full policy/}).check();await page.getByRole('checkbox',{name:/Synthetic worker/}).check();await page.getByRole('checkbox',{name:/Standard job JSA/}).check();await expect(page.getByLabel('Published PDF access')).toHaveValue('restricted');await saved(page);const event=page.waitForEvent('download',{timeout:60000});await page.getByRole('button',{name:'Download PDF',exact:true}).click();const d=await event,file=info.outputPath(d.suggestedFilename());await d.saveAs(file);const parsed=await texts(file);expect(parsed.pages).toBeGreaterThanOrEqual(195);expect(parsed.text).toContain('ORIGINAL POLICY PAGE 184');expect(parsed.text).toContain('CERTIFICATE REVERSE PAGE');expect(parsed.text).toContain('SYNTHETIC JSA WORK');expect(parsed.text).toContain('PLAN CONTENTS');expect(parsed.values.at(-1)).toContain('Page '+parsed.pages+' of '+parsed.pages);await page.getByRole('button',{name:'Publish to Job Board',exact:true}).click();await expect(page.getByRole('status')).toContainText('published in the Job Board');const calls=await page.evaluate(()=>window.__safetyCalls);expect(calls.filter(c=>c.name==='begin_job_board_upload')).toHaveLength(1);expect(calls.find(c=>c.name==='begin_job_board_upload').args.p_board_id).toBe('qa-board');expect(calls.find(c=>c.name==='review_job_board_document').args.p_visibility).toBe('restricted');});
test('failed publish retains the plan and retries the same reserved upload; extra originals remain separate',async({page})=>{test.setTimeout(60000);await setup(page);await client(page,await documents(),{uploadFail:true});await saved(page);await page.getByRole('button',{name:'Publish to Job Board',exact:true}).click();await expect(page.getByRole('status')).toContainText('Your plan is kept');await page.getByRole('button',{name:'Publish to Job Board',exact:true}).click();await expect(page.getByRole('status')).toContainText('published in the Job Board');let calls=await page.evaluate(()=>window.__safetyCalls);expect(calls.filter(c=>c.name==='begin_job_board_upload')).toHaveLength(1);await page.getByRole('button',{name:'Attachments',exact:true}).click();await page.getByLabel('Additional PDFs, forms or photos').setInputFiles({name:'extra.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4 QA original file')});await page.getByRole('button',{name:'Upload 1 supporting file',exact:true}).click();await expect(page.getByRole('status')).toContainText('saved privately');calls=await page.evaluate(()=>window.__safetyCalls);expect(calls.filter(c=>c.name==='review_job_board_document')).toHaveLength(1);expect(calls.filter(c=>c.name==='begin_job_board_upload')).toHaveLength(2);});
test('attachment failure produces no partial PDF and unapproved access cannot invoke write RPCs',async({page})=>{test.setTimeout(60000);const seed=fixture();seed.jobs[0].siteSpecific=model.createSitePlan(seed.jobs[0],'QA');seed.jobs[0].siteSpecific.updatedAt=new Date().toISOString();seed.jobs[0].siteSpecific.attachments=[{id:'board:gone',kind:'board',boardId:'wrong-board',documentId:'gone',title:'Missing file',included:true,fileName:'gone.pdf'}];await setup(page,{seed});await client(page,await documents());await page.getByRole('button',{name:'Download PDF',exact:true}).click();await expect(page.getByRole('status')).toContainText('No incomplete PDF was exported');await client(page,await documents(),{deny:true});await page.getByRole('button',{name:'Publish to Job Board',exact:true}).click();await expect(page.getByRole('status')).toContainText('Approved administrator access is required');expect(await page.evaluate(()=>window.__safetyCalls)).toHaveLength(0);});


test('saved tasks can be reused across jobs without altering the source job or library version',async({page})=>{
  test.setTimeout(60000);
  const seed=fixture();seed.jobs.push({...structuredClone(seed.jobs[0]),id:'second-job',jobNumber:'26998',project:'Second QA job',portalJobId:'second-portal-job',portalAddress:'456 QA Street'});
  const store=await setup(page,{seed});
  await page.getByRole('button',{name:'Pages',exact:true}).click();
  await page.getByRole('textbox',{name:'Scope of work',exact:true}).fill('First job original scope');
  await page.getByRole('button',{name:'Save page to library',exact:true}).click();
  await expect.poll(()=>store.saves.at(-1)?.safetyLibrary?.length).toBe(1);
  await page.goto('/estimating/index.html?dev=1&view=jobs&job=26998');
  await page.getByRole('tab',{name:'Safety',exact:true}).click();await page.getByRole('tab',{name:'Create Site Specific',exact:true}).click();
  await expect(page.getByLabel('Site address',{exact:true})).toHaveValue('456 QA Street');
  await page.getByRole('button',{name:'Saved pages',exact:true}).click();await page.locator('.ss-library summary').click();
  await page.getByRole('button',{name:'Use in this plan',exact:true}).click();await page.getByRole('textbox',{name:'Scope of work',exact:true}).fill('Second job adapted scope');
  await expect.poll(()=>store.saves.at(-1)?.jobs[1].siteSpecific?.pages.at(-1).fields[0].value).toBe('Second job adapted scope');
  expect(store.getState().jobs[0].siteSpecific.pages[0].fields[0].value).toBe('First job original scope');
  expect(store.getState().safetyLibrary[0].fields[0].value).toBe('First job original scope');
});
